### ISSUE TITLE
V1.3.6 停止客户端后大量错误日志

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#100]
V1.3.6-1 / fake-ip / dns forward

停止客户端后大量错误日志如下：

`Fri Dec 20 23:22:29 2019 daemon.err uhttpd[2394]: /usr/lib/lua/luci/dispatcher.lua:509: Failed to execute call dispatcher target for entry '/admin/services/clash/logstatus'.`
`Fri Dec 20 23:22:29 2019 daemon.err uhttpd[2394]: The called action terminated with an exception:`
`Fri Dec 20 23:22:29 2019 daemon.err uhttpd[2394]: /usr/lib/lua/luci/controller/clash.lua:235: attempt to index local 'f' (a nil value)`
`Fri Dec 20 23:22:29 2019 daemon.err uhttpd[2394]: stack traceback:`
`Fri Dec 20 23:22:29 2019 daemon.err uhttpd[2394]: 	[C]: in function 'assert'`
`Fri Dec 20 23:22:29 2019 daemon.err uhttpd[2394]: 	/usr/lib/lua/luci/dispatcher.lua:509: in function 'dispatch'`
`Fri Dec 20 23:22:29 2019 daemon.err uhttpd[2394]: 	/usr/lib/lua/luci/dispatcher.lua:127: in function </usr/lib/lua/luci/dispatcher.lua:126>`

**Comment by frainzy1477** [comment]
https://github.com/frainzy1477/luci-app-clash/commit/dfa7d8834119c1d118b844f9d166c81e326b026a
你先自己修改

**Comment by wangxin6** [comment]
多谢。
