### ISSUE TITLE
停在重启Dnsmasq程序导致无法使用

### ISSUE THREAD

**Issue by denel23** [frainzy1477/luci-app-clash#103]
帮忙看下config和luci里dns设置在哪儿出问题？请教一下，感谢
![1577458588816](https://user-images.githubusercontent.com/31842977/71521594-620b5180-28fc-11ea-8818-7961530e5d31.jpg)
![1577458616829](https://user-images.githubusercontent.com/31842977/71521602-6cc5e680-28fc-11ea-8a49-0a5af3367236.jpg)
![1577458636091](https://user-images.githubusercontent.com/31842977/71521612-74858b00-28fc-11ea-91cf-5dd9941895c6.jpg)

**Comment by frainzy1477** [comment]
日志呢？？‘’

**Comment by frainzy1477** [comment]
listen: 0.0.0.0:5300 端口53不能使用, 已经在使用中
你的配置有问题， 你先修吧

**Comment by denel23** [comment]
在luci上传有问题，路由器里clash config路径在哪？

**Comment by denel23** [comment]
![1577460522456](https://user-images.githubusercontent.com/31842977/71523358-96ced700-2903-11ea-87af-22ce1942ff2c.jpg)
![1577461780828](https://user-images.githubusercontent.com/31842977/71523361-98000400-2903-11ea-945d-d3db9def207e.jpg)

**Comment by frainzy1477** [comment]
上传的配置有问题

**Comment by frainzy1477** [comment]
日志出来

**Comment by frainzy1477** [comment]
![image](https://user-images.githubusercontent.com/49537471/71524358-27a7b180-2908-11ea-9c85-d80baa6786af.png)

**Comment by denel23** [comment]
下面是路由器日志，luci日志没有记录。。内网外网都无法上网，看不出来哪个问题
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain qq.com
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain msftncsi.com
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain msftconnecttest.com
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain music.163.com
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain music.126.net
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain imap.163.com
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain crash.163.com
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain mr.da.netease.com
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain ac.dun.163yun.com
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain api.iplay.163.com
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain man.netease.com
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain apm3.music.163.com
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain apm.music.163.com
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain interface5.music.163.com
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain interface4.music.163.com
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain interface3.music.163.com
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain interface2.music.163.com
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain interface1.music.163.com
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain interface.music.163.com
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain p5c.music.126.net
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain p4c.music.126.net
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain p3c.music.126.net
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain p2c.music.126.net
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain p1c.music.126.net
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain p5.music.126.net
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain p4.music.126.net
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain p3.music.126.net
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain p2.music.126.net
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain p1.music.126.net
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using nameserver 114.114.114.114#53 for domain music.126.net
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: using 53 more nameservers
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: read /etc/hosts - 4 addresses
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: read /tmp/hosts/dhcp.cfg01411c - 2 addresses
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq[2942]: read /etc/hosts - 4 addresses
Sat Dec 28 10:17:45 2019 daemon.info dnsmasq-dhcp[2942]: read /etc/ethers - 0 addresses

**Comment by denel23** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"frainzy1477"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月28日(星期六) 凌晨0:22
收件人:&nbsp;"frainzy1477/luci-app-clash"<luci-app-clash@noreply.github.com&gt;;
抄送:&nbsp;"宫欣"<1152933035@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [frainzy1477/luci-app-clash] 停在重启Dnsmasq程序导致无法使用 (#103)
