### ISSUE TITLE
配置生成的时候被截断问题

### ISSUE THREAD

**Issue by fs20sc** [frainzy1477/luci-app-clash#104]
Openwrt，LuCI Master (git-19.338.43082-9e87e69) / OpenWrt R9.12.03
clash-linux-mipsle-softfloat-v0.17.0
luci-app-clash_1.3.9-2_all
luci-app-clash_1.3.9-1_all
均有尝试。
具体
订阅神机规则
https://raw.githubusercontent.com/lhie1/Rules/master/Clash/Rule.yml
修改dns部分为redir-host模式，自行录入代理
依据订阅的配置
生成自定义配置的时候，规则文件会在第329行被截断。（自己的代理占3行）
最终文本大小只有9.97KB(10210B)
查了下原因，截断处刚好与“**创建配置**” TAB 底部的“规则”段 载入配置的文本框截断处相同。
应该是订阅的配置文本较大，文本框长度限制导致的。
而同文件，在“**配置**”TAB的 “**自定义配置**”中是正常的，只是只要使用，在 **使用中的配置**，就被截断了……

**Comment by frainzy1477** [comment]
x86没有这问题，可能你的路由器生成自定义配置有点慢

**Comment by fs20sc** [comment]
CPU还好吧，MT7621A，路由上几乎没啥东西跑。
刚再次查了，其实跟生成无关，“**创建配置**” TAB，读取配置之后就是这样子了
![SharedScreenshot](https://user-images.githubusercontent.com/22271348/71558946-759cf080-2a93-11ea-8905-dfa328ac8ceb.jpg)
生成配置，是依据这个文本框里面的内容生成的
所以被截断了

**Comment by frainzy1477** [comment]
好的我明天再试试

**Comment by wangxin6** [comment]
实际使用中，如果节点包含字符比如”]“，会被截断。

比如我的节点名称为“[v2ray]通道1”，生成配置会变成“[v2ray"

**Comment by frainzy1477** [comment]
> 实际使用中，如果节点包含字符比如”]“，会被截断。
> 
> 比如我的节点名称为“[v2ray]通道1”，生成配置会变成“[v2ray"

是的, 你应该节点名称不要添加 [ ]， 只读节点会有这问题。

**Comment by frainzy1477** [comment]
> 实际使用中，如果节点包含字符比如”]“，会被截断。
> 
> 比如我的节点名称为“[v2ray]通道1”，生成配置会变成“[v2ray"

他的问题是规则不是节点问题

**Comment by fs20sc** [comment]
补充一下，读取进来的时候被截断了规则
我手工从文本拷贝粘贴补全规则。
点保存并应用，生成的配置也被截断了。

再次测试，担心是客户端问题，
Chrome 79.0.3945.88（正式版本） （64 位）禁用了插件，一样被截断
Microsoft Edge 44.18362.449.0 with Microsoft EdgeHTML 18.18363，一样被截断
最后换成，WIN10自带的IE
神奇的地方出现了，**### IE 是 OK的**……
囧，还真是浏览器的问题……
