### ISSUE TITLE
启动后停在设置端口密码不动

### ISSUE THREAD

**Issue by denel23** [frainzy1477/luci-app-clash#105]
发现几个问题:启动后停在设置端口密码，未显示外部控制，使用上传配置发现还是使用自定义配置。
配置写external-controller: 127.0.0.1:9090在自定义配置0.0.0.0:9090

**Comment by denel23** [comment]
请看下面config内容哪儿有问题？
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
bind-address: "*"
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
secret: "123456"
external-ui: "/usr/share/clash/dashboard"
     
experimental:
  ignore-resolve-fail: true

#authentication:
# - "user1:pass1"

# hosts:
#   '*.clash.dev': 127.0.0.1
#   'alpha.clash.dev': '::1'
 
dns:
 enable: true
 listen: 0.0.0.0:5300
 enhanced-mode: fake-ip
 fake-ip-range: 198.18.0.0/16
 nameserver: 
  - 119.29.29.29 
  - 114.114.114.114    
  - tls://dns.rubyfish.cn:853
  - https://dns.google/dns-query
  - https://1.1.1.1/dns-query
fallback:
  - tls://dns.rubyfish.cn:853
  - tcp://1.1.1.1
  - tcp://8.8.8.8
fallback-filter:
  geoip: true
  ipcidr:
    - 240.0.0.0/4

**Comment by frainzy1477** [comment]
> 发现几个问题:启动后停在设置端口密码，未显示外部控制，使用上传配置发现还是使用自定义配置。
> 配置写external-controller: 127.0.0.1:9090在自定义配置0.0.0.0:9090

没有问题啊，你的意思不懂

**Comment by denel23** [comment]
开启clash内外网无法上网，客户端，外部控制都显示未运行另外fake-ip显示。

![1577765416941](https://user-images.githubusercontent.com/31842977/71609844-b184a280-2bc6-11ea-9fa9-b2d100b899b0.jpg)

**Comment by frainzy1477** [comment]
I cannot help you if you do not provide logs for clash.    located  in /tmp/clash.log

**Comment by denel23** [comment]
61行空一行
![1577768925326](https://user-images.githubusercontent.com/31842977/71610763-b0577380-2bce-11ea-8c63-831794d3e2e4.jpg)

**Comment by denel23** [comment]
![1577768925326](https://user-images.githubusercontent.com/31842977/71610774-cd8c4200-2bce-11ea-9898-8b817010fdee.jpg)

**Comment by wangxin6** [comment]
https://github.com/Fndroid/clash-config-builder

在线calsh配置

**Comment by denel23** [comment]
终于可以用了，谢谢
![image](https://user-images.githubusercontent.com/31842977/71616703-96c82300-2bf2-11ea-894e-d4f5e9fc2bf2.png)
