### ISSUE TITLE
GEOIP 下载更新

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#106]
maxmind.com不再提供自由下载：

[Significant Changes to Accessing and Using GeoLite2 Databases](https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/)

以及：
https://github.com/Dreamacro/maxmind-geoip

**Comment by m4niacjp** [comment]
Yep, seems to be an issue.
