### ISSUE TITLE
文件执行路劲

### ISSUE THREAD

**Issue by fuqiang03** [frainzy1477/luci-app-clash#107]
这两个地方是两个执行文件的路劲吧 脚本别的地方没有在定义了吧
![QQ截图20191231203202](https://user-images.githubusercontent.com/26851715/71621868-e3b8f300-2c0c-11ea-8812-5117dcecc148.png)

**Comment by frainzy1477** [comment]
> 这两个地方是两个执行文件的路劲吧 脚本别的地方没有在定义了吧

你想问什么？

**Comment by frainzy1477** [comment]
没有什么问题

**Comment by fuqiang03** [comment]
自己想改下路劲而已,

**Comment by frainzy1477** [comment]
> @frainzy1477
> 自己想改下路劲而已,
> config.yaml 是自动生成的吗
> ![QQ截图20191231205321](https://user-images.githubusercontent.com/26851715/71622307-c5a0c200-2c0f-11ea-9783-4315f6d60367.png)
> ![QQ截图20191231205346](https://user-images.githubusercontent.com/26851715/71622309-c9344900-2c0f-11ea-93f3-101da4de5d3c.png)

1. 你可以改
2 .不是
