### ISSUE TITLE
配置文件生成错误(Proxy节点段）

### ISSUE THREAD

**Issue by fs20sc** [frainzy1477/luci-app-clash#109]
luci-app-clash 1.4.1
创建配置
添加代理正常
最终点击创建配置按钮生产配置文件
生成的Proxy节点代码应为
- { name: "server1", type: http, server: myserver.com, port: 10001, username: user, password: userpass,false,tls: true }
但实际生成的文本，userpass和false中间那个逗号消失了。导致配置文件出错，手工在/usr/share/clash/config/custom下修改添加之后OK

**Comment by frainzy1477** [comment]
修了
https://github.com/frainzy1477/luci-app-clash/commit/7a2d8ece43e2752753be56ef34cdf9e5369737ce

https://github.com/frainzy1477/luci-app-clash/commit/952f7ae711339e3346dfce13a96b0a7d7c8055f0
