### ISSUE TITLE
  dns:  enable: true 启用后hosts就不生效

### ISSUE THREAD

**Issue by ztechie** [frainzy1477/luci-app-clash#111]

**Comment by ztechie** [comment]
看了下官方issues ,    dns:  enable: true 启用后hosts就不生效，那么DNS该怎么设置呢，谢谢

**Comment by frainzy1477** [comment]
> 看了下官方issues , dns: enable: true 启用后hosts就不生效，那么DNS该怎么设置呢，谢谢
看过vernesong和D大在组回答你

**Comment by frainzy1477** [comment]
> > 看了下官方issues , dns: enable: true 启用后hosts就不生效，那么DNS该怎么设置呢，谢谢
> > 看过vernesong和D大在组回答你了

**Comment by frainzy1477** [comment]
> > 看了下官方issues , dns: enable: true 启用后hosts就不生效，那么DNS该怎么设置呢，谢谢
> > 看过vernesong和D大在组回答你了
