### ISSUE TITLE
打开国内网站特别慢 （就是会加载一下转一会，但是打开国外的网站就没这个状况）

### ISSUE THREAD

**Issue by shaoyou11** [frainzy1477/luci-app-clash#112]
使用默认的dns设置 打开国内网站特别慢 （就是会加载一下转一会，但是打开国外的网站就没这个状况），而且我改不成上传配置dns设置。我改了这种规则 发现都是慢的  所以应该跟规则没关系了

**Comment by frainzy1477** [comment]
> 使用默认的dns设置 打开国内网站特别慢 （就是会加载一下转一会，但是打开国外的网站就没这个状况），而且我改不成上传配置dns设置。我改了这种规则 发现都是慢的 所以应该跟规则没关系了

那你自己改dns设置吧

![image](https://user-images.githubusercontent.com/49537471/71889906-25eab300-317e-11ea-9197-8d5be0f227b7.png)
