### ISSUE TITLE
在openwrt18.6.5 x64安装成功，但是内核用clashr不正常！

### ISSUE THREAD

**Issue by jackwonglstc** [frainzy1477/luci-app-clash#113]
使用clash内核一切正常，使用感觉不错！
但是使用clashr内核的时候，客户端运行到重启dnsmasq ,然后就不动了，始终无法启动客户端成功！
不知道是什么原因？clashr内核好像是支持SSR。
不知道其他人是否也有这个情况？

**Comment by frainzy1477** [comment]
clashr内核没问题
