### ISSUE TITLE
1.4.2无法安装

### ISSUE THREAD

**Issue by aaaisan** [frainzy1477/luci-app-clash#114]
内核版本4.19.88无法安装……

**Comment by frainzy1477** [comment]
> 内核版本4.19.88无法安装……

你说无法安装我怎么帮你安装？？我也不知道你有什么问题。  don't open an issue without providing any log or screenshot of issue。

**Comment by aaaisan** [comment]
就是因为内核版本不对啊
Upgrading luci-app-clash on root from 1.4.1 to 1.4.2...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-clash:
 *      kernel (= 4.19.93-1-be6b24a36b944ebcfb692eabf6c74fec) * 
 * opkg_install_cmd: Cannot install package luci-app-clash.

**Comment by aaaisan** [comment]
`Upgrading luci-app-clash on root from 1.4.1 to 1.4.2...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-clash:
 *      kernel (= 4.19.93-1-be6b24a36b944ebcfb692eabf6c74fec) * 
 * opkg_install_cmd: Cannot install package luci-app-clash.`
