### ISSUE TITLE
OK，我重新提交，1.4.2无法安装

### ISSUE THREAD

**Issue by aaaisan** [frainzy1477/luci-app-clash#115]
```
root@OpenWrt:/tmp/upload# opkg install luci-app-clash_1.4.2_all.ipk
Upgrading luci-app-clash on root from 1.4.1 to 1.4.2...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-clash:
 *      kernel (= 4.19.93-1-be6b24a36b944ebcfb692eabf6c74fec) * 
 * opkg_install_cmd: Cannot install package luci-app-clash.
```
我的内核版本是4.19.88

**Comment by frainzy1477** [comment]
> ```
> root@OpenWrt:/tmp/upload# opkg install luci-app-clash_1.4.2_all.ipk
> Upgrading luci-app-clash on root from 1.4.1 to 1.4.2...
> Collected errors:
>  * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-clash:
>  *      kernel (= 4.19.93-1-be6b24a36b944ebcfb692eabf6c74fec) * 
>  * opkg_install_cmd: Cannot install package luci-app-clash.
> ```
> 
> 我的内核版本是4.19.88

先 opkg update

**Comment by aaaisan** [comment]
就是说我要先编译固件？……

**Comment by ztechie** [comment]
ssh链接路由器，先执行opkg update在执行你的安装命令

**Comment by frainzy1477** [comment]
kmod-tun
https://downloads.openwrt.org/releases/18.06.2/targets/x86/64/kmods/4.14.95-1-83ad3e3d0a55dcd3f120c5ac4bdc92ba/kmod-tun_4.14.95-1_x86_64.ipk

kernel
https://downloads.openwrt.org/releases/18.06.2/targets/x86/64/packages/kernel_4.14.95-1-83ad3e3d0a55dcd3f120c5ac4bdc92ba_x86_64.ipk




> 每次安装ipk前都opkg update
> 就是说我要先编译固件？……
动下载 安装
https://downloads.openwrt.org/releases/18.06.2/targets/

**Comment by frainzy1477** [comment]
> 每次安装ipk前都opkg update
> 就是说我要先编译固件？……

动下载 安装
https://downloads.openwrt.org/releases/18.06.2/targets/
