### ISSUE TITLE
GeoIP相关问题

### ISSUE THREAD

**Issue by PianCat** [frainzy1477/luci-app-clash#116]
在上传geoip的country.mmdb文件后出现client无法启动的现象，且在启动client后无法正常链接网络

log error行:
time="2020-01-08T03:23:08Z" level=fatal msg="Can't load mmdb: error opening database: invalid MaxMind DB file"

**Comment by frainzy1477** [comment]
> 在上传geoip的country.mmdb文件后出现client无法启动的现象，且在启动client后无法正常链接网络
> 
> log error行:
> time="2020-01-08T03:23:08Z" level=fatal msg="Can't load mmdb: error opening database: invalid MaxMind DB file"

这是我的问题吗？你上传无效的country.mmdb，

下载地址
https://geolite.clash.dev/Country.mmdb

https://github.com/Dreamacro/maxmind-geoip/releases/download/20191231/Country.mmdb

**Comment by PianCat** [comment]
我就是从这两个地方下载下来的Country.mmdb，是不是我的上传方式有问题还是怎么的？

**Comment by PianCat** [comment]
可以通过丢到/tmp里面再手动导入吗？

**Comment by frainzy1477** [comment]
首先检查你是否有足够的空间
可能是因为设备空间不足而缩短了文件大小

**Comment by PianCat** [comment]
那应该是空间不够的问题了，geoIP不更新也应该没问题的吧
