### ISSUE TITLE
昨天的1.42版本openwrt编译出错    恢复1.41正常

### ISSUE THREAD

**Issue by leishao1993** [frainzy1477/luci-app-clash#117]
昨天的1.42版本openwrt编译出错    恢复1.41正常

**Comment by frainzy1477** [comment]
> 昨天的1.42版本openwrt编译出错 恢复1.41正常

你开这个issue谁知道编哪里出错？开一个issue要发日志

**Comment by lifetyper** [comment]
其实最近几个版本我都没编译过，借楼贴一下日志:

cp -fpR /home/lifetyper/ledex/build_dir/target-x86_64_musl/root-x86 /home/lifetyper/ledex/build_dir/target-x86_64_musl/root.orig-x86
/home/lifetyper/ledex/build_dir/target-x86_64_musl/root-x86/etc/init.d/arpbind: line 5: /lib/functions.sh: No such file or directory
/home/lifetyper/ledex/build_dir/target-x86_64_musl/root-x86/etc/init.d/arpbind: line 6: /lib/functions/network.sh: No such file or directory
/home/lifetyper/ledex/build_dir/target-x86_64_musl/root-x86/etc/init.d/clash: line 291: syntax error in conditional expression
/home/lifetyper/ledex/build_dir/target-x86_64_musl/root-x86/etc/init.d/clash: line 291: syntax error near `]'
/home/lifetyper/ledex/build_dir/target-x86_64_musl/root-x86/etc/init.d/clash: line 291: `elif [[  -f $CONFIG_YAML_SUB ] && [ "$(ls -l $CONFIG_YAML_SUB | awk '{print int($5)}')" -eq 0 ] && [ ! -z "${subscribe_url_clash}" ]]  && [[ -f $CONFIG_YAML_OLD ] && [ "$(ls -l $CONFIG_YAML_OLD | awk '{print int($5/1024)}')" -eq 0 ]];then'
postinst script ./usr/lib/opkg/info/luci-app-clash.postinst has failed with exit code 1
package/Makefile:65: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 1

**Comment by frainzy1477** [comment]
> 其实最近几个版本我都没编译过，借楼贴一下日志:
> `cp -fpR /home/lifetyper/ledex/build_dir/target-x86_64_musl/root-x86 /home/lifetyper/ledex/build_dir/target-x86_64_musl/root.orig-x86 /home/lifetyper/ledex/build_dir/target-x86_64_musl/root-x86/etc/init.d/arpbind: line 5: /lib/functions.sh: No such file or directory /home/lifetyper/ledex/build_dir/target-x86_64_musl/root-x86/etc/init.d/arpbind: line 6: /lib/functions/network.sh: No such file or directory /home/lifetyper/ledex/build_dir/target-x86_64_musl/root-x86/etc/init.d/clash: line 291: syntax error in conditional expression /home/lifetyper/ledex/build_dir/target-x86_64_musl/root-x86/etc/init.d/clash: line 291: syntax error near`]'
> /home/lifetyper/ledex/build_dir/target-x86_64_musl/root-x86/etc/init.d/clash: line 291: `elif [[ -f $CONFIG_YAML_SUB ] && [ "$(ls -l $CONFIG_YAML_SUB | awk '{print int($5)}')" -eq 0 ] && [ ! -z "${subscribe_url_clash}" ]] && [[ -f $CONFIG_YAML_OLD ] && [ "$(ls -l $CONFIG_YAML_OLD | awk '{print int($5/1024)}')" -eq 0 ]];then' postinst script ./usr/lib/opkg/info/luci-app-clash.postinst has failed with exit code 1 package/Makefile:65: recipe for target 'package/install' failed make[2]: *** [package/install] Error 1 `

https://github.com/frainzy1477/luci-app-clash/commit/b40db5ce26279380154e4558029e04f4efed69f3  先试试

**Comment by frainzy1477** [comment]
> 昨天的1.42版本openwrt编译出错 恢复1.41正常

https://github.com/frainzy1477/luci-app-clash/commit/b40db5ce26279380154e4558029e04f4efed69f3
