### ISSUE TITLE
卸载luci-app-clash提示ip6tables: not found

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#121]
卸载luci-app-clash有如下提示：
`Removing package luci-app-clash from root...`
`/etc/rc.common: line 619: ip6tables: not found`
`uci: Entry not found`

**Comment by frainzy1477** [comment]
哦知道了，修了

**Comment by shensven** [comment]
@wangxin6 请问你怎么卸载的？我`opkg remove luci-app-clash`后提示`No packages removed.`，`opkg list-installed`后也没有这个包

**Comment by wangxin6** [comment]
system-software 然后找到 luci-app-clash 点选remove。然后 terminal 到路由器。
rm -f -r /etc/config/clash
rm -f -r /etc/clash
rm -f -r /usr/share/clash
