### ISSUE TITLE
配置求助...

### ISSUE THREAD

**Issue by crackerfly** [frainzy1477/luci-app-clash#122]
Hi....  各位大佬。
我已在openwrt(18.06.5 armv7) 成功安装:
- luci-app-clash(v1.4.2)
- clash内核(clash-linux-armv7-v0.17.1.gz)

在配置使用时遇到两个问题：

- 使用UI自带的配置工具导入 clashx 正在使用的配置文件，无法启动（ 首页状态停留在 Restarting Dnsmapq）
  - 配置文件模版来自：https://github.com/ConnersHua/Profiles/blob/master/Clash/Pro.yaml
- 使用UI手动创建配置，点击创建后 首页状态停留在 开始创建配置文件，之后一直卡在这里

-----
大佬能否提供一份标准可手动编辑下服务器信息即可使用的配置文件模版，万分感谢...

**Comment by frainzy1477** [comment]
1. Do not open an issue without providing error log, really annoying.
2. Does your proxy group names all  match with rule?
