### ISSUE TITLE
有个小问题

### ISSUE THREAD

**Issue by fuqiang03** [frainzy1477/luci-app-clash#123]
就是在重启(关机)后页面在5s后会(而不是等待一段时间后再返回登入页面),直接跳到主页上,但是删除clash脚本就不会出现这个问题(个人怀疑再关机的时候系统执行了stop部分导致的),作者遇到过同样的问题吗,包括系统主题也是如此.(因为是关机或者重启的时候发生的,很难找的一些线索)
我用的是op 主库的代码(包括luci)

**Comment by frainzy1477** [comment]
没有啊，可能是你的固件问题

**Comment by fuqiang03** [comment]
@frainzy1477 
关于这个问题,我正在重新的验证
我最小化安装后问题依旧,删除init下面的clash 重启页面就正常 我正在自己查找原因
已排除主题问题.
希望有同样的情况可以分享些经验,
![QQ截图20200118140715](https://user-images.githubusercontent.com/26851715/72659552-41668100-39fc-11ea-89cc-b3e01578d7ae.png)
注释掉下列语句,重启页面正常
#		remove_mark >/dev/null 2>&1
#		revert_dns >/dev/null 2>&1
#		if [ "${lang}" == "en" ] || [ $lang == "auto" ];then
#			echo "  $(date "+%Y-%m-%d %H:%M:%S") - CLIENT IS DISABLED " >> /tmp/clash.txt
#			echo "Client is Disabled " >$REAL_LOG
#			sleep 2
#			echo "Clash for OpenWRT" >$REAL_LOG
#		elif [ "${lang}" == "zh_cn" ];then
#			echo "  $(date "+%Y-%m-%d %H:%M:%S")  - 客户端被禁用 " >> /tmp/clash.txt
#			echo "客户端被禁用 " >$REAL_LOG
#			sleep 2
#			echo "Clash for OpenWRT" >$REAL_LOG
#		fi
---已经关机了 还有写入日志文件?

**Comment by wangxin6** [comment]
System - Reboot - Perform reboot 点击以后，会出现提示 “device is rebooting..."，然后返回 Status - overview 页面。而不是openwrt 用户名/密码登陆页面。

Firmware Version | OpenWrt R9.8.17 / LuCI Master (git-19.146.62144-fd6fdb2)
