### ISSUE TITLE
V1.4.5 tun模式无法使用 Custome DNS

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#126]
在 client - core 设置为 ClashTun，

在 settings - DNS settings - Tun Mode DNS 设置为 Disabled，勾选 Custom DNS，并在 Modify yaml DNS 输入自定义DNS。点击 Save&Apply。

Log有如下提示：
`"Parse config error: Configuration file /etc/clash/config.yaml is empty"`

返回settings - DNS settings，发现未勾选 Custom DNS，并且无Modify yaml DNS 可以输入。

**Comment by frainzy1477** [comment]
Clash Tun的 coe,  Tun Dns 就能选择用
