### ISSUE TITLE
系统日志一直在打错误，25的版本

### ISSUE THREAD

**Issue by zcluo** [frainzy1477/luci-app-clash#13]
Mon Jul  8 09:39:41 2019 daemon.err uhttpd[3325]: Model clash/log returns SimpleForm but is dispatched via cbi(),
Mon Jul  8 09:39:41 2019 daemon.err uhttpd[3325]: please change admin/services/clash/log to use the form() action instead.

**Comment by zcluo** [comment]
24的版本会有这种情况，刚开始导入config.yaml的时候启动起来是正常的功能也是正常，但是用1天左右客户端就down了，config.yaml也变成0字节

**Comment by wangxin6** [comment]
> 24的版本会有这种情况，刚开始导入config.yaml的时候启动起来是正常的功能也是正常，但是用1天左右客户端就down了，config.yaml也变成0字节

缺省情况下，是定时更新机场订阅。如果没有设置机场订阅地址，就会造成你所说的情况。需要将定时更新取消。或者作者修改源码：缺省情况下，不定时更新机场订阅。

**Comment by zcluo** [comment]
总体还是挺好用的，谢谢，如果能让路由器本身也能翻出去就好了！
