### ISSUE TITLE
clash tun怎么安装

### ISSUE THREAD

**Issue by mmeiwenlong** [frainzy1477/luci-app-clash#130]
是下载两个么？我下载两个上传至你说的目录下，赋予权限时输完命令提示没发现，是不是我步骤搞错了？下载ipk输完opkg install luci-app-clash_1.4.6_all.ipk ( original openwrt / lean openwrt / koolshare openwrt )等他装完接着又输
opkg install kmod-tun ( To use Tuntap kmod-tun must be install first )

那这个kmod-tun也得提前下载好然后通过openwrt本身上传上去再执行安装吧？

**Comment by frainzy1477** [comment]
opkg update
opkg install kmod-tun
你也可以从https://downloads.openwrt.org/snapshots/targets/ 下载好然后安装, 有时候需要升级openwrt kernel

**Comment by mmeiwenlong** [comment]
> opkg update 
> opkg install kmod-tun 
> 你也可以从https://downloads.openwrt.org/snapshots/targets/下载好然后安装，有时候需要升级openwrt内核


就是执行这两条命令就可以安装了？难怪我只下载一个tun文件至目录，然后给矛权限命令提示没发现，再一看命令后面还有个/clash而我的那里面没有！至此就晕了，呵呵

**Comment by mmeiwenlong** [comment]
> opkg update
> opkg install kmod-tun
> 你也可以从https://downloads.openwrt.org/snapshots/targets/下载好然后安装，有时候需要升级openwrt内核
![QQ截图20200116194240](https://user-images.githubusercontent.com/44661424/72522352-735ed280-3898-11ea-8612-cf1d24501d11.png)
安装失败

**Comment by frainzy1477** [comment]
你先升级kernel 到4.19.93-1-********

**Comment by mmeiwenlong** [comment]
> 您先升级kernel到4.19.93-1-********
> 下载安装
> https://downloads.openwrt.org/snapshots/targets/x86/64/packages/kernel_4.19.93-1-38cbd52649ab584264f35e676da58679_x86_64.ipk

![QQ截图20200116195427](https://user-images.githubusercontent.com/44661424/72523124-18c67600-389a-11ea-82ee-e125ee2d4bf7.png)
这样就是装好了吧。
那个clash tun
![QQ截图20200116195609](https://user-images.githubusercontent.com/44661424/72523226-51664f80-389a-11ea-90e1-dcef51349d47.png)
两个只需要一个吧就行了呗

**Comment by frainzy1477** [comment]
你自己下载clash 支持Tun内核 试试 link 2

**Comment by mmeiwenlong** [comment]
> 你自己下载clash支持Tun内核试试link 2
> 
> ![图片](https://user-images.githubusercontent.com/49537471/72523609-22041280-389b-11ea-9c38-99f704e57a4c.png)

就是这样子的提示没发现
![QQ截图20200116201000](https://user-images.githubusercontent.com/44661424/72524276-7cea3980-389c-11ea-8944-78823c0172e3.png)
![QQ截图20200116201054](https://user-images.githubusercontent.com/44661424/72524300-8d021900-389c-11ea-8a26-cdb78d97b470.png)

**Comment by frainzy1477** [comment]
![image](https://user-images.githubusercontent.com/49537471/72524344-ac00ab00-389c-11ea-9868-bdcc4ed89cab.png)

重命名 clash 不是clash-linux-amd64

**Comment by mmeiwenlong** [comment]
> ![图片](https://user-images.githubusercontent.com/49537471/72524344-ac00ab00-389c-11ea-9868-bdcc4ed89cab.png)
> 
> 重命名clash不是clash-linux-amd64
> 
> 你没看我发的截图???

![QQ截图20200116201832](https://user-images.githubusercontent.com/44661424/72524813-ae173980-389d-11ea-8074-3ae883f96e5b.png)
![QQ截图20200116202028](https://user-images.githubusercontent.com/44661424/72524818-b0799380-389d-11ea-8f0e-e7e6df651b3f.png)
终于好了。谢谢你的帮助。

**Comment by Comah** [comment]
我的是路由器新三 openwrt 是否也能按照这样来安装呢 谢谢  原来的是1.22 16.0 太老旧了用不了
