### ISSUE TITLE
V1.4.8 Modify Tun DNS save

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#131]
V1.4.8 Modify Tun DNS save & apply 以前需要在第一行保留空行，否则会出现 experimental: 在 config in use的第一行

**Comment by frainzy1477** [comment]
没有啊，和以前一样

**Comment by wangxin6** [comment]
需要先修改。比如删除两个 dns server 然后点 Save & Apply。这时 config - config in use 就会出现：
`experimental:`
`port: 7890`
`socks-port: 7891`
`redir-port: 7892`
`...`

**Comment by frainzy1477** [comment]
我也试试多次没出现那个问题

**Comment by wangxin6** [comment]
DNS Settings 页面做任何修正，然后再点  Save & Apply，都会复现这个问题。
