### ISSUE TITLE
自定义配置文件问题导致启动时卡“重启Dnsmasq”

### ISSUE THREAD

**Issue by Scorpion4286** [frainzy1477/luci-app-clash#133]
平台：
OpenWrt 19.07.0 官方源编译

版本：
v1.4.8（在v1.4.7也有遇到，之前用的是v1.3.5，没有问题）

现象：
启动时卡“重启Dnsmasq”，日志如下
![Snipaste_2020-01-20_13-15-06](https://user-images.githubusercontent.com/54585136/72700782-e2ce0e00-3b87-11ea-9ef9-8b42fc56302c.png)

原因：
在“配置->使用中的配置”中存在格式问题
![Snipaste_2020-01-20_13-14-29](https://user-images.githubusercontent.com/54585136/72700740-c336e580-3b87-11ea-9b05-cfa144ee7183.png)
但在“配置->自定义配置”中则没有问题
![Snipaste_2020-01-20_13-14-17](https://user-images.githubusercontent.com/54585136/72700766-d8137900-3b87-11ea-95f9-b0bacf8553af.png)

操作：
在生成自定义配置后，只是在客户端页面进行了启动操作。
![Snipaste_2020-01-20_13-23-11](https://user-images.githubusercontent.com/54585136/72700847-23c62280-3b88-11ea-8eaa-02c5c524633b.png)

**Comment by wangxin6** [comment]
同 #131
临时解决方案：
在customer dns 里面添加一空行在experimental:上面，然后点保存和应用

**Comment by frainzy1477** [comment]
修了
