### ISSUE TITLE
Bypass LAN-IP

### ISSUE THREAD

**Issue by m4niacjp** [frainzy1477/luci-app-clash#136]
Since last update v1.4.8 i can't seem to find option to bypass LAN IP in order to let a device not use proxy.

**Comment by frainzy1477** [comment]
> Since last update v1.4.8 i can't seem to find option to bypass LAN IP in order to let a device not use proxy.

Option have been removed, you can add source ip directly in config file and sent to DIRECT

**Comment by wangxin6** [comment]
- SRC-IP-CIDR,192.168.1.123/32,DIRECT

**Comment by m4niacjp** [comment]
What about if the config it's a subscribe link from a third party provider? Is it possible to add it somehow on top of it?

**Comment by frainzy1477** [comment]
> What about if the config it's a subscribe link from a third party provider? Is it possible to add it somehow on top of it?

luci-app-clash v1.4.8 can edit subscribe config and SAVE&APPLY changes

**Comment by m4niacjp** [comment]
Thanks! You can close.
