### ISSUE TITLE
这个在线下载出这提示。

### ISSUE THREAD

**Issue by mmeiwenlong** [frainzy1477/luci-app-clash#137]
缺少下东西。怎样装好这些缺失的？谷歌了下都装不成功。好像说里面有一个了就不能安装这个？
![QQ截图20200123183501](https://user-images.githubusercontent.com/44661424/72977443-89781000-3e0f-11ea-9320-b954bdd34416.png)
![QQ截图20200123185245](https://user-images.githubusercontent.com/44661424/72978597-b62d2700-3e11-11ea-9fb0-e7d03b4bd507.png)

**Comment by crackerfly** [comment]
opkg update

**Comment by mmeiwenlong** [comment]
> opkg更新

OPKG更新经常出错。无语

**Comment by frainzy1477** [comment]
> > opkg更新
> 
> OPKG更新经常出错。无语

安装luci-app-clash时候添加 --force-depends

**Comment by Mosney** [comment]
错误提示不是告诉你wget缺少ssl依赖了么 装上提示的两个依赖就ok了

**Comment by Mosney** [comment]
可以尝试先把之前的老版本的`libubox`卸载然后接着安装`libustream`
另外没有金刚钻就不要用snapshot版本了
