### ISSUE TITLE
openwrt18.06.4取消启动按钮后，点保存，无法停止，系统进程如下

### ISSUE THREAD

**Issue by ztechie** [frainzy1477/luci-app-clash#14]
14078 root      1192 S    /bin/sh /etc/rc.common /etc/init.d/clash restart
14082 root      1056 S    flock 1000
14373 root      1192 S    /bin/sh /etc/rc.common /etc/init.d/clash restart
14377 root      1056 S    flock 1000
14805 root      1192 S    /bin/sh /etc/rc.common /etc/init.d/clash restart
14809 root      1056 S    flock 1000
14813 root      1192 S    /bin/sh /etc/rc.common /etc/init.d/clash restart

**Comment by ztechie** [comment]
要kill掉这些clash的进程后才能点重启按钮，这些进程不结束，不管是ssh reboot和luci的重启都无效

**Comment by frainzy1477** [comment]
> 要kill掉这些clash的进程后才能点重启按钮，这些进程不结束，不管是ssh reboot和luci的重启都无效
you must set clash client to disable else it will restart again since there is a background process check (clash-watchdog), if clash is enabled and system detect clash has stopped, it will automatically restart clash client.
