### ISSUE TITLE
missing luci module in the latest OpenWRT build 

### ISSUE THREAD

**Issue by scbizu** [frainzy1477/luci-app-clash#140]
* luci-app-clash version: v1.4.8
* clash version: v0.17.2
* CPU arch: mipsle 24kc
* Kernel Version: 4.14.162
* Route Type: XiaoMi Wifi mini 
* OpenWRT verson: 19.07
* Details:「Create Config」-> 「Proxies」, 当点击Add或者Edit的时候会直接报错，信息如下：
```log
Failed to execute cbi dispatcher target for entry '/admin/services/clash/provider-config/cfg074a8f'.
The called action terminated with an exception:
...usr/lib/lua/luci/model/cbi/clash/provider-config.lua:5: module 'luci.model.ipkg' not found:
	no field package.preload['luci.model.ipkg']
	no file './luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg/init.lua'
	no file '/usr/lib/lua/luci/model/ipkg.lua'
	no file '/usr/lib/lua/luci/model/ipkg/init.lua'
	no file './luci/model/ipkg.so'
	no file '/usr/lib/lua/luci/model/ipkg.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	...usr/lib/lua/luci/model/cbi/clash/provider-config.lua:5: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:943: in function </usr/lib/lua/luci/dispatcher.lua:937>
```

**Comment by frainzy1477** [comment]
> * luci-app-clash version: v1.4.8
> * clash version: v0.17.2
> * CPU arch: mipsle 24kc
> * Kernel Version: 4.14.162
> * Route Type: XiaoMi Wifi mini
> * OpenWRT verson: 19.07
> * Details:「Create Config」-> 「Proxies」, 当点击Add或者Edit的时候会直接报错，信息如下：
> 
> ```
> Failed to execute cbi dispatcher target for entry '/admin/services/clash/provider-config/cfg074a8f'.
> The called action terminated with an exception:
> ...usr/lib/lua/luci/model/cbi/clash/provider-config.lua:5: module 'luci.model.ipkg' not found:
> 	no field package.preload['luci.model.ipkg']
> 	no file './luci/model/ipkg.lua'
> 	no file '/usr/share/lua/luci/model/ipkg.lua'
> 	no file '/usr/share/lua/luci/model/ipkg/init.lua'
> 	no file '/usr/lib/lua/luci/model/ipkg.lua'
> 	no file '/usr/lib/lua/luci/model/ipkg/init.lua'
> 	no file './luci/model/ipkg.so'
> 	no file '/usr/lib/lua/luci/model/ipkg.so'
> 	no file '/usr/lib/lua/loadall.so'
> 	no file './luci.so'
> 	no file '/usr/lib/lua/luci.so'
> 	no file '/usr/lib/lua/loadall.so'
> stack traceback:
> 	[C]: in function 'require'
> 	...usr/lib/lua/luci/model/cbi/clash/provider-config.lua:5: in function 'func'
> 	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
> 	/usr/lib/lua/luci/dispatcher.lua:943: in function </usr/lib/lua/luci/dispatcher.lua:937>
> ```

https://github.com/frainzy1477/luci-app-clash/commit/3531deabc0aed823cbd48de63d326b2f059e5062 自己修改试试

**Comment by scbizu** [comment]
有release发吗？本地没有 OpenWRT build tools

**Comment by scbizu** [comment]
ok  可以了
