### ISSUE TITLE
增加服务器选择的选项

### ISSUE THREAD

**Issue by softicer** [frainzy1477/luci-app-clash#141]
很好用，非常感谢。当配置文件中多个服务器的时候能否增加一个选项，允许指定某一个服务器。谢谢。

**Comment by frainzy1477** [comment]
> 很好用，非常感谢。当配置文件中多个服务器的时候能否增加一个选项，允许指定某一个服务器。谢谢。

有啊，你说的不不清楚

![image](https://user-images.githubusercontent.com/49537471/73171198-1f2adc80-413b-11ea-9ddb-da48f3575e0a.png)

**Comment by softicer** [comment]
我是说一个配置中有多个服务器的时候。

**Comment by frainzy1477** [comment]
> 我是说一个配置中有多个服务器的时候。

![image](https://user-images.githubusercontent.com/49537471/73172166-5b5f3c80-413d-11ea-843b-a85e7fd9714d.png)
你的意思我还不懂

**Comment by softicer** [comment]
我看到的界面跟你这个不太一样呢，谢谢，可以加电报问你么，谢谢啊。

**Comment by softicer** [comment]
谢谢啊，知道怎么解决了，虽然不能手工选择，我自己上传一个配置文件，然后删除了多余的配置。

**Comment by frainzy1477** [comment]
> 我看到的界面跟你这个不太一样呢，谢谢，可以加电报问你么，谢谢啊。

怎么可能？? 你安装1.5.0？？

**Comment by frainzy1477** [comment]
> 谢谢啊，知道怎么解决了，虽然不能手工选择，我自己上传一个配置文件，然后删除了多余的配置。

你上传以后可以选配置然后在创建配置页读取、编辑和重新创建配置

**Comment by softicer** [comment]
我的意思是配置文件中有以下的多个服务器：
![TIM图片20200127200226](https://user-images.githubusercontent.com/12409478/73173310-0cff6d00-4140-11ea-955e-08b55c9fee3d.png)
最好可以界面能选择使用哪一个。
另外我的界面上显示主要的错误：
![TIM图片20200127200603](https://user-images.githubusercontent.com/12409478/73173533-87c88800-4140-11ea-8721-fba8793bff25.png)

**Comment by frainzy1477** [comment]
安装 https://github.com/frainzy1477/luci-app-clash/releases/download/v1.5.0/luci-theme-rosy_all.ipk  luci-theme-rosy

**Comment by softicer** [comment]
> 你的主题有问题
> 安装 https://github.com/frainzy1477/luci-app-clash/releases/download/v1.5.0/luci-theme-rosy_all.ipk luci-theme-rosy
安装报错：
Not downgrading package luci-theme-rosy on root from git-19.134.25985-50bb118-1 to git-19.127.46547-530d0c1-1.

**Comment by softicer** [comment]
谢谢啦。基本解决问题了，创建配置会出错。用上传配置就好了。谢谢。

**Comment by bengdan** [comment]
> 谢谢啦。基本解决问题了，创建配置会出错。用上传配置就好了。谢谢。

我今天就是，一改配置提交，整个网页都崩了，软路由还在跑，只能重启。必须得重新上传配置，删除某个配置也崩。
