### ISSUE TITLE
无法取消“自定义DNS”

### ISSUE THREAD

**Issue by Mosney** [frainzy1477/luci-app-clash#144]
上传了一份完整可用的配置文件，把所有额外功能都关闭，发现此处的覆写DNS配置无法取消，即使取消勾选，保存重启动之后也会恢复截图状态。
![image](https://user-images.githubusercontent.com/22477230/73220941-95126080-419a-11ea-877f-b7f783d5d2e0.png)

**Comment by frainzy1477** [comment]
you can delete all content in modify dns and save

**Comment by Mosney** [comment]
我已经尝试把“修改DNS”文本框中的**内容清空**`or`**保留一个空行**，同时**不勾**`or`**勾选**”自定义DNS“复选框。共计四种情况，点击保存并应用后，结果都是一样的：复选框重新勾选，文本框内容依旧替换掉配置文件中dns部分。
目测这个文本框跟这个issue https://github.com/frainzy1477/luci-app-clash/issues/143 里提到的不能置空是一套逻辑。

**Comment by Mosney** [comment]
@frainzy1477 这个bug还打算修么
