### ISSUE TITLE
wan口重新拨号之后需要手动重启clash客户端才能上网

### ISSUE THREAD

**Issue by laoz77** [frainzy1477/luci-app-clash#145]
clash版本1.5.0，clashr的版本是1.7.2
在wan口重新拨号（可能是电信强制断线重连）之后会出现无法上网的情况。必须手动重启clash客户端才能上网。

**Comment by m4niacjp** [comment]
Same situation as me. It happens at least every night, i wake up in the morning and need to restart clash in order to make it work.
