### ISSUE TITLE
创建配置里面的下载规则文件，点击下载后直接出错。

### ISSUE THREAD

**Issue by thank243** [frainzy1477/luci-app-clash#147]
![image](https://user-images.githubusercontent.com/11692994/73609060-e9876700-4604-11ea-9882-7c857dc5f439.png)

![image](https://user-images.githubusercontent.com/11692994/73609065-f015de80-4604-11ea-963b-f92753d0e3e9.png)
如图所示

**Comment by frainzy1477** [comment]
https://github.com/frainzy1477/luci-app-clash/commit/0d5857551208884c2fff60a838b73ef9c12f2a62

先自己修改
