### ISSUE TITLE
开启会卡在 "重启dnsmasq"程序

### ISSUE THREAD

**Issue by Android-AwesomeRoy** [frainzy1477/luci-app-clash#148]
运行环境: N1盒子旁路由, 内核版本: 4.18.7-aml-s9xxx
subconverter 订阅代理链接并生成 yaml 文件.
luci-app-clash : 1.5.1, 内核: 1.7.2

---

### 问题1
操作方式:yaml文件上传到配置并读取, 点击启用客户端, 便会卡在 "重启dnsmasq 程序" 的页面
![Snipaste_2020-02-04_01-02-54](https://user-images.githubusercontent.com/19187129/73673950-853ed300-46ea-11ea-89ec-d1347bdb54a0.png)

同时日志会读取到:
![image](https://user-images.githubusercontent.com/19187129/73674040-a8698280-46ea-11ea-9f76-3e425010b41f.png)

回去找配置中的 28 行,内容只是一行普通的vmess配置信息. 
桌面版与Android版客户端都可以正常识别yaml文件并使用.

### 问题2 
在比较早的一次操作中是正常启用的, 但是启用后无法登录国内的游戏(如风暴英雄), 原因未知. 应该怎么解决?

**Comment by frainzy1477** [comment]
卡在 "重启dnsmasq"程序 以后在 /etc/clash/config.yaml看看28 行

**Comment by Android-AwesomeRoy** [comment]
问题已解决, 重新上传了几次就好了.
