### ISSUE TITLE
修改外部端口需要重新启用

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#15]
修改外部端口后，点【保存和应用】维持原端口不变，需要取消【启动】再点【启动】才生效。修改日志级别点【保存和应用】立刻生效。

**Comment by wangxin6** [comment]
转发端口 ／ 外部控制端口 ／ 外部控制密钥 ／ 日志级别 是否都应该是点【保存和应用】立刻生效？

**Comment by frainzy1477** [comment]
> 修改外部端口后，点【保存和应用】维持原端口不变，需要取消【启动】再点【启动】才生效。修改日志级别点【保存和应用】立刻生效。

不可能， 那是你的OP的问题， 必须转发端口 ／ 外部控制端口 ／ 外部控制密钥 ／ 日志级别立刻生效
