### ISSUE TITLE
策略组无法正确设置provider

### ISSUE THREAD

**Issue by thank243** [frainzy1477/luci-app-clash#152]
使用provider后，还会默认添加个ss服务器。

**- name: PROXY
  type: select
  proxies:
    - "UrlTest"
  use:
    - "Senis"**

策略组中没有use参数。

**Comment by frainzy1477** [comment]
> 使用provider后，还会默认添加个ss服务器。
> 
> **- name: PROXY type: select proxies: - "UrlTest" use: - "Senis"**
> 
> 策略组中没有use参数。

知道了，没有PROXY会出现
