### ISSUE TITLE
能否取消Online Update GeoIP 后客户端自动重启

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#153]
Online Update GeoIP 后客户端自动重启，会回到缺省的节点，无法继续使用上次修改后的节点。

**Comment by frainzy1477** [comment]
> Online Update GeoIP 后客户端自动重启，会回到缺省的节点，无法继续使用上次修改后的节点。

当然了，你自己重启客户端以后不是一样吗？

**Comment by wangxin6** [comment]
我的意思是仅更新GeoIP不用重启客户端吧？
