### ISSUE TITLE
Status mismatch?

### ISSUE THREAD

**Issue by Kihara777** [frainzy1477/luci-app-clash#154]
The status always stuck at "Setting dns forwarder", but everything else works fine without any problem.

luci-app-clash version: v1.5.2
openwrt version: 19.07.1 r10911-c155900f66

**Comment by frainzy1477** [comment]
I cannot help you without providing log info, i have never experience such situation.

**Comment by Kihara777** [comment]
Well, tried logread | grep clash and her's what I got:

**Comment by frainzy1477** [comment]
Not possible, i have tested several times and no errors, maybe problem with your firmware

**Comment by Kihara777** [comment]
May be you are right... force downgrade to luci-app-clash v1.5.1 and opkg throw me few lines of ”sh: out of range”, so I downgrade to openwrt 18.06 and the status update correctly now.
