### ISSUE TITLE
ClashTUN : socket: too many open files

### ISSUE THREAD

**Issue by m4niacjp** [frainzy1477/luci-app-clash#155]
I'm trying to use ClashTUN but not working as per following error:

time="2020-02-07T04:17:54Z" level=warning msg="dial DIRECT error: dial tcp4 IP: socket: too many open files"

Basically i've downloaded TUN from [ArmV7](https://github.com/Dreamacro/clash/releases/download/TUN/clash-linux-armv7-v0.17.1-19-g8757868.gz) as i'm using a Netgear R7800. 
Then i move into /etc/clash/clashtun/ and start the client Clash(cTUn). Everything starts with fake-ip but got the above error. 

By the way i'm using CLASH for DNS as i have my own Pihole with DoH so my router is directing all DNS requests to my pihole and it's working normally with your version of normal Clash.

**Comment by frainzy1477** [comment]
try redir-host instea of fake-ip

**Comment by m4niacjp** [comment]
Yes i've already tried using both fake-ip and redir-host, same issue.
I've also try to use your TUN ArmV7 from your website instead of directly from Dreamacro and same issue.
 
The normal version of clash with redir-host is working perfectly but i can't manage to use the cTun version of yours as too many open files error will come.

Now i will try on another router that i have where i will fresh install OpenWRT and see if the problem still there.

**Comment by m4niacjp** [comment]
I've tried a fresh installation on another router, while again Clash is working the cTUn version have yet again problem, this time a different one.

`time="2020-02-08T05:52:44Z" level=error msg="Start Tun interface error: Can't open tun: no such file or directory"`

But very strange since the file is there in the folder

`root@OpenWrt:~# ls /etc/clash/clashtun/
clash
root@OpenWrt:~#
`

**Comment by frainzy1477** [comment]
> I've tried a fresh installation on another router, while again Clash is working the cTUn version have yet again problem, this time a different one.
> 
> `time="2020-02-08T05:52:44Z" level=error msg="Start Tun interface error: Can't open tun: no such file or directory`
> 
> But very strange since the file is there in the folder
> 
> ```
> root@OpenWrt:~# ls /etc/clash/clashtun/
> clash
> root@OpenWrt:~#
> ```

you need to install kmod-tun

**Comment by m4niacjp** [comment]
Yeah i forgot to install kmod-tun. Unfortunately the problem was not solved, clean install of OpenWRT 19.07 on a new router, install of clash and dTun. Clash works perfectly both fake-ip and redir-host. dTun just doesn't seem to work.

`time="2020-02-08T07:36:17Z" level=warning msg="dial 其它规则外 error: dial tcp4 xxx:443: socket: too many open files"`

Same problem as on the other router.

**Comment by frainzy1477** [comment]
you can compile from source and see https://github.com/comzyh/clash  (ctun)

or download    Dreamacro  Experimental TUN https://github.com/Dreamacro/clash/releases/tag/TUN (dtun)

**Comment by frainzy1477** [comment]
i am runing Openwrt Koolshare mod V2.31 r10822-50aa0525d1, i have no problem, you do not need to always use a latest firmware because it have new features, one that works perfectly is enough

**Comment by frainzy1477** [comment]
![image](https://user-images.githubusercontent.com/49537471/74081773-9fcbd000-4a8d-11ea-9953-32b2cfe7263e.png)

**Comment by m4niacjp** [comment]
Can you try on classic OpenWRT 19.07? I've tried on 2 routers still no luck.

Anyway with OpenWRT lean that was able to run?

**Comment by frainzy1477** [comment]
> Can you try on classic OpenWRT 19.07? I've tried on 2 routers still no luck.
> 
> Anyone that successfully installed on lean OpenWRT?

Problem fixed

https://github.com/frainzy1477/luci-app-clash/commit/cfa686487eaba80710bc7c296cba575130b1b327
