### ISSUE TITLE
Dependency missing: luci-compat

### ISSUE THREAD

**Issue by m4niacjp** [frainzy1477/luci-app-clash#157]
As per OpenWRT 19.07 you should add in the dependency luci-compat in order to use luci interface. 
On a new installation will appear the following error:

```
Failed to execute cbi dispatcher target for entry '/admin/services/clash/overview'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:938: module 'luci.cbi' not found:
```

By installing luci-compat you will resolve this issue.

**Comment by KnectBis** [comment]
Same problem.

**Comment by Mosney** [comment]
opkg update 
opkg install luci-compat

**Comment by m4niacjp** [comment]
> 
> 
> opkg update
> opkg install luci-compat

Yes, this is what i mentioned in my post. When you install luci-app-clash should have in the dependency luci-compat

**Comment by frainzy1477** [comment]
Ok, i did not consider on OP 19.07, will add dependency later
