### ISSUE TITLE
iptables output表存在死循环

### ISSUE THREAD

**Issue by thank243** [frainzy1477/luci-app-clash#159]
具体表现是当fakeip映射丢失时，路由器会通过wan接口向外请求fakeip段地址，经过output是又会被redir回7892，然后继续循环。路由器因为这个已经每天自动重启多次，希望尽快处理。谢谢大佬。

**Comment by thank243** [comment]
![image](https://user-images.githubusercontent.com/11692994/74097743-d1ef3780-4b4a-11ea-8337-6f561018e564.png)

**Comment by wangxin6** [comment]
最终规则之前把 fake-ip 访问reject
`- IP-CIDR,198.18.0.1/16,REJECT`
`- MATCH,Proxy`

**Comment by thank243** [comment]
> 最终规则之前把 fake-ip 访问reject
> `- IP-CIDR,198.18.0.1/16,REJECT`
> `- MATCH,Proxy`

好的。回去我试试
