### ISSUE TITLE
how to set clash client to disable

### ISSUE THREAD

**Issue by ztechie** [frainzy1477/luci-app-clash#16]
how to set clash client to disable？Cancel start button ，save？

**Comment by wangxin6** [comment]
【客户端】- 【启用】- 【保存&应用】，再去【日志】看一下，是否提示disable。

**Comment by frainzy1477** [comment]
> 【客户端】- 【启用】- 【保存&应用】，再去【日志】看一下，是否提示disable。
是这一样
