### ISSUE TITLE
V1.5.4 Restore Config 功能未实现

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#161]
/usr/share/clashbackup/history 文件已存在。但是停止/重启clash还是第一个节点组，未恢复重启前选择的节点组。

**Comment by wangxin6** [comment]
刚切换了一下core，功能又好了。。。

**Comment by frainzy1477** [comment]
It works without any issue, i have tested several times

**Comment by frainzy1477** [comment]
is an issues with the core https://github.com/comzyh/clash itself not luci pr lua issue

**Comment by frainzy1477** [comment]
> 刚切换了一下core，功能又好了。。。
> 会随机失效/有效

https://github.com/frainzy1477/luci-app-clash/commit/28325f7183a98fd984547bb0f97cf33919273183
