### ISSUE TITLE
cTun不能正常运行

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#162]
在update页面下载最新的cTun core。运行出现如下错误：
![Screen Shot](https://user-images.githubusercontent.com/24645789/74098459-55148b80-4b53-11ea-979c-6e8f10f13ba5.JPEG)

**Comment by frainzy1477** [comment]
if core have a problem please open an issue with the developer, i am not responsible for that.

**Comment by wangxin6** [comment]
感觉不是core的问题。和重启恢复配置有关。错误日志出现了/home/vernesong/clash-tun/clash/....
