### ISSUE TITLE
 GEOIP Issues

### ISSUE THREAD

**Issue by m4niacjp** [frainzy1477/luci-app-clash#165]
I'm having issues with GEOIP detecting the proper flow, as per example if i try to access taobao.com i get the following

`2020-02-12 14:46:34[info] 192.168.1.216 --> 47.246.25.253 match Match using 其它规则外[HKBN波澜]`

While in fact GEOIP of that address belongs to a chinese IP address as per page https://ipinfo.io/AS24429 

```
47.246.25.0/24 | Alibaba.com LLC | 256
-- | -- | --
```

In my config i've already setup the rule

`- GEOIP,CN,国内网站或资源`

**Comment by wangxin6** [comment]
![Screen Shot](https://user-images.githubusercontent.com/24645789/74316542-ab343980-4db4-11ea-802e-488bb9fdeb66.JPEG)

**Comment by m4niacjp** [comment]
You are correct, i had a problem in DNS handling not GEOIP.
