### ISSUE TITLE
可以在 koolshare 上面 安装 clashr 吗

### ISSUE THREAD

**Issue by wangruicacc0731** [frainzy1477/luci-app-clash#166]
您好，我是 新手，看了您发布的这个 clash 的 luci 想问问这个能直接用于在 koolshare 中离线安装clahsr 的软件吗

**Comment by frainzy1477** [comment]
> 您好，我是 新手，看了您发布的这个 clash 的 luci 想问问这个能直接用于在 koolshare 中离线安装clahsr 的软件吗

你没试试，怎么来问？？？？？ 可以了

**Comment by wangruicacc0731** [comment]
您好，不好意思打扰，我试过了呀。在酷软里面只有kool clash.
我安装了，不能订阅ssr转换的托管地址，有啥方法吗，我目前就是安装了openclash
然后替换了核心。但是还是喜欢在酷软里面安装软件进行使用。有啥方法吗

frainzy1477 <notifications@github.com> 于 2020年2月12日周三 下午7:49写道：
