### ISSUE TITLE
create config问题

### ISSUE THREAD

**Issue by gg4924** [frainzy1477/luci-app-clash#168]
目前使用v1.5.5，使用create config的时候碰到了一个问题，生成的配置里，在每个组的proxies后都会紧跟当前的组名，导致使用这个生成的配置文件后无法启动clash，一直在那循环。
![Snipaste_2020-02-12_16-44-56](https://user-images.githubusercontent.com/21310130/74318340-fef45200-4db7-11ea-8c1a-859c8eb5df34.png)
只能在config中手动删除才能正常使用。

**Comment by frainzy1477** [comment]
> 目前使用v1.5.5，使用create config的时候碰到了一个问题，生成的配置里，在每个组的proxies后都会紧跟当前的组名，导致使用这个生成的配置文件后无法启动clash，一直在那循环。
> ![Snipaste_2020-02-12_16-44-56](https://user-images.githubusercontent.com/21310130/74318340-fef45200-4db7-11ea-8c1a-859c8eb5df34.png)
> 只能在config中手动删除才能正常使用。

https://github.com/frainzy1477/luci-app-clash/commit/8b2a1ee9231d97d713ae2c06512e373884f6a169   你先修改了
