### ISSUE TITLE
clash(dtun)问题

### ISSUE THREAD

**Issue by brick713** [frainzy1477/luci-app-clash#169]
![image](https://user-images.githubusercontent.com/5291873/74401365-f9e8de80-4e5b-11ea-91bd-8af51d5b5fdf.png)
如图所示 clash(dtun)无法点击检查，好像也没法安装。
已经正常安装了 kmod-tun

**Comment by brick713** [comment]
处理器型号是: arm_cortex-a15_neon-vfpv4

**Comment by brick713** [comment]
ERRO[0000] Start Tun interface error: Can't open tun: no such file or directory 
使用 clash tun 的时候会报错

**Comment by wangxin6** [comment]
在页面选择本地电脑下载好的dtun内核文件上传
