### ISSUE TITLE
yaml和yml的区别？

### ISSUE THREAD

**Issue by hackenfu** [frainzy1477/luci-app-clash#17]
你好，我看etc/clash里面，有yaml和yml两个文件，如果我下载托管文件上传的话是yaml，但是我直接用URL更新的话是更新到yml，到底真正启用的是哪个呢？我有点搞不清楚。我是最新0.15+0.25

**Comment by frainzy1477** [comment]
> 你好，我看etc/clash里面，有yaml和yml两个文件，如果我下载托管文件上传的话是yaml，但是我直接用URL更新的话是更新到yml，到底真正启用的是哪个呢？我有点搞不清楚。我是最新0.15+0.25

0.15.0 就是yaml吧， yml 会出错， 用URL更新的话必须更新到yaml, 你可以删除yml文件
