### ISSUE TITLE
资源占用有时会出现异常

### ISSUE THREAD

**Issue by Limgmk** [frainzy1477/luci-app-clash#170]
![Snipaste_2020-02-13_21-20-24](https://user-images.githubusercontent.com/45861815/74439643-87303100-4e64-11ea-8a21-a159f9c2937b.png)
刚开始启动还没有问题，之后占用会越来越高，最终会爆内存然后无法上网，必须重启。

**Comment by Limgmk** [comment]
进一步看了一下，活动链接是不是太多了？
![image](https://user-images.githubusercontent.com/45861815/74440326-b6936d80-4e65-11ea-91d9-7f528a16d9d9.png)

**Comment by Limgmk** [comment]
通过查看日志，我发现openwrt本身的流量貌似出现了问题，我猜想可能是这条防火墙记录造成的
![Snipaste_2020-02-14_13-51-38](https://user-images.githubusercontent.com/45861815/74505167-5a286080-4eee-11ea-8f1b-6b5dad306630.png)
于是我把这条规则删掉了，目前是正常的。虽然openwrt本机不再走clash，但是可以接受

**Comment by wangxin6** [comment]
在日志中会出现路由器对fake-ip的很多访问
`level=info msg="192.168.0.2 --> 198.18.0.174 match IPCIDR using REJECT"`
不知道和这个issue是否有关联

**Comment by Limgmk** [comment]
我的日志中出现了大量的wan口请求，这个bug比较严重，而且似乎是一个普遍现象，昨天我发现好像有人提了相同的问题https://github.com/frainzy1477/luci-app-clash/issues/159

**Comment by wangxin6** [comment]
在wan口把fake-ip的访问reject
