### ISSUE TITLE
建议将日志等需要大量写入的内容重定向到tmpfs文件系统中

### ISSUE THREAD

**Issue by Mosney** [frainzy1477/luci-app-clash#172]
我注意到目前的日志都是重定向到了 `/usr/share/clash/clash.txt`，大部分情况下这个目录都是挂载的持久化文件系统，对于网关用途的clash来说日志写入量实属不低，应该把它重定向到类似`/tmp/clash.log `之类的tmpfs中并定时截断。

**Comment by wangxin6** [comment]
已有定时脚本`0 0 * * 0 echo "" >> /usr/share/clash/clash.txt`。
如果需要修改周期，可以在`/etc/init.d/clash`中修订，并重启clash生效

**Comment by Mosney** [comment]
重点是日志重定向的位置，如果定时截断有了的话可以忽略掉。
