### ISSUE TITLE
在 Windows 下 NetBIOS 解析会造成大量连接

### ISSUE THREAD

**Issue by hehehehehaha** [frainzy1477/luci-app-clash#175]
系统经常因为内存爆掉重启，看日志发现有时会有大量连接由路由器指向 fake-ip 地址，查到是 NetBIOS 解析造成的问题。模式是普通 Clash ，版本最新。要怎么解决？
![Snipaste_2020-02-18_23-50-10](https://user-images.githubusercontent.com/45707218/74753347-f665b500-52aa-11ea-984a-a219ce076f7f.png)
![Snipaste_2020-02-18_23-53-08](https://user-images.githubusercontent.com/45707218/74753354-f8c80f00-52aa-11ea-8abe-df123b51b977.png)

**Comment by wangxin6** [comment]
#159 最终规则前把 fake-ip 访问 reject
