### ISSUE TITLE
上传dtun后版本号识别不正常

### ISSUE THREAD

**Issue by nb5p** [frainzy1477/luci-app-clash#177]
下面是LuCI和终端显示的版本号。

![CleanShot 2020-02-23 at 17 44 59](https://user-images.githubusercontent.com/2098464/75110069-55894800-5664-11ea-8992-760f3c714bd4.png)

```
root@FriendlyWrt:/etc/clash/dtun# clash -v
Clash v0.17.2.3 linux arm64 Wed Feb 19 13:01:58 UTC 2020
```

**Comment by frainzy1477** [comment]
> 下面是LuCI和终端显示的版本号。
> 
> ![CleanShot 2020-02-23 at 17 44 59](https://user-images.githubusercontent.com/2098464/75110069-55894800-5664-11ea-8992-760f3c714bd4.png)
> 
> ```
> root@FriendlyWrt:/etc/clash/dtun# clash -v
> Clash v0.17.2.3 linux arm64 Wed Feb 19 13:01:58 UTC 2020
> ```

没有问题。是D大在编译给这个版本号

**Comment by nb5p** [comment]
之前是这种情况，在终端输出版本号是0.17.2.3。
```
root@FriendlyWrt:/etc/clash/dtun# clash -v
Clash v0.17.2.3 linux arm64 Wed Feb 19 13:01:58 UTC 2020
```

应该是GitHub的Bug，我下的0.18.0，解压出来是0.17.2.3

**Comment by frainzy1477** [comment]
> 之前是这种情况，在终端输出版本号是0.17.2.3。
> 
> ```
> root@FriendlyWrt:/etc/clash/dtun# clash -v
> Clash v0.17.2.3 linux arm64 Wed Feb 19 13:01:58 UTC 2020
> ```
> 
> 应该是GitHub的Bug。说出来你可能不信，我下的0.18.0，解压出来是0.17.2.3。从新用Wget下载一遍就正常了。

不可能吧

**Comment by nb5p** [comment]
No, renamed after upload

**Comment by frainzy1477** [comment]
> No, renamed after upload

安装v1.5.8, download core rename clash-linux-amd64  to just clash before upload, make sure you select correct core type when uploading on update page of luci-app-clash
