### ISSUE TITLE
你好，好像有一直ping百度。能加个开关吗？ping各个网址的开关

### ISSUE THREAD

**Issue by mmxlyo** [frainzy1477/luci-app-clash#178]

**Comment by frainzy1477** [comment]
啥意思？？

**Comment by crackerfly** [comment]
> 啥意思？？

我猜他大概说的是连通性检测的功能，一直在ping百度，他希望这个功能可以设置是否启用

**Comment by mmxlyo** [comment]
> > 啥意思？？
> 
> 我猜他大概说的是连通性检测的功能，一直在ping百度，他希望这个功能可以设置是否启用

就是这位兄弟说的意思

**Comment by mmxlyo** [comment]
仔细看了下原来是多播的掉线检测，不好意思了
