### ISSUE TITLE
yaml问题（补充）

### ISSUE THREAD

**Issue by hackenfu** [frainzy1477/luci-app-clash#18]
你好，之前您说可以删除yml，但是我删除了之后，URL更新仍然生成新的yml，而且会把我手动上传的yaml清空变成空文件，最后结果就是每次更新URL，yaml是空文件，yml是有内容的，“配置”栏目框内也是空白。我很确定我装的是0.15+0.25。日志如下：
200 OK
Length: 51981 (51K) [application/octet-stream]
Saving to: '/etc/clash/config.yml'

     0K .......... .......... .......... .......... .......... 98% 72.0K 0s
    50K                                                       100% 10.5M=0.7s

2019-07-09 18:42:34 (73.1 KB/s) - '/etc/clash/config.yml' saved [51981/51981]

**Comment by hackenfu** [comment]
再提供一个线索，我尝试全部删除clash和luci-clash，重装这两个之后发现第一次获取没问题，先生成了yml文件，然后改名yaml文件，yml就消失了。但我第二次手动更新链接，就出现上述情况了

**Comment by frainzy1477** [comment]
> 再提供一个线索，我尝试全部删除clash和luci-clash，重装这两个之后发现第一次获取没问题，先生成了yml文件，然后自动重命名后缀yaml，yml就消失了。但我第二次手动更新链接，就出现上述情况了

https://github.com/frainzy1477/luci-app-clash/blob/master/root/usr/share/clash/clash.sh   不可能yml. 我也不知道你自己的是yml
