### ISSUE TITLE
路由器本身流量通过代理

### ISSUE THREAD

**Issue by maddie** [frainzy1477/luci-app-clash#181]
先说一下，clash on openwrt真的是太tm好用了

现在一切设置完以后，内网机器都没有问题了，但是路由器本身的流量貌似没有经过clash，这个是可以设置的，还是说是限制？

我用的是正常的clash core, 没有用tun的版本/clashr

**Comment by maddie** [comment]
换了 clash (dtun) 变成TUN模式以后路由器的流量依然没有经过Clash

这个有办法配置吗？

**Comment by wangxin6** [comment]
`settings - dns settings - DNS forwarding`

**Comment by Mosney** [comment]
最简单的方式--使用fakeIP模式。
不过路由本身的流量最好还是不要直接走代理，你可以在环境变量中设置，这样大部分流量都会使用代理
```
export http_proxy=http://{你运行clash设备的IP}:{你设置的代理端口}
export https_proxy=$http_proxy
export HTTP_PROXY=$http_proxy
export HTTPS_PROXY=$http_proxy
```

**Comment by maddie** [comment]
@wangxin6 跟dns forwarding没有关系吧？

@Mosney 按道理设置正确的iptables是没有问题的，ss/v2ray之类的用redirect/tproxy都可以达到效果。目前也只能先这样用着了，谢谢。

**Comment by matthuo333** [comment]
> @wangxin6 跟dns forwarding没有关系吧？
> 
> @Mosney 按道理设置正确的iptables是没有问题的，ss/v2ray之类的用redirect/tproxy都可以达到效果。目前也只能先这样用着了，谢谢。

最后试了上述各大神提出的方案了么？
