### ISSUE TITLE
怎么安装啊 ，openwrt19.0.7

### ISSUE THREAD

**Issue by miroda** [frainzy1477/luci-app-clash#182]
报了很多错误
`Multiple packages (luci-app-clash and luci-app-clash) providing same name marked HOLD or PREFER. Using latest.
Installing luci-app-clash (1.5.8) to root...
Installing libmbedtls12 (2.16.4-1) to root...
Collected errors:
 * opkg_download_pkg: Package libmbedtls12 is not available from any configured src.
 * opkg_install_pkg: Failed to download libmbedtls12. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package luci-app-clash.`

**Comment by wangxin6** [comment]
先运行`opkg update `再安装

**Comment by Mosney** [comment]
请使用正规OpenWrt，至少包管理要正常工作
