### ISSUE TITLE
停止再运行后进程列表有多个watchdog和/etc/init.d/clash restart一直运行

### ISSUE THREAD

**Issue by maddie** [frainzy1477/luci-app-clash#184]
如题。

看到最后两个commit把watchdog换成了restore，不知道是否解决这个问题？

**Comment by frainzy1477** [comment]
> 如题。
> 
> 看到最后两个commit把watchdog换成了restore，不知道是否解决这个问题？

最commit修了

**Comment by maddie** [comment]
ok，另外想问问，Clash启动以后，路由器上面的DNS是怎么走的？

我看init脚本里面 if listen: 0.0.0.0:53 就 添加 127.0.0.1:5300 到dnsmasq里 else 添加 127.0.0.1:$port

我的config里面原本是有 0.0.0.0:53 的，但是却没看到 dnsmasq 里面有添加 127.0.0.1:5300

现在我遇到的问题是：

1. 5300端口是luci-app-clash在后面添加的监听吗？流量怎么走的呢？
2. 如上所述，dnsmasq的forwarding servers里面没有127.0.0.1:5300，导致无法解析
3. 手动把127.0.0.1:5300添加到 dnsmasq 中，DNS也貌似无法解析？但这可能是我本地cache问题

谢谢解答！

**Comment by Scorpion4286** [comment]
设置->DNS设置->DNS转发 确定开了么？配置文件有没有动过？
别直接手动转发，先ssh用netstat之类的看看5300端口的服务有没有吧。
也可以nslookup指定端口看看结果。

**Comment by maddie** [comment]
开了，配置文件没有动过
没有手动转发，手动指定nslookup也查询不了

换成openclash就没有问题

**Comment by frainzy1477** [comment]
> ok，另外想问问，Clash启动以后，路由器上面的DNS是怎么走的？
> 
> 我看init脚本里面 if listen: 0.0.0.0:53 就 添加 127.0.0.1:5300 到dnsmasq里 else 添加 127.0.0.1:$port
> 
> 我的config里面原本是有 0.0.0.0:53 的，但是却没看到 dnsmasq 里面有添加 127.0.0.1:5300
> 
> 现在我遇到的问题是：
> 
> 1. 5300端口是luci-app-clash在后面添加的监听吗？流量怎么走的呢？
> 2. 如上所述，dnsmasq的forwarding servers里面没有127.0.0.1:5300，导致无法解析
> 3. 手动把127.0.0.1:5300添加到 dnsmasq 中，DNS也貌似无法解析？但这可能是我本地cache问题
> 
> 谢谢解答！

listen的53端口不能用，自动切换到5300端口
https://github.com/frainzy1477/luci-app-clash/blob/c0b84ee7dafdf6616c713895c4c19ed0c60d7ae6/root/etc/init.d/clash#L147
