### ISSUE TITLE
bypass LAN IP issue

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#19]
【设置】-【不走代理的局域网IP】-【保存&应用】

Issue1. 添加不走代理的局域网IP后，此IP无法访问任何网站

Issue2. 【保存&应用】不会立即生效。需要到【客户端】-【启用】关闭再打开才生效

**Comment by frainzy1477** [comment]
> 【设置】-【不走代理的局域网IP】-【保存&应用】
> 
> Issue1. 添加不走代理的局域网IP后，此IP无法访问任何网站
> 
> Issue2. 【保存&应用】不会立即生效。需要到【客户端】-【启用】关闭再打开才生效

我自己试试了， 没有问题。我用是x86_64 OP没有啥问题

**Comment by frainzy1477** [comment]
> 同x86_64 op，两个问题都存在

我自己编译x86_64 op lean的没有问题， 我不是VM安装OP，直接安装OP

**Comment by frainzy1477** [comment]
主机名 | X86
-- | --
主机型号 | Intel(R) Celeron(R) CPU J1900 @ 1.99GHz : 4 Core 4 Thread
CPU信息 | 1999.322 MHz (CpuMark : 27568.922306 Scores) +35.0°C
固件版本 | OpenWrt R9.5.1 By Lean / LuCI Master (git-19.121.62139-9ee402e)
内核版本 | 4.9.171
本地时间 | Tue Jul 9 23:15:24 2019
运行时间 | 7d 7h 2m 32s
平均负载 | 0.08, 0.13, 0.10

**Comment by wangxin6** [comment]
![屏幕快照 2019-07-09 下午11 43 21](https://user-images.githubusercontent.com/24645789/60903144-62a72180-a2a3-11e9-9669-580036300a39.JPEG)

**Comment by wangxin6** [comment]
enhanced-mode 从 fake-ip 该为 redir-host 问题1解决。

但问题2依旧存在。
