### ISSUE TITLE
计划任务设置问题及其引发的dns转发失效

### ISSUE THREAD

**Issue by Scorpion4286** [frainzy1477/luci-app-clash#190]
环境 OpenWrt 19.07.2

版本 1.5.9

问题
执行“停用客户端”时未删除cron中的配置，导致再启动时会连续启动多个clash。
并且由于连续启动过程中的dnsmasq重复重启行为，有机会导致uci中的dns转发设置丢失。

**Comment by Scorpion4286** [comment]
抱歉描述有误，又试了下。
DNS转发配置丢失应该是其他issue。

目前暂时可以通过让clash直接监听53端口或手动配置dnsmasq解决。

**Comment by frainzy1477** [comment]
> 环境 OpenWrt 19.07.2
> 
> 版本 1.5.9
> 
> 问题
> 执行“停用客户端”时未删除cron中的配置，导致再启动时会连续启动多个clash。
> 并且由于连续启动过程中的dnsmasq重复重启行为，有机会导致uci中的dns转发设置丢失。

更新了
