### ISSUE TITLE
V1.5.9 无法在线更新 clashr core

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#191]
在 system log 中可以发现如下日志：
`daemon.err uhttpd[2733]: rm: can't remove '/var/run/core_update_error': No such file or directory` 
` daemon.err uhttpd[2733]: rm: can't remove '/var/run/core_update': No such file or directory`

**Comment by frainzy1477** [comment]
> 在 system log 中可以发现如下日志：
> `daemon.err uhttpd[2733]: rm: can't remove '/var/run/core_update_error': No such file or directory`
> ` daemon.err uhttpd[2733]: rm: can't remove '/var/run/core_update': No such file or directory`

更新了
