### ISSUE TITLE
可以设置只代理80、442、20端口吗？

### ISSUE THREAD

**Issue by evindu** [frainzy1477/luci-app-clash#193]
路由器开启代理后默认所有端口都会走clash，能设置只代理80/443/20端口吗？避免其他迅雷、bt端口走代理

**Comment by Scorpion4286** [comment]
这是clash的yaml配置问题，与本项目无关，请close掉。

目前Clash支持的规则类型如下，请自己适配你的需求：
DOMAIN-SUFFIX：域名后缀匹配
DOMAIN：域名匹配
DOMAIN-KEYWORD：域名关键字匹配
IP-CIDR：IP段匹配
SRC-IP-CIDR：源IP段匹配
GEOIP：GEOIP数据库（国家代码）匹配
DST-PORT：目标端口匹配
SRC-PORT：源端口匹配
MATCH：全匹配（一般放在最后）
