### ISSUE TITLE
随固件一起编译，连接openwrt管理页面出现CA证书验证，如何解决？

### ISSUE THREAD

**Issue by bijiamo** [frainzy1477/luci-app-clash#196]
![TIM截图20200308131425](https://user-images.githubusercontent.com/61779399/76157286-a0fe2480-6141-11ea-89e0-274041787ff7.png)
libustream-openssl
libopenssl
openssl-util
把这上面三个依赖删掉会出现什么问题么，影响使用么？？

**Comment by wangxin6** [comment]
要问你的固件源码提供者。和clash luci无关

**Comment by Scorpion4286** [comment]
> ![TIM截图20200308131425](https://user-images.githubusercontent.com/61779399/76157286-a0fe2480-6141-11ea-89e0-274041787ff7.png)
> libustream-openssl
> libopenssl
> openssl-util
> 把这上面三个依赖删掉会出现什么问题么，影响使用么？？

求求了，不懂别乱搞乱问，自己先学学基础知识，提issue之前先看看别人提过的，这又不是论坛，别把大佬搞烦了不更新了。

这里的CA是你开了https访问，编译的时候产生的自签证书，又不是可信机构签发的，当然会显示不安全。
你把证书添加信任，或者把https关了，要么自己找教程去改证书。

此issue与本项目无关，麻烦你close掉。

**Comment by lloyd18** [comment]
> > ![TIM截图20200308131425](https://user-images.githubusercontent.com/61779399/76157286-a0fe2480-6141-11ea-89e0-274041787ff7.png)
> > libustream-openssl
> > libopenssl
> > openssl-util
> > 把这上面三个依赖删掉会出现什么问题么，影响使用么？？
> 
> #195
> 
> 求求了，不懂别乱搞乱问，自己先学学基础知识，提issue之前先看看别人提过的，这又不是论坛，别把大佬搞烦了不更新了。
> 
> 这里的CA是你开了https访问，编译的时候产生的自签证书，又不是可信机构签发的，当然会显示不安全。
> 你把证书添加信任，或者把https关了，要么自己找教程去改证书。
> 
> 此issue与本项目无关，麻烦你close掉。

在官方源码下依赖openssl-util确实会导致默认打开https，不懂就问，我不觉得楼主哪里有错。

**Comment by Scorpion4286** [comment]
> > > ![TIM截图20200308131425](https://user-images.githubusercontent.com/61779399/76157286-a0fe2480-6141-11ea-89e0-274041787ff7.png)
> > > libustream-openssl
> > > libopenssl
> > > openssl-util
> > > 把这上面三个依赖删掉会出现什么问题么，影响使用么？？
> > 
> > 
> > #195
> > 求求了，不懂别乱搞乱问，自己先学学基础知识，提issue之前先看看别人提过的，这又不是论坛，别把大佬搞烦了不更新了。
> > 这里的CA是你开了https访问，编译的时候产生的自签证书，又不是可信机构签发的，当然会显示不安全。
> > 你把证书添加信任，或者把https关了，要么自己找教程去改证书。
> > 此issue与本项目无关，麻烦你close掉。
> 
> 在官方源码下依赖openssl-util确实会导致默认打开https，不懂就问，我不觉得楼主哪里有错。

见issue#195

**Comment by lloyd18** [comment]
> > > > ![TIM截图20200308131425](https://user-images.githubusercontent.com/61779399/76157286-a0fe2480-6141-11ea-89e0-274041787ff7.png)
> > > > libustream-openssl
> > > > libopenssl
> > > > openssl-util
> > > > 把这上面三个依赖删掉会出现什么问题么，影响使用么？？
> > > 
> > > 
> > > #195
> > > 求求了，不懂别乱搞乱问，自己先学学基础知识，提issue之前先看看别人提过的，这又不是论坛，别把大佬搞烦了不更新了。
> > > 这里的CA是你开了https访问，编译的时候产生的自签证书，又不是可信机构签发的，当然会显示不安全。
> > > 你把证书添加信任，或者把https关了，要么自己找教程去改证书。
> > > 此issue与本项目无关，麻烦你close掉。
> > 
> > 
> > 在官方源码下依赖openssl-util确实会导致默认打开https，不懂就问，我不觉得楼主哪里有错。
> 
> 见issue#195

啥也不知道，上来就怼，真是什么人都有
