### ISSUE TITLE
官方源码。error: recursive dependency detected!

### ISSUE THREAD

**Issue by lloyd18** [frainzy1477/luci-app-clash#197]
lan@ubuntu:~/openwrt$ rm -rf ./tmp && rm -rf .config
lan@ubuntu:~/openwrt$ make menuconfig
Collecting package info: done
Collecting target info: done
tmp/.config-package.in:73186:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:73186:	symbol PACKAGE_luci-app-clash depends on PACKAGE_rpcd
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:1080:	symbol PACKAGE_rpcd is selected by PACKAGE_attendedsysupgrade-common
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:7:	symbol PACKAGE_attendedsysupgrade-common is selected by PACKAGE_luci-app-attendedsysupgrade
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:73536:	symbol PACKAGE_luci-app-attendedsysupgrade depends on PACKAGE_uhttpd
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:134678:	symbol PACKAGE_uhttpd is selected by PACKAGE_luci
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:73074:	symbol PACKAGE_luci is selected by PACKAGE_luci-app-clash

**Comment by frainzy1477** [comment]
you can remove the dependency causing such errors if your are compiling on your own.
