### ISSUE TITLE
关闭DNS转发，启动局域网DNS服务器，是填多少127.0.0.1吗？

### ISSUE THREAD

**Issue by z877303287** [frainzy1477/luci-app-clash#199]

**Comment by frainzy1477** [comment]
关闭DNS转发就用你的局域网DNS服务器

**Comment by easyinplay** [comment]
> 关闭DNS转发就用你的局域网DNS服务器


自定义局域网DNS服务器填写之后会覆写 openwrt网络中的DNS服务器（原来填写的会被覆盖掉）。
所以我理解关闭DNS转发就是用的openwrt网络中的DNS服务器，所以不太明白这里让填写自定义服务器会在什么场景下用到？ 如果没什么用我感觉留在那里会让人有点疑惑
