### ISSUE TITLE
‘概览’页面闪动

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#2]
停留在‘概览’页面，会发现页面会闪动，就像IE使用F5刷新页面一样。

**Comment by frainzy1477** [comment]
> 停留在‘概览’页面，会发现页面会闪动，就像IE使用F5刷新页面一样。

我没有这个问题， chrome 没有问题

**Comment by wangxin6** [comment]
MacOS Sierra + Safari 11.1.2 ／ Iphone 11.4 + Mobile Safari 11.0 都有闪动的问题。此问题是最近版本出现的。

**Comment by wangxin6** [comment]
通过日志可以看到是由于【概览】页面不断的在检测链接情况造成的页面刷新
