### ISSUE TITLE
本地配置文件上传后在配置标签页不显示

### ISSUE THREAD

**Issue by easyinplay** [frainzy1477/luci-app-clash#201]
本地配置文件上传后在配置标签页不显示，具体情况如下图所示，配置文件应该没有问题 在openclash中正常显示
![image](https://user-images.githubusercontent.com/4202001/76455801-105d6800-6411-11ea-8f9d-feffa2cf7c3d.png)
![image](https://user-images.githubusercontent.com/4202001/76455849-21a67480-6411-11ea-9d53-f324f59acfa9.png)

**Comment by frainzy1477** [comment]
上传配置必须 .yaml

**Comment by frainzy1477** [comment]
更新了

**Comment by easyinplay** [comment]
好的，多谢朋友辛苦更新

**Comment by easyinplay** [comment]
> 更新了

多谢朋友辛苦更新
