### ISSUE TITLE
libubox20191228 wants to install file /lib/libubox.so 请问这个 怎么解决？

### ISSUE THREAD

**Issue by iJayscn** [frainzy1477/luci-app-clash#202]
root@CC:/tmp# opkg install luci-app-clash_1.6.2_all.ipk  --force-depends
Installing luci-app-clash (1.6.2) to root...
Installing libubox20191228 (2020-02-27-7da66430-1) to root...
Downloading http://downloads.openwrt.org/snapshots/packages/mipsel_24kc/base/libubox20191228_2020-02-27-7da66430-1_mipsel_24kc.ipk
Collected errors:
 * check_data_file_clashes: Package libubox20191228 wants to install file /lib/libubox.so
	But that file is already provided by package  * libubox
 * opkg_install_cmd: Cannot install package luci-app-clash.

**Comment by wangxin6** [comment]
try opkg install libubox --force-overwrite

**Comment by iJayscn** [comment]
> try opkg install libubox --force-overwrite

无效！

**Comment by wangxin6** [comment]
无效就去问你的固件源码作者，和此repo无关。

**Comment by yunkuaiji** [comment]
应该是： opkg install luci-app-clash_1.6.2_all.ipk --force-overwrite

**Comment by Tagima** [comment]
> try opkg install libubox --force-overwrite

I had the same issue as @iJayscn when trying to install uqmi package. @wangxin6 solution worked pretty well. I was afraid that forcing installation would damage another thing, but it turns out that everything worked fine. It may not be the best solution though.
