### ISSUE TITLE
关于dns转发

### ISSUE THREAD

**Issue by zcracker** [frainzy1477/luci-app-clash#204]
开启dns转发，路由器性能直线下降，上传下载速度都上不去，勾选了启用自定义dns，不选择开启dnd转发，谷歌油管都上不去，仍然启用自定义dns，fake-ip模式，联通宽带  ,自定义dns这两个好像查不到什么信息
- tls://118.89.110.78:853
  - tls://47.96.179.163:853

**Comment by frainzy1477** [comment]
> 开启dns转发，路由器性能直线下降，上传下载速度都上不去，勾选了启用自定义dns，不选择开启dnd转发，谷歌油管都上不去，仍然启用自定义dns，fake-ip模式，联通宽带 ,自定义dns这两个好像查不到什么信息
> 
> * tls://118.89.110.78:853
>   
>   * tls://47.96.179.163:853

https://github.com/frainzy1477/luci-app-clash/commit/3b040f86a278105a504aff47e59eff136c9c4ef3

**Comment by zcracker** [comment]
经过多次测试，关闭dns转发，油管谷歌就无法访问，好像存在dns污染，但是DNS转发开启，迅雷等下载app，上传下载速度都上不去（启用了自定义dns）

**Comment by wangxin6** [comment]
fake-ip 模式 dns 只是做国内外判断，用简单点的 114.114.114.114 即可防污染

**Comment by zcracker** [comment]
> fake-ip 模式 dns 只是做国内外判断，用简单点的 114.114.114.114 即可防污染

奇怪的问题，不启动DNS转发模式是上不去的，不知道问题出在哪里，启用自定义dns也选择了

**Comment by wangxin6** [comment]
dns 转发是解决路由器自身流量出国。自定义 dns 是解决配置文件（特别是订阅配置）无 dns。两个都叫 dns。作用不一样。贴出你的页面配置

**Comment by zcracker** [comment]
![image](https://user-images.githubusercontent.com/9046704/76742526-2e79ee00-67ac-11ea-834f-f7a6eb40d600.png)

**Comment by wangxin6** [comment]
DNS 设置页面

**Comment by zcracker** [comment]
![image](https://user-images.githubusercontent.com/9046704/76742725-857fc300-67ac-11ea-82ce-0935792979c7.png)

**Comment by zcracker** [comment]
![image](https://user-images.githubusercontent.com/9046704/76742781-9d574700-67ac-11ea-8d56-34c846e8e25e.png)

**Comment by zcracker** [comment]
启用DNS转发马上正常，不知道问题出在哪里

**Comment by wangxin6** [comment]
供参考：
![Screen Shot](https://user-images.githubusercontent.com/24645789/76743071-063ebf00-67ad-11ea-9350-af639f8b00b1.JPEG)



另：启用UDP建议停用

**Comment by zcracker** [comment]
奇怪的问题.我从1.3.9升级的，1.3.9正常的，1.6.3不正常

**Comment by zcracker** [comment]
> DNS 设置页面

你试试你的，关闭dns转发

**Comment by zcracker** [comment]
1.6.3安装后每次启动提示level=fatal msg="Parse config error: yaml: control characters are not allowed"，明天我在试试，1.6.2正常使用

**Comment by zcracker** [comment]
经过多次测试，启动dns正常使用，日志显示域名为level=info msg="[TCP] 10.0.0.208:55087 --> r3---sn-ogueln7y.googlevideo.com match DomainSuffix，不启用dns转发，显示为
time="2020-03-17T02:04:38Z" level=warning msg="dial DIRECT error: dial tcp4 69.171.234.48:443: i/o timeout"
time="2020-03-17T02:04:41Z" level=warning msg="dial DIRECT error: dial tcp4 216.58.200.46:443: i/o timeout"
time="2020-03-17T02:04:41Z" level=warning msg="dial DIRECT error: dial tcp4 172.217.160.78:443: i/o timeout"
time="2020-03-17T02:04:44Z" level=warning msg="dial DIRECT error: dial tcp4 216.58.200.46:443: i/o timeout"

**Comment by zcracker** [comment]
> > 开启dns转发，路由器性能直线下降，上传下载速度都上不去，勾选了启用自定义dns，不选择开启dnd转发，谷歌油管都上不去，仍然启用自定义dns，fake-ip模式，联通宽带 ,自定义dns这两个好像查不到什么信息
> > 
> > * tls://118.89.110.78:853
> >   
> >   * tls://47.96.179.163:853
> 
> [3b040f8](https://github.com/frainzy1477/luci-app-clash/commit/3b040f86a278105a504aff47e59eff136c9c4ef3)

谢谢幸苦付出，dns转发确实有bug，有空修复下，给个paypay码，打赏杯咖啡啥的，支付宝微信均可啊

**Comment by zcracker** [comment]
经过测试1.4.2产生了这个问题，1.4.2之前没这个问题

**Comment by evindu** [comment]
我设置了之后，能上外网，但是日志里全是DNS 失败
![截屏2020-03-19下午9 23 28](https://user-images.githubusercontent.com/7939349/77072340-7f961600-6a28-11ea-89ae-0654b12017ee.png)
![截屏2020-03-19下午9 28 30](https://user-images.githubusercontent.com/7939349/77072432-a48a8900-6a28-11ea-8017-5ad273d1a990.png)
![截屏2020-03-19下午9 28 42](https://user-images.githubusercontent.com/7939349/77072436-a6544c80-6a28-11ea-85a3-c1464fa6d914.png)

**Comment by evindu** [comment]
不启用DNS缓存也是DNS faild

**Comment by evindu** [comment]
我不开自定义DNS 使用上传的yaml配置文件，不会出现DNS faild的问题
`
# HTTP 代理端口
port: 7890

# SOCKS5 代理端口
socks-port: 7891

# 允许局域网的连接（可用来共享代理）
allow-lan: true
 bind-address: "*"
# 此功能仅在 allow-lan 设置为 true 时生效，支持三种参数：
# "*"                           绑定所有的 IP 地址
# 192.168.122.11                绑定一个的 IPv4 地址
# "[aaaa::a8aa:ff:fe09:57d8]"   绑定一个 IPv6 地址

mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
# 实验性功能
experimental:
  ignore-resolve-fail: true # 忽略 DNS 解析失败，默认值为 true
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host # redir-host fake-ip
  # fake-ip-range: 198.18.0.1/16 # 如果你不知道这个参数的作用，请勿修改
  # fake-ip-filter: # fake-ip 白名单列表
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com

  nameserver:
    - 127.0.0.1:6053
     
  fallback: 
    - tls://13800000000.rubyfish.cn:853
    - tls://1.0.0.1:853
    - tls://dns.google:853

fallback-filter:
  geoip: true # 默认
  ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
    - 240.0.0.0/4
`

**Comment by frainzy1477** [comment]
> 我不开自定义DNS 使用上传的yaml配置文件，不会出现DNS faild的问题
> 
> ```
> # HTTP 代理端口
> port: 7890
> 
> # SOCKS5 代理端口
> socks-port: 7891
> 
> # 允许局域网的连接（可用来共享代理）
> allow-lan: true
>  bind-address: "*"
> # 此功能仅在 allow-lan 设置为 true 时生效，支持三种参数：
> # "*"                           绑定所有的 IP 地址
> # 192.168.122.11                绑定一个的 IPv4 地址
> # "[aaaa::a8aa:ff:fe09:57d8]"   绑定一个 IPv6 地址
> 
> mode: Rule
> log-level: info
> external-controller: 0.0.0.0:9090
> # 实验性功能
> experimental:
>   ignore-resolve-fail: true # 忽略 DNS 解析失败，默认值为 true
> dns:
>   enable: true
>   ipv6: false
>   listen: 0.0.0.0:53
>   enhanced-mode: redir-host # redir-host fake-ip
>   # fake-ip-range: 198.18.0.1/16 # 如果你不知道这个参数的作用，请勿修改
>   # fake-ip-filter: # fake-ip 白名单列表
>   #   - '*.lan'
>   #   - localhost.ptlogin2.qq.com
> 
>   nameserver:
>     - 127.0.0.1:6053
>      
>   fallback: 
>     - tls://13800000000.rubyfish.cn:853
>     - tls://1.0.0.1:853
>     - tls://dns.google:853
> 
> fallback-filter:
>   geoip: true # 默认
>   ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
>     - 240.0.0.0/4
> ```

你自己在用smartdns（nameserver)出现，这是luci问题吗？？？

**Comment by evindu** [comment]
@frainzy1477   可能我没说清楚，"DNS设置"里的"自定义DNS"打开，”修改DNS“框内nameserver里填”- 127.0.0.1:6053” 会出现DNS faild 的情况，
关闭"DNS设置"里的"自定义DNS"，使用上传的yaml配置文件，配置文件内nameserver里也是同样的”- 127.0.0.1:6053” ，不会出现DNS faild 的情况。 所以不知道为什么会这样
