### ISSUE TITLE
我想问下，我这路由可以直接下载这里的clash安装吗？

### ISSUE THREAD

**Issue by mchotdograp** [frainzy1477/luci-app-clash#205]
搜了几个地方，也没看明白到底用哪个版本的合适，我的是：
NETGEAR WNDR3800
CPU型号 | Atheros AR7161 rev 2
CPU主频 | 680 MHz
内存频率 | 340 MHz
闪存容量 | 16 MB
固件版本 | OpenWrt Barrier Breaker 14.07 r47805 元旦版 by 明月永在
内核版本 | 3.10.70
如果有清楚的，麻烦请告知一下，感谢！🙏

**Comment by frainzy1477** [comment]
> 搜了几个地方，也没看明白到底用哪个版本的合适，我的是：
> NETGEAR WNDR3800
> CPU型号 | Atheros AR7161 rev 2
> CPU主频 | 680 MHz
> 内存频率 | 340 MHz
> 闪存容量 | 16 MB
> 固件版本 | OpenWrt Barrier Breaker 14.07 r47805 元旦版 by 明月永在
> 内核版本 | 3.10.70
> 如果有清楚的，麻烦请告知一下，感谢！🙏

你可以试试

**Comment by zcracker** [comment]
> 搜了几个地方，也没看明白到底用哪个版本的合适，我的是：
> NETGEAR WNDR3800
> CPU型号 | Atheros AR7161 rev 2
> CPU主频 | 680 MHz
> 内存频率 | 340 MHz
> 闪存容量 | 16 MB
> 固件版本 | OpenWrt Barrier Breaker 14.07 r47805 元旦版 by 明月永在
> 内核版本 | 3.10.70
> 如果有清楚的，麻烦请告知一下，感谢！🙏

性能太差了，别安装了，跑不动
