### ISSUE TITLE
启动脚本会影响原有的防火墙规则

### ISSUE THREAD

**Issue by Mosney** [frainzy1477/luci-app-clash#207]
### 现象：
手机使用移动网络 WIreGuard 客户端VPN连接至 OpenWrt，在开启clash的状态下只能访问局域网无法访问广域网，关闭clash后即可正常访问公网。
### 环境：
OpenWrt 19.07.2 
WireGuard 0.0.20190702-1
WireGuard 使用的逻辑接口为`wg0`，IP为 **192.168.9.0/24**，防火墙区域为`lan`

### 可能的原因：
从现象来看，只能访问防火墙区域为`lan`、不能访问区域为`wan`的网络。因为数据包到达WireGuard（也就是`wg0`）后的IP必然**不是**LAN IP段（如OpenWrt默认的 **192.168.1.0/24**），在本例中手机使用的IP是`192.168.9.2/32`，因此怀疑是 clash 使用 iptables 重定向流量会影响到**非**LAN IP段的转发规则，导致 WireGuard 的收到的数据包只能在防火墙`lan`区域通信，而不能被转发到`wan`，从而导致上述现象发生。
### 相关链接：
https://www.wireguard.com/
https://openwrt.org/docs/guide-user/services/vpn/wireguard/basic

**Comment by oknown** [comment]
我也遇到同样的问题，现象是开启clash后端口转发失效，怀疑是clash的iptables规则影响

**Comment by Mosney** [comment]
经过这段时间使用，基本可以确定clash启动脚本会导致防火墙的规则失效，包含上面 @oknown 所说的端口转发。
