### ISSUE TITLE
libcurl4_7.69.0-1_x86_64.ipk 文件不存在了

### ISSUE THREAD

**Issue by vincentchan24** [frainzy1477/luci-app-clash#208]
你好，安装过程中发现libcurl4_7.69.0-1_x86_64.ipk 疑似不存在服务器上了，导致安装失败，请问有其他的解决办法么？

`root@OpenWRT:/tmp# opkg install luci-app-clash_1.6.3_all.ipk --force-depends
Installing luci-app-clash (1.6.3) to root...
Installing libcurl4 (7.69.0-1) to root...
Downloading http://downloads.openwrt.org/snapshots/packages/x86_64/base/libcurl4_7.69.0-1_x86_64.ipk
Collected errors:
 * opkg_download: Failed to download http://downloads.openwrt.org/snapshots/packages/x86_64/base/libcurl4_7.69.0-1_x86_64.ipk, wget returned 8.
 * opkg_install_pkg: Failed to download libcurl4. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package luci-app-clash.`

请问有其他的解决办法么？

**Comment by zcracker** [comment]
先执行opkg update在安装

**Comment by vincentchan24** [comment]
> 先执行opkg update在安装

已经执行了几次了，但是都不行。是这个文件已经被移除出服务器了呢。

**Comment by zcracker** [comment]
opkg install https://downloads.openwrt.org/releases/19.07.2/packages/x86_64/base/libcurl4_7.66.0-1_x86_64.ipk试试

**Comment by vincentchan24** [comment]
> opkg install [https://downloads.openwrt.org/releases/19.07.2/packages/x86_64/base/libcurl4_7.66.0-1_x86_64.ipk试试](https://downloads.openwrt.org/releases/19.07.2/packages/x86_64/base/libcurl4_7.66.0-1_x86_64.ipk%E8%AF%95%E8%AF%95)

谢谢你的回复。但是还是不行。我已经先手动安装一遍 libcurl了之后，再执行“opkg install luci-app-clash_1.6.3_all.ipk --force-depends”之后，还是提示无法下载到libcurl。

可以看到错误信息如下。 

`root@OpenWRT:/tmp# opkg install libcurl4_7.66.0-1_x86_64.ipk
Installing libcurl4 (7.66.0-1) to root...
Configuring libcurl4.
root@OpenWRT:/tmp# opkg install luci-app-clash_1.6.3_all.ipk
Installing luci-app-clash (1.6.3) to root...
Installing curl (7.69.0-1) to root...
Downloading http://downloads.openwrt.org/snapshots/packages/x86_64/base/curl_7.69.0-1_x86_64.ipk
Collected errors:
 * opkg_download: Failed to download http://downloads.openwrt.org/snapshots/packages/x86_64/base/curl_7.69.0-1_x86_64.ipk, wget returned 8.
 * opkg_install_pkg: Failed to download curl. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package luci-app-clash.
root@OpenWRT:/tmp# opkg install luci-app-clash_1.6.3_all.ipk --force-depends
Installing luci-app-clash (1.6.3) to root...
Installing curl (7.69.0-1) to root...
Downloading http://downloads.openwrt.org/snapshots/packages/x86_64/base/curl_7.69.0-1_x86_64.ipk
Collected errors:
 * opkg_download: Failed to download http://downloads.openwrt.org/snapshots/packages/x86_64/base/curl_7.69.0-1_x86_64.ipk, wget returned 8.
 * opkg_install_pkg: Failed to download curl. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package luci-app-clash.
root@OpenWRT:/tmp#`

**Comment by zcracker** [comment]
你用稳定版不行么，为什么要用sanpshots版本

**Comment by vincentchan24** [comment]
> 你用稳定版不行么，为什么要用sanpshots版本

不好意思，没有明白您的意思。我安装的就是这个最新的1.6.3的版本啊。难道这个不是稳定版？

如果不是这个版本的话，请教一下您说的是哪个版本呢？

谢谢你。

**Comment by zcracker** [comment]
> > 你用稳定版不行么，为什么要用sanpshots版本
> 
> 不好意思，没有明白您的意思。我安装的就是这个最新的1.6.3的版本啊。难道这个不是稳定版？
> 
> 如果不是这个版本的话，请教一下您说的是哪个版本呢？
> 
> 谢谢你。

openwrt19.07.2

**Comment by vincentchan24** [comment]
> > > 你用稳定版不行么，为什么要用sanpshots版本
> > 
> > 
> > 不好意思，没有明白您的意思。我安装的就是这个最新的1.6.3的版本啊。难道这个不是稳定版？
> > 如果不是这个版本的话，请教一下您说的是哪个版本呢？
> > 谢谢你。
> 
> openwrt19.07.2

明白了。谢谢您。我换个版本。
