### ISSUE TITLE
V1.6.3 clash New Config(Rename fields) 支持问题

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#209]
情况一：
1. clash 内核已升级到最新支持新字段 proxies: 和 proxy-groups:。
2. Client - New Config(Rename fields)：Enable。
3. 本地配置文件（或者create config - load config - New Config(Rename fields)：Enable）也已经修订为新字段。

问题：启动 clash 发现 /etc/clash/config.yaml 文件中无proxies， proxy-groups， rules部分。到 dns 段文件结束。

情况二：
1. clash 内核已升级到最新支持新字段 proxies: 和 proxy-groups:。
2. Client - New Config(Rename fields)：Enable。
3. 本地配置文件保留为旧字段。

问题：启动 clash 发现 /etc/clash/config.yaml 文件proxies已修订， proxy-groups保留为原Proxy Groups

**Comment by wangxin6** [comment]
新内核各种姿势（Luci 都无法使用，急盼更新。

**Comment by zcracker** [comment]
> 新内核各种姿势（Luci 都无法使用，急盼更新。

大佬估计这几天在忙

**Comment by frainzy1477** [comment]
好的，有空试试看

**Comment by wangxin6** [comment]
内核迟早要更新，能否下个版本的luci直接支持新字段，不用这个参数控制。
