### ISSUE TITLE
fake ip模式下无法更新订阅和geoip

### ISSUE THREAD

**Issue by snipersteve** [frainzy1477/luci-app-clash#21]
按wiki设置了fake ip，各终端上网无问题，但路由器本身无法更新订阅和geoip了，貌似把fake ip当真实ip在连接。

**Comment by frainzy1477** [comment]
> 按wiki设置了fake ip，各终端上网无问题，但路由器本身无法更新订阅和geoip了，貌似把fake ip当真实ip在连接。

知道了， 有空研究能不能修

**Comment by frainzy1477** [comment]
> 按wiki设置了fake ip，各终端上网无问题，但路由器本身无法更新订阅和geoip了，貌似把fake ip当真实ip在连接。

用fake-ip不要开DNS转发
