### ISSUE TITLE
dns问题

### ISSUE THREAD

**Issue by zcracker** [frainzy1477/luci-app-clash#215]
刚刚编译了test分支的最新代码，选择不启用dns，启用自定义dns后，fake-ip模式，还是无法命中规则，而luci-app-clash程序dns将规则里的地址转换成ip地址，直接ip链接，导致链接超时

**Comment by zcracker** [comment]
1.6.4好像还没修复

**Comment by frainzy1477** [comment]
> 1.6.4好像还没修复

没有问题，可能你的OP问题

**Comment by zcracker** [comment]
我是19.07.2，我明天再试试

**Comment by zcracker** [comment]
经过观察，不启用dns日志显示，域名被转换为ip地址，配置文件最后的规则为
- GEOIP,CN,DIRECT
- MATCH,Proxy

time="2020-03-31T01:16:14Z" level=info msg="[TCP] 10.0.0.208:54096 --> 172.217.27.129 match Match using Proxy[Osaka]"
time="2020-03-31T01:16:16Z" level=info msg="[TCP] 10.0.0.208:54097 --> 69.171.235.101 match Match using Proxy[Osaka]"
time="2020-03-31T01:16:16Z" level=info msg="[TCP] 10.0.0.208:54098 --> 69.171.235.101 match Match using Proxy[Osaka]"
time="2020-03-31T01:16:17Z" level=info msg="[TCP] 10.0.0.208:54099 --> 75.126.215.88 match Match using Proxy[Osaka]"
代理成功
启用dns后日志显示为，有原来不启用dns时候的ip地址变为域名，配置文件最后的规则为
- GEOIP,CN,DIRECT
- MATCH,Proxy
time="2020-03-31T01:19:08Z" level=info msg="[TCP] 10.0.0.208:54239 --> fonts.gstatic.com match DomainSuffix using Proxy[Osaka]"
time="2020-03-31T01:19:08Z" level=info msg="[TCP] 10.0.0.208:54238 --> i.ytimg.com match DomainSuffix using Proxy[Osaka]"
time="2020-03-31T01:19:09Z" level=info msg="[TCP] 10.0.0.208:54240 --> lh3.googleusercontent.com match DomainSuffix using Proxy[Osaka]"
如果我仅想代理规则中的网址，剩下的全部直连，最后的规则改为如下，那么就会造成规则中的域名被转换为ip直接直连，导致链接失败
- DOMAIN-SUFFIX,google.com,Proxy
- DOMAIN-SUFFIX,googlevideo.com,Proxy
- DOMAIN-SUFFIX,google.co.jp,Proxy
- DOMAIN-SUFFIX,google.com.hk,Proxy
- DOMAIN-SUFFIX,google.de,Proxy
- GEOIP,CN,DIRECT
- MATCH,DIRECT

**Comment by zcracker** [comment]
这个问题还请大佬修复以下，
![image](https://user-images.githubusercontent.com/9046704/77990784-d36ffb80-7354-11ea-9af9-fe4acabfb0f6.png)

**Comment by frainzy1477** [comment]
你要匹配域名规则必须开dns转发
