### ISSUE TITLE
支持trojan吗？

### ISSUE THREAD

**Issue by muziling** [frainzy1477/luci-app-clash#216]
Dreamacro 最近新增了 trojan 的支持，我看core download下载地址还是19年的，
不知道luci下拉选项有新增了 trojan的支持不

**Comment by frainzy1477** [comment]
> Dreamacro 最近新增了 trojan 的支持，我看core download下载地址还是19年的，
> 不知道luci下拉选项有新增了 trojan的支持不

支持
