### ISSUE TITLE
同一配置文件 1.6.4无法正常启动 日志提示未找到[节点]

### ISSUE THREAD

**Issue by Mosney** [frainzy1477/luci-app-clash#218]
此[节点]在配置文件的`proxy`段处于中后段位置。
卸载1.6.4之后重新安装1.6.3恢复正常。
luci界面几乎所有的功能都处于关闭状态，自始至终仅使用同一个完整的配置文件。

**Comment by frainzy1477** [comment]
> 此[节点]在配置文件的`proxy`段处于中后段位置。
> 卸载1.6.4之后重新安装1.6.3恢复正常。
> luci界面几乎所有的功能都处于关闭状态，自始至终仅使用同一个完整的配置文件。

我试试了很多次，没看到你说的问题你要看看你的.yaml吧

**Comment by Mosney** [comment]
> 我试试了很多次，没看到你说的问题你要看看你的.yaml吧

好吧我再排查一下，主要是之前的版本和clash直接运行这个配置文件都没问题，有时间我测试一下你改动的部分

**Comment by Mosney** [comment]
更换了最新的0.19.0版本的clash核心之后没问题了
估计是因为启动脚本生成配置文件采用了新格式，而我还在用了0.18.0版本的clash
下次可以在release页标注一下兼容的clash核心版本要求
