### ISSUE TITLE
低版本luci-app-clash搭配新内核

### ISSUE THREAD

**Issue by Synchronized1** [frainzy1477/luci-app-clash#221]
frainzy大佬,环境:1.6.4+0.19.0.1,
一.在移除或者直接在页面修个某个配置的时候,会一直等待响应,然后卡死
   导致LEDE主页:192.168.1.1都无法访问!
![image](https://user-images.githubusercontent.com/58451554/77908177-94db3200-72bd-11ea-9386-67afa97b9092.png)
![image](https://user-images.githubusercontent.com/58451554/77908210-a1f82100-72bd-11ea-85dd-65d76a0fc9ff.png)

二.还有一个问题,大佬如果我使用这个搭配,会不会有兼容性问题? 
![image](https://user-images.githubusercontent.com/58451554/77905594-19778180-72b9-11ea-984e-5bbe61db3ce6.png)

**Comment by frainzy1477** [comment]
启动客户端把你的config.yaml的屏幕截图出来

这一样
![image](https://user-images.githubusercontent.com/49537471/77923713-65382400-72d5-11ea-8636-82973f6a2772.png)

![image](https://user-images.githubusercontent.com/49537471/77923853-96185900-72d5-11ea-8a3c-9e3bc53fc585.png)

**Comment by Synchronized1** [comment]
![image](https://user-images.githubusercontent.com/58451554/78017425-daabff00-737e-11ea-9080-d143ef8789f6.png)


> 启动客户端把你的config.yaml的屏幕截图出来
> 
> 这一样
> ![image](https://user-images.githubusercontent.com/49537471/77923713-65382400-72d5-11ea-8636-82973f6a2772.png)
> 
> ![image](https://user-images.githubusercontent.com/49537471/77924352-2bb3e880-72d6-11ea-864b-d873878e5edd.png)

**Comment by Synchronized1** [comment]
大佬过目:
![image](https://user-images.githubusercontent.com/58451554/78017570-0c24ca80-737f-11ea-8ecf-8928d4e407fa.png)
