### ISSUE TITLE
请大佬修复DNS bug

### ISSUE THREAD

**Issue by zcracker** [frainzy1477/luci-app-clash#226]
经过观察，不启用dns日志显示，域名被转换为ip地址，配置文件最后的规则为，其实有最后的- MATCH,Proxy兜底规则生效，代理正常，代理规则并没有命中

GEOIP,CN,DIRECT
MATCH,Proxy
time="2020-03-31T01:16:14Z" level=info msg="[TCP] 10.0.0.208:54096 --> 172.217.27.129 match Match using Proxy[Osaka]"
time="2020-03-31T01:16:16Z" level=info msg="[TCP] 10.0.0.208:54097 --> 69.171.235.101 match Match using Proxy[Osaka]"
time="2020-03-31T01:16:16Z" level=info msg="[TCP] 10.0.0.208:54098 --> 69.171.235.101 match Match using Proxy[Osaka]"
time="2020-03-31T01:16:17Z" level=info msg="[TCP] 10.0.0.208:54099 --> 75.126.215.88 match Match using Proxy[Osaka]"

启用dns后日志显示为，ip地址变为域名，规则正确命中域名，配置文件最后的规则为

GEOIP,CN,DIRECT
MATCH,Proxy
time="2020-03-31T01:19:08Z" level=info msg="[TCP] 10.0.0.208:54239 --> fonts.gstatic.com match DomainSuffix using Proxy[Osaka]"
time="2020-03-31T01:19:08Z" level=info msg="[TCP] 10.0.0.208:54238 --> i.ytimg.com match DomainSuffix using Proxy[Osaka]"
time="2020-03-31T01:19:09Z" level=info msg="[TCP] 10.0.0.208:54240 --> lh3.googleusercontent.com match DomainSuffix using Proxy[Osaka]"

如果我仅想代理规则中的网址，不想启用dns转发，剩下的全部直连，最后的规则改为如下，那么就会造成规则中的域名被转换为ip直接直连，导致链接失败，经测试，1.4.1之前的版本使用以下规则是正常的，1.4.1之后最后的兜底规则- MATCH,DIRECT这样写就会链接失败

DOMAIN-SUFFIX,google.com,Proxy
DOMAIN-SUFFIX,googlevideo.com,Proxy
DOMAIN-SUFFIX,google.co.jp,Proxy
DOMAIN-SUFFIX,google.com.hk,Proxy
DOMAIN-SUFFIX,google.de,Proxy
GEOIP,CN,DIRECT
MATCH,DIRECT

**Comment by Scorpion4286** [comment]
首先，你要明白clash中的DNS都干了什么：
推荐你读一下F大的[这条](https://github.com/Fndroid/clash_for_windows_pkg/wiki/DNS%E6%B1%A1%E6%9F%93%E5%AF%B9Clash%EF%BC%88for-Windows%EF%BC%89%E7%9A%84%E5%BD%B1%E5%93%8D)Wiki 

其中：
在路由器或虚拟机中使用Clash做透明代理时，**需要使用Clash内置的DNS服务器进行解析，DNS服务器会生成IP和域名的关系，从而在Clash端反推对应的域名**（因为redir只能传递IP）。

所以根据你的需求，我没理解为啥要关掉DNS转发。

**Comment by zcracker** [comment]
> 首先，你要明白clash中的DNS都干了什么：
> 推荐你读一下F大的[这条](https://github.com/Fndroid/clash_for_windows_pkg/wiki/DNS%E6%B1%A1%E6%9F%93%E5%AF%B9Clash%EF%BC%88for-Windows%EF%BC%89%E7%9A%84%E5%BD%B1%E5%93%8D)Wiki
> 
> 其中：
> 在路由器或虚拟机中使用Clash做透明代理时，**需要使用Clash内置的DNS服务器进行解析，DNS服务器会生成IP和域名的关系，从而在Clash端反推对应的域名**（因为redir只能传递IP）。
> 
> 所以根据你的需求，我没理解为啥要关掉DNS转发。

首先我路由器用的fake-ip模式 ，不启用dns转发的时候，clash dns没有命中规则

**Comment by Scorpion4286** [comment]
fake-ip?你上面贴的log里可都是realip哎。
要是不把DNS请求交给clash处理，你怎么可能拿得到fake-ip呢？

**Comment by isslayne** [comment]
> > 首先，你要明白clash中的DNS都干了什么：
> > 推荐你读一下F大的[这条](https://github.com/Fndroid/clash_for_windows_pkg/wiki/DNS%E6%B1%A1%E6%9F%93%E5%AF%B9Clash%EF%BC%88for-Windows%EF%BC%89%E7%9A%84%E5%BD%B1%E5%93%8D)Wiki
> > 其中：
> > 在路由器或虚拟机中使用Clash做透明代理时，**需要使用Clash内置的DNS服务器进行解析，DNS服务器会生成IP和域名的关系，从而在Clash端反推对应的域名**（因为redir只能传递IP）。
> > 所以根据你的需求，我没理解为啥要关掉DNS转发。
> 
> 首先我路由器用的fake-ip模式 ，不启用dns转发的时候，clash dns没有命中规则

和你一样的问题现象

**Comment by frainzy1477** [comment]
你要匹配域名规则必须开dns转发
