### ISSUE TITLE
有关订阅内容自动更新的问题

### ISSUE THREAD

**Issue by khking** [frainzy1477/luci-app-clash#228]
经过自己测试发现，订阅的URL已经好久没有自动更新了，在设置里面设置为一小时更新一次。但是查看日志每小时会重启客户端但是并不会自动去更新订阅内容。现在只能手动更新。

**Comment by isping** [comment]
同样问题，升级后订阅的URL不能自动下载保存。只能手动更新了。

**Comment by frainzy1477** [comment]
修了

**Comment by khking** [comment]
我升级了最新1.6.8但是查看日志还是不会自动更新。

**Comment by frainzy1477** [comment]
> 我升级了最新1.6.8但是查看日志还是不会自动更新。

仅在客户端运行时更新

**Comment by isping** [comment]
貌似还有问题，还是只能手动更新配置文件，自动下载不行。

**Comment by frainzy1477** [comment]
> 貌似还有问题，还是只能手动更新配置文件，自动下载不行。

我自己试试多次可以了
