### ISSUE TITLE
似乎每6个小时都会把订阅文件更新成大小为0的文件

### ISSUE THREAD

**Issue by shown1985** [frainzy1477/luci-app-clash#239]
最后导致客户端停止

**Comment by shown1985** [comment]
发觉是似乎fake ip模式下更新订阅会失败，包裹geo-ip会download失败，是不是fake-ip下，这些更新都直接连接了fake-ip导致的了。如果关掉dns转发fake-ip就没事

**Comment by shown1985** [comment]
解决办法目前似乎是在clash的自定义dns里做fake ip filter 过滤掉类似download.maxmind.com这种

**Comment by TomatoFryEggs** [comment]
我重新下载了配置还是出现：你的config.yaml有问题还是为了空 0kb
