### ISSUE TITLE
无法停止客户端和日志问题

### ISSUE THREAD

**Issue by ztechie** [frainzy1477/luci-app-clash#24]
在客户端取消启动按钮，保存应用，程序依旧运行，执行kill -9 命令杀掉clash-watchdog.sh进程，程序停止，还有一个问题就是日志问题，日志虽然自动清理了，但是clash.log的体积越来越大

**Comment by ztechie** [comment]
OpenWrt 18.06.4 r7808-ef686b7292

**Comment by frainzy1477** [comment]
> 在客户端取消启动按钮，保存应用，程序依旧运行，执行kill -9 命令杀掉clash-watchdog.sh进程，程序停止，还有一个问题就是日志问题，日志虽然自动清理了，但是clash.log的体积越来越大

每个本版出来你有问题，有什么问题自己fork修改吧

**Comment by wangxin6** [comment]
/etc/init.d/cron start
/etc/init.d/cron enable

**Comment by wangxin6** [comment]
在【系统】-【计划任务】改成：
`0 0 * * * echo "" > /tmp/clash.log`

**Comment by ztechie** [comment]
我也在找问题，是不是我安装了什么，第一点启动保存，并不会启动到，会弹出日志=$(date "+%Y-%m-%d %H:%M:%S")  CLIENT IS DISABLED
在点一次报存，就启动了，正常使用，但是取消启动按钮，点保存应用，if [ $enable -eq 1 ]; then 这个值也变成0了，点几次保存也没用
start_service(){
#=========================================================================================================================== 
if pidof clash >/dev/null; then
	kill $(pidof clash) >/dev/null 2>&1 || kill -9 $(ps | grep clash | grep -v grep | awk '{print $1}') >/dev/null 2>&1
fi
enable=$(uci get clash.config.enable 2>/dev/null)
yml_yaml
size=$(ls -l /etc/clash/config.yaml|awk '{print $5}')
lan=$(uci get clash.config.proxylan 2>/dev/null)
lanac=$(uci get clash.config.rejectlan 2>/dev/null)

if [ $enable -eq 1 ]; then

if [ $size -ne 0 ]; then

	
	if [ $lan ]; then
		access >/dev/null 2>&1
	fi

	if [ $lanac ]; then
		reject_access >/dev/null 2>&1
	fi

   	yml_change

	yml_dns_change
	
        nohup $CLASH -d "$CLASH_CONFIG" > /tmp/clash.log 2>&1 &	
	  
	ln -s /usr/share/clash/web /www/clash
			
	uci set firewall.@defaults[0].flow_offloading=1
	uci commit firewall	
	/etc/init.d/firewall restart >/dev/null 2>&1
		
	rules >/dev/null 2>&1
	
	killall -1 dnsmasq
	
	/etc/init.d/dnsmasq restart >/dev/null 2>&1

	
	if pidof clash >/dev/null; then
		add_cron
		nohup /usr/share/clash/clash-watchdog.sh >/dev/null 2>&1
	
	fi
else
	echo "===============================$(date "+%Y-%m-%d %H:%M:%S")  problem with config.yaml,  config.yaml is either empty or not found =====================================" >> /tmp/clash.log


fi

else
	echo "===============================$(date "+%Y-%m-%d %H:%M:%S")  CLIENT IS DISABLED =====================================" >> /tmp/clash.log
fi

不知道是这里那里的判断不满足

**Comment by wangxin6** [comment]
`日志问题，日志虽然自动清理了，但是clash.log的体积越来越大`

--同样的问题。文件内容是清理了，但是文件体积（磁盘大小）在增大。
