### ISSUE TITLE
无法启动客户端

### ISSUE THREAD

**Issue by zhangeden** [frainzy1477/luci-app-clash#240]
装在LEDE软路由里面，koolshare的版本

因为软件库里面没有安装模式，我用ssh安装在服务里面
但启动后发现无法运行
提示：
客户端 | 末运行
Clash模式 | 末运行
Clash配置类型 | 末运行
Clash控制面板 | 末运行

内核是clashrV 0.19.0.2

![TIM截图20200411205010](https://user-images.githubusercontent.com/59479806/79044166-335c8100-7c36-11ea-8b39-c36c7eb069b3.png)

**Comment by shown1985** [comment]
启动的代理类型和你的clash 核心是否匹配，如果你启动的是ssr的梯子，但使用的又不是clashr核心，就会这样

**Comment by EXGDT** [comment]
一样，所有clash核心都是最新的，vmess，各种核心都显示无法启动客户端，日志没有任何显示。

**Comment by EXGDT** [comment]
> 一样，所有clash核心都是最新的，vmess，各种核心都显示无法启动客户端，日志没有任何显示。

在系统日志中会有如下提示
daemon.err uhttpd[3449]: egrep: /etc/clash/config.yaml: No such file or directory
将配置文件拷贝到/etc/clash下并重命名为config.yaml，系统日志该提示消失但是clash依然全部未运行。

**Comment by xuhuanxxx** [comment]
> > 一样，所有clash核心都是最新的，vmess，各种核心都显示无法启动客户端，日志没有任何显示。
> 
> 在系统日志中会有如下提示
> daemon.err uhttpd[3449]: egrep: /etc/clash/config.yaml: No such file or directory
> 将配置文件拷贝到/etc/clash下并重命名为config.yaml，系统日志该提示消失但是clash依然全部未运行。

可能是因为配置文件在clash尝试启动时被删掉了，官方源码openwrt固件存在这种现象。

**Comment by wangfeng35** [comment]
> > > 一样，所有clash核心都是最新的，vmess，各种核心都显示无法启动客户端，日志没有任何显示。
> > 
> > 
> > 在系统日志中会有如下提示
> > daemon.err uhttpd[3449]: egrep: /etc/clash/config.yaml: No such file or directory
> > 将配置文件拷贝到/etc/clash下并重命名为config.yaml，系统日志该提示消失但是clash依然全部未运行。
> 
> 可能是因为配置文件在clash尝试启动时被删掉了，官方源码openwrt固件存在这种现象。

这个问题没法解决么？
