### ISSUE TITLE
启用自定义规则后客户端启动失败

### ISSUE THREAD

**Issue by XinSSS** [frainzy1477/luci-app-clash#242]
log：time="2020-04-17T16:11:34Z" level=fatal msg="Parse config error: yaml: line 1630: did not find expected key"

![20200418_001647](https://user-images.githubusercontent.com/30732527/79590693-fd257280-8109-11ea-93f4-4bfce95cad9e.jpg)

**Comment by W1nd** [comment]
遇到了相同的问题，关闭就可以启动

**Comment by frainzy1477** [comment]
修了
