### ISSUE TITLE
你的config.yaml有问题还是为了空 0kb

### ISSUE THREAD

**Issue by TomatoFryEggs** [frainzy1477/luci-app-clash#246]
本来好好的，早上醒来就出现：你的config.yaml有问题还是为了空 0kb；
然后启动就一直出现：你的config.yaml有问题还是为了空 0kb。
无法启动 了。
重新下载了配置，并使用了配置，且不为空，依然无法启动，日志出现上述错误。

**Comment by taken7** [comment]
这个bug看来挺普遍的

**Comment by actg** [comment]
非常普遍，莫名其妙就出现0Kb，已经关闭了自动更新

**Comment by Humorize** [comment]
调试Clash的配置文件更新脚本
> `/usr/share/clash/update_all.sh`

发现执行
> `wget --no-check-certificate --user-agent="Clash/OpenWRT" $url -O 2>&1 >1 $CONFIG_YAML`

时报错，报错内容是

> `Unable to establish SSL connection.`

我的配置文件订阅链接是HTTPS的，于是尝试删掉上面的wget命令的

> `--no-check-certificate`

参数，重新执行这个脚本，完美地更新了配置文件。你也可以试试看
