### ISSUE TITLE
OpenWRT 19.07缺少依赖

### ISSUE THREAD

**Issue by zh2209645** [frainzy1477/luci-app-clash#248]
Version: OpenWRT 19.07 Stable
Hardware: Xiaomi Mi Router 3G
仅安装Readme中显示依赖会提示"module 'luci.cbi' not found"
安装 luci-compat可解决

**Comment by m4niacjp** [comment]
SSH into router and then type

```
opkg update
opkg install luci-compat
```

This will fix your issue.
