### ISSUE TITLE
Openwrt Snapshot - 

### ISSUE THREAD

**Issue by m4niacjp** [frainzy1477/luci-app-clash#249]
In Snapshot Openwrt since you didn't register in the repository can't access the LUCI interface with error: Insufficient permissions to read UCI configuration

**Comment by xuhuanxxx** [comment]
在/usr/share/rpcd/acl.d新建一个名为luci-app-clash.json的文件，
文件内容如下：
```
{
	"luci-app-clash": {
		"description": "Grant UCI access for luci-app-clash",
		"read": {
			"uci": [ "clash" ]
		},
		"write": {
			"uci": [ "clash" ]
		}
	}
}
```
赋予0644权限
重启rpcd

![image](https://user-images.githubusercontent.com/4946617/80296708-d2918480-87af-11ea-859e-eff3ca9e1a2d.png)
