### ISSUE TITLE
无限 正在检查...

### ISSUE THREAD

**Issue by cmd2001** [frainzy1477/luci-app-clash#252]
路由器型号为newifi3，openwrt版本为Powered by LuCI openwrt-19.07 branch (git-20.115.52331-39a8290) / OpenWrt 19.07.2 r10947-65030d81f3
手动安装clash(dtun) linux-mips-softfloat后，已安装版本始终卡在 正在检查...。

**Comment by actg** [comment]
我也遇到类似问题，无限显示，正在检查...
另外，clashr启动不了，郁闷

**Comment by cmd2001** [comment]
> 我也遇到类似问题，无限显示，正在检查...
> 另外，clashr启动不了，郁闷

其实手动sftp上传clash内核并chmod+x就可以了。上传目录自己找一下。
