### ISSUE TITLE
小调查，你们都是x86_64 OP么

### ISSUE THREAD

**Issue by ztechie** [frainzy1477/luci-app-clash#26]
我把程序弄到WNDR4300  linksys1900acs  /etc/init.d/clash 无其他无问题，仅存在程序无法停止的问题

**Comment by wangxin6** [comment]
如何知道程序没有停止？

**Comment by ztechie** [comment]
![image](https://user-images.githubusercontent.com/9046704/61622993-73469700-aca8-11e9-8a75-9fbe7b1399cd.png)
![image](https://user-images.githubusercontent.com/9046704/61623013-8194b300-aca8-11e9-95c1-87280b3d8e77.png)
![image](https://user-images.githubusercontent.com/9046704/61623055-8fe2cf00-aca8-11e9-8d4b-5fc391e7fb93.png)
![image](https://user-images.githubusercontent.com/9046704/61623102-a4bf6280-aca8-11e9-958f-311f4dfa0422.png)
另外日志也在不断刷新

**Comment by ztechie** [comment]
第一次选启动，点保存应用，会弹出$(date "+%Y-%m-%d %H:%M:%S")  CLIENT IS DISABLED 程序未启动，在点保存应用，程序就启动了，正常使用

**Comment by frainzy1477** [comment]
> 第一次选启动，点保存应用，会弹出$(date "+%Y-%m-%d %H:%M:%S") CLIENT IS DISABLED 程序未启动，在点保存应用，程序就启动了，正常使用

你先重新启动路由器看看

**Comment by ztechie** [comment]
如果取消启动按钮，重启后程序显示CLIENT IS DISABLED

**Comment by ztechie** [comment]
frainzy1477谢谢你的付出，clash的shell我也看了没找出问题在哪，水平有限，如果你需要4300测试的话我可以免费寄给你，手头多余的一台

**Comment by ztechie** [comment]
frainzy1477你好 ，或者你提供个邮箱，我发我路由器的ssh ip 账号密码给你

**Comment by frainzy1477** [comment]
> 如果取消启动按钮，重启后程序显示CLIENT IS DISABLED

openclash 也有这个问题？

**Comment by frainzy1477** [comment]
运行中， watchdog.sh和 restart 仅执行1个流程但看你的有多了流程
![Screenshot_12](https://user-images.githubusercontent.com/49537471/61685210-8f9d0f00-ad4e-11e9-979b-fcbac2daa374.png)

**Comment by frainzy1477** [comment]
运行中， watchdog.sh和 restart 仅执行1个流程但看你的有多了流程
![Screenshot_12](https://user-images.githubusercontent.com/49537471/61685350-0cc88400-ad4f-11e9-8dfd-cd1ac6eb4397.png)

**Comment by frainzy1477** [comment]
未运行
![Screenshot_1](https://user-images.githubusercontent.com/49537471/61685508-8b252600-ad4f-11e9-8996-ee8d870167dd.png)

**Comment by frainzy1477** [comment]
我用是x86_64
![Screenshot_2](https://user-images.githubusercontent.com/49537471/61685720-2c13e100-ad50-11e9-9869-63900ba86bf0.png)

**Comment by frainzy1477** [comment]
> 我用是x86_64
> ![Screenshot_2](https://user-images.githubusercontent.com/49537471/61685720-2c13e100-ad50-11e9-9869-63900ba86bf0.png)

有新3，也没有问题

**Comment by ztechie** [comment]
![image](https://user-images.githubusercontent.com/9046704/61689022-07703700-ad59-11e9-9c29-f9a89d88cc8f.png)
正常运行图

**Comment by ztechie** [comment]
![image](https://user-images.githubusercontent.com/9046704/61689252-6c2b9180-ad59-11e9-9695-96dca19bbb6f.png)
运行一阵后就这么多，也不影响正常上网

**Comment by ztechie** [comment]
openclash 未尝试，比较喜欢您的这个UI和功能

**Comment by ztechie** [comment]
![image](https://user-images.githubusercontent.com/9046704/61689970-d2fd7a80-ad5a-11e9-9e25-b21b8b0f4ccb.png)
取消启动按钮的候选，点保存，进程如下，我点了2次保存

**Comment by ztechie** [comment]
![image](https://user-images.githubusercontent.com/9046704/61691979-5ae58380-ad5f-11e9-918f-5f267c8eec1d.png)
程序还在正常运行，进程如下

**Comment by ztechie** [comment]
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: warning
external-controller: 0.0.0.0:9191
experimental:
ignore-resolve-fail: true
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5300
  enhanced-mode: fake-ip
  nameserver:
  - tls://dns.rubyfish.cn:853
  - 1.2.4.8
  - 101.6.6.6
  - 117.50.10.10
  - 223.5.5.5
  - https://1.1.1.1/dns-query
#  fallback:
#  - tls://dns.rubyfish.cn:853
#  - tls://dns.google:853
#  - tls://1.1.1.1:853
#  - tls://1.0.0.1:853

yaml配置如下

**Comment by ztechie** [comment]
please change admin/services/clash/log to use the form() action instead.第一次执行启动，系统日志显示

**Comment by ztechie** [comment]
> please change admin/services/clash/log to use the form() action instead.第一次执行启动，系统日志显示

Model clash/overview returns SimpleForm but is dispatched via cbi()
