### ISSUE TITLE
1.6.9b导致luci页面崩溃

### ISSUE THREAD

**Issue by sunuo1997** [frainzy1477/luci-app-clash#260]
/usr/lib/lua/luci/controller/clash.lua:15: attempt to index global 'page' (a nil value)
stack traceback:
	/usr/lib/lua/luci/controller/clash.lua:15: in function 't'
	/usr/lib/lua/luci/dispatcher.lua:465: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:188: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

**Comment by VanDeAnna** [comment]
我也是这个问题，安装之后登录路由显示上面的错误，卸载luci-app-clash后正常


OpenWrt R20.4.8 
LuCI Master (git-20.117.60969-420c61a)
Kernel Version 4.19.115

**Comment by jarryyen** [comment]
我也是这样....

**Comment by canflyx** [comment]
me too

**Comment by sheiy** [comment]
/usr/lib/lua/luci/controller/clash.lua:15: attempt to index global 'page' (a nil value)
stack traceback:
	/usr/lib/lua/luci/controller/clash.lua:15: in function 'v'
	/usr/lib/lua/luci/dispatcher.lua:1201: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:694: in function 'menu_json'
	/usr/lib/lua/luci/dispatcher.lua:795: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:478: in function </usr/lib/lua/luci/dispatcher.lua:477>

**Comment by jarryyen** [comment]
我用上一个版本就好了,不用最新版

**Comment by frainzy1477** [comment]
这星期会修了
