### ISSUE TITLE
不能使用更新配置功能

### ISSUE THREAD

**Issue by isping** [frainzy1477/luci-app-clash#266]
在**Subscription Config**页面，配置好clash下载链接，点击Download Config后显示开始下载配置文件，但最后检查Config页面并没有更新。 想检查错误，不知道应该在哪里查看更新的日志？

**Comment by frainzy1477** [comment]
1.7.1

**Comment by isping** [comment]
问题依旧，早期版本是可以更新成功的，最近的几个版本都不行了，只能手动上传更新。

**Comment by frainzy1477** [comment]
> 问题依旧，早期版本是可以更新成功的，最近的几个版本都不行了，只能手动上传更新。

我也在用没有问题，就自动更新有点问题

**Comment by frainzy1477** [comment]
更新了
