### ISSUE TITLE
原版openwrt19.07.3系统的luci界面找不到clash

### ISSUE THREAD

**Issue by jialan22010** [frainzy1477/luci-app-clash#268]
我用官方原版的openwrt19.07.3与luci-app-clash一起编译ok，但在运行后的 luci界面找不到clash，是需要怎么设置一下吗？

**Comment by yiguihai** [comment]
我还以为只有我有这种情况

**Comment by jialan22010** [comment]
> 我还以为只有我有这种情况

但是在openwrt19.07.2上不会出现这个问题

**Comment by jialan22010** [comment]
用官方原版的openwrt19.07.3与luci-app-clash，在 luci界面可以找到clash了
