### ISSUE TITLE
config.yaml配置检查

### ISSUE THREAD

**Issue by ztechie** [frainzy1477/luci-app-clash#27]
请问你们可以正常运行或关闭的yaml配置文件如下吗
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: warning
external-controller: 0.0.0.0:9191
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5300
  enhanced-mode: fake-ip
  nameserver:
  - tls://dns.rubyfish.cn:853
  - 1.2.4.8
  - 101.6.6.6
  - 117.50.10.10
  - 223.5.5.5
  - https://1.1.1.1/dns-query
#  fallback:
#  - tls://dns.rubyfish.cn:853
#  - tls://dns.google:853
#  - tls://1.1.1.1:853
#  - tls://1.0.0.1:853

**Comment by frainzy1477** [comment]
> 请问你们可以正常运行或关闭的yaml配置文件如下吗
> port: 7890
> socks-port: 7891
> allow-lan: true
> mode: Rule
> log-level: warning
> external-controller: 0.0.0.0:9191
> dns:
> enable: true
> ipv6: false
> listen: 0.0.0.0:5300
> enhanced-mode: fake-ip
> nameserver:
> 
> * tls://dns.rubyfish.cn:853
> * 1.2.4.8
> * 101.6.6.6
> * 117.50.10.10
> * 223.5.5.5
> * https://1.1.1.1/dns-query
> 
> # fallback:
> # - tls://dns.rubyfish.cn:853
> # - tls://dns.google:853
> # - tls://1.1.1.1:853
> # - tls://1.0.0.1:853

你看看Wiki https://github.com/frainzy1477/luci-app-clash/wiki  fakeip 别用fallback

**Comment by wangxin6** [comment]
在fake-ip模式下不进行DNS解析，而是直接生成一个“假IP”并响应给客户端，再记录对应关系。

不需要担心DNS污染，因为配置文件中的DNS仅用作规则判定，所以DNS随便放一个你喜欢的就行。
