### ISSUE TITLE
luci 18.06 新版clash出错

### ISSUE THREAD

**Issue by kenzok8** [frainzy1477/luci-app-clash#286]
uci: Parse error (EOF with unterminated ') at line 385, byte 464

**Comment by frainzy1477** [comment]
> uci: Parse error (EOF with unterminated ') at line 385, byte 464

我怎么知道哪里出现？？？

**Comment by kenzok8** [comment]
openwrt-x86架构，云编译固件服务-clash-点开就此错误，卸载后用你releases发布v1.7.3.1，也是此错误

**Comment by frainzy1477** [comment]
> openwrt-x86架构，云编译固件服务-clash-点开就此错误，卸载后用你releases发布v1.7.3.1，也是此错误

我也想86没有这问题

**Comment by frainzy1477** [comment]
> uci: Parse error (EOF with unterminated ') at line 385, byte 464

https://github.com/frainzy1477/luci-app-clash/pull/288/commits/7cf6940b466bad13d5a06be3f1af48cd742a084f
