### ISSUE TITLE
config file missing 【‘】 in line 363 after 【CN】

### ISSUE THREAD

**Issue by esirplayground** [frainzy1477/luci-app-clash#287]
file location：
https://github.com/frainzy1477/luci-app-clash/blob/master/root/etc/config/clash

**Comment by frainzy1477** [comment]
> file location：
> https://github.com/frainzy1477/luci-app-clash/blob/master/root/etc/config/clash

you can just save&apply again from config->provider config page to fix the missing character

**Comment by frainzy1477** [comment]
修了
