### ISSUE TITLE
config.yam中DNS的配置

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#29]
在config.yaml中如果没有DNS的配置。比如注释以下DNS代码

`#dns:`
`# enable: true` 
`#  ipv6: false`
`#  nameserver:`
`#     - tls://dns.rubyfish.cn:853`

上传文件以后，clash无法启动

**Comment by ztechie** [comment]
sed 没找到相关配置，判断不成立，没启动吧，要标准配置模版吧

**Comment by wangxin6** [comment]
我的机场订阅没有dns。另外从标准配置模版dns也不是必须的吧？至少clashx，cfw都可以在没有dns配置情况下运行。
