### ISSUE TITLE
全新安装，一直都显示“未启动”

### ISSUE THREAD

**Issue by Kilochord** [frainzy1477/luci-app-clash#292]
全新虚拟机上安装新的Openwrt，全新安装17.3.2all.ipk。
打开之后用之前可用的规则，或者机场提供的托管衔接，都不能启动Clash
可以确定我所装的版本正确，内核已经更新至最新版，内核选择和设置上没有问题。
我虚拟机上另外一个Openwrt，装的是17.1.1能正常运行，机场托管以及自定义规则都是可用状态。

日志提示：
/etc/rc.common: line 674: nohup: not found

**Comment by Kilochord** [comment]
重新安装17.1.1完美启动，暂时不折腾更新版本了，能用就行了。

**Comment by frainzy1477** [comment]
> 重新安装17.1.1完美启动，暂时不折腾更新版本了，能用就行了。

nohup: not found 
安装coreutils-nohup
