### ISSUE TITLE
[BUG] 生成的配置文件有格式问题，不能启动

### ISSUE THREAD

**Issue by Limgmk** [frainzy1477/luci-app-clash#296]
``
![csow](https://user-images.githubusercontent.com/45861815/86084493-a48e3080-bacf-11ea-82c8-1f74e1f33717.png)
版本：1.7.3.3

**Comment by Limgmk** [comment]
没有启用自定义DNS

**Comment by Limgmk** [comment]
设置里启用自定义DNS就能用了，但是我原本的配置文件并没有错误，直接 ./clash -d . 运行是正常的

**Comment by Limgmk** [comment]
即使启用自定义DNS, 一旦取消这里的 fake-ip-filter 注释同样回出现问题
![image](https://user-images.githubusercontent.com/45861815/86085282-567a2c80-bad1-11ea-9c5f-6942f8ac51b6.png)

**Comment by frainzy1477** [comment]
更新了

**Comment by frainzy1477** [comment]
> ``
> ![csow](https://user-images.githubusercontent.com/45861815/86084493-a48e3080-bacf-11ea-82c8-1f74e1f33717.png)
> 版本：1.7.3.3

更新了
https://github.com/frainzy1477/luci-app-clash/releases/tag/v1.7.4
