### ISSUE TITLE
多机场订阅支持和配置文件切换

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#3]
是否考虑增加此功能？

**Comment by frainzy1477** [comment]
> 是否考虑增加此功能？

clash不能,一次可以使用一个配置, 你想用别的配置你可以更新机场订阅

**Comment by wangxin6** [comment]
使用是只能使用一个配置，但是可以订阅多个机场的配置，切换当前使用的配置即可。
