### ISSUE TITLE
0.30获取不了yaml

### ISSUE THREAD

**Issue by hackenfu** [frainzy1477/luci-app-clash#30]
--2019-07-28 06:58:36--  https://dler.cloud/link/（xxx）?dns=1&clash=1
Resolving dler.cloud... 104.31.76.117, 104.31.77.117, 2606:4700:30::681f:4d75, ...
Connecting to dler.cloud|104.31.76.117|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-07-28 06:58:39 ERROR 403: Forbidden.

===============================2019-07-28 06:58:39  problem with config.yaml,  config.yaml is either empty or not found =====================================
以上是0.30的日志，去看了/etc/clash，确实yaml是0kb空文件，手动下载yaml可以替换并正常使用，但一旦URL更新又不行了
--2019-07-28 07:02:22--  https://dler.cloud/link/（xxx）?dns=1&clash=1
Resolving dler.cloud... 104.31.76.117, 104.31.77.117, 2606:4700:30::681f:4c75, ...
Connecting to dler.cloud|104.31.76.117|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 56429 (55K) [application/octet-stream]
Saving to: '/etc/clash/config.yaml'

     0K .......... .....
换回0.29-2，一切正常

**Comment by ztechie** [comment]
选择服务器订阅类型,输入服务器订阅不要带https://tgbot.lbyczf.com/*?"

**Comment by hackenfu** [comment]
但是订阅网址不是我能决定的哎，无奈了

**Comment by frainzy1477** [comment]
> 但是订阅网址不是我能决定的哎，无奈了
试试

1.先停用客户端
2.服务器订阅类型 clash
3.输入服务器订阅，更新配置
4.停用用客户端

**Comment by frainzy1477** [comment]
我重新上传了,你试试吧

**Comment by hackenfu** [comment]
还是老样子，不行。
而且新的ipk安装后多了条提示：
Installing luci-app-clash (0.30.0-1) to root...
Configuring luci-app-clash.
sh: 1: unknown operand
最后一行以前安装的时候没出现过

**Comment by frainzy1477** [comment]
> 还是老样子，不行。
> 而且新的ipk安装后多了条提示：
> Installing luci-app-clash (0.30.0-1) to root...
> Configuring luci-app-clash.
> sh: 1: unknown operand
> 最后一行以前安装的时候没出现过

我重新上传了 0.30.1 ,你试试吧

**Comment by hackenfu** [comment]
0.30.1安装倒是没报错了，但是使用还是不行，跟我帖子里的报错日志一样problem with config.yaml, config.yaml is either empty or not found

**Comment by ztechie** [comment]
去掉 https:// 试试，你复制详细的日志，新版本好像不需要前面的 https://了

**Comment by ztechie** [comment]
订阅地址是否被墙，如果被墙也会下载失败

**Comment by hackenfu** [comment]
> 去掉 https:// 试试，你复制详细的日志，新版本好像不需要前面的 [https://了](https://%E4%BA%86)

--2019-07-30 16:30:55--  https://dler.cloud/link/xxx?dns=1&clash=1
Resolving dler.cloud... 104.31.76.117, 104.31.77.117, 2606:4700:30::681f:4d75, ...
Connecting to dler.cloud|104.31.76.117|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-07-30 16:30:56 ERROR 403: Forbidden.

===============================2019-07-30 16:30:56  problem with config.yaml,  config.yaml is either empty or not found =====================================

URL transformed to HTTPS due to an HSTS policy
--2019-07-30 16:32:52--  https://dler.cloud/link/xxx?dns=1&clash=1
Resolving dler.cloud... 104.31.77.117, 104.31.76.117, 2606:4700:30::681f:4c75, ...
Connecting to dler.cloud|104.31.77.117|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-07-30 16:32:53 ERROR 403: Forbidden.

===============================2019-07-30 16:32:53  problem with config.yaml,  config.yaml is either empty or not found =====================================
加不加https似乎没区别

**Comment by hackenfu** [comment]
> 订阅地址是否被墙，如果被墙也会下载失败

从日志上看应该是没被墙的，而且0.29一直用得很好。我猜测是不是0.30之后加了什么东西，然后让服务器识别到，拒绝让你下载了。我不懂这种，乱猜的

**Comment by frainzy1477** [comment]
> > 订阅地址是否被墙，如果被墙也会下载失败
> 
> 从日志上看应该是没被墙的，而且0.29一直用得很好。我猜测是不是0.30之后加了什么东西，然后让服务器识别到，拒绝让你下载了。我不懂这种，乱猜的

你的服务器订阅问题
 你没有看 403: Forbidden ？？， luci没有问题

**Comment by frainzy1477** [comment]
![image](https://user-images.githubusercontent.com/49537471/62119169-90571780-b2f1-11e9-95ce-04c827a2e2bd.png)
 
出现ERROR 403: Forbidden那是你的服务器订阅问题，这意思是下载config.yml/yaml 不了，如果启动客户端会看到(config.yml/yaml找不到还是 0kb）===============================2019-07-30 16:30:56 problem with config.yaml, config.yaml is either empty or not found =====================================。

**Comment by frainzy1477** [comment]
您尝试使用浏览器从链接下载config.yaml, 也会出现403: Forbidden 你的服务器订阅问题

**Comment by hackenfu** [comment]
不好意思，昨晚回家晚了，没测试
早上又测试了下：
1、在卸载clash和luci-clash的情况下，浏览器可以正常下载这个URL的yaml文件；所以不需要翻墙
2、重装clash和luci0.30.1，--2019-07-31 06:56:56--  https://dler.cloud/link/xxx?dns=1&clash=1
Resolving dler.cloud... 104.31.76.117, 104.31.77.117, 2606:4700:30::681f:4c75, ...
Connecting to dler.cloud|104.31.76.117|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-07-31 06:56:57 ERROR 403: Forbidden.

===============================2019-07-31 06:56:57  problem with config.yaml,  config.yaml is either empty or not found =====================================
3、卸载luci0.30.1，重装0.29.2，--2019-07-31 07:01:05--  https://dler.cloud/link/xxx?dns=1&clash=1
Resolving dler.cloud... 104.31.77.117, 104.31.76.117, 2606:4700:30::681f:4c75, ...
Connecting to dler.cloud|104.31.77.117|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 56959 (56K) [application/octet-stream]
Saving to: '/etc/clash/config.yaml'

     0K .......... .......... .......... ....
4、卸载luci0.29.2，重装回0.30.1，--2019-07-31 07:03:22--  https://dler.cloud/link/xxx?dns=1&clash=1
Resolving dler.cloud... 104.31.76.117, 104.31.77.117, 2606:4700:30::681f:4c75, ...
Connecting to dler.cloud|104.31.76.117|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-07-31 07:03:24 ERROR 403: Forbidden.

===============================2019-07-31 07:03:24  problem with config.yaml,  config.yaml is either empty or not found =====================================
5、步骤1-4之间，没有进行其他任何活动

**Comment by hackenfu** [comment]
6、补充一下：原来步骤3生成的56kb的yaml，到步骤4安装后还在，但是url更新之后除了日志显示的错误外，yaml也变成0kb了（文件是一直在的）
所以我一直纳闷，为什么同一个机场url，0.29.2就可以，0.30.1（包括之前的0.30.0）就不行呢
