### ISSUE TITLE
访问控制，不走代理的列表问题

### ISSUE THREAD

**Issue by ztechie** [frainzy1477/luci-app-clash#31]
经测试访问控制，不走代理的列表问题，启动这选项后发现，QQ微信可以使用，浏览器无法访问任何网页，局域网有台NAS 经常下载，不想走代理
root@OpenWrt:/tmp# ipset list
Name: clash_lan
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 372
References: 1
Members:
10.0.0.207

root@OpenWrt:/tmp# iptables -L -t  nat
Chain clash_tcp (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             0.0.0.0/8           
RETURN     all  --  anywhere             10.0.0.0/8          
RETURN     all  --  anywhere             127.0.0.0/8         
RETURN     all  --  anywhere             169.254.0.0/16      
RETURN     all  --  anywhere             172.16.0.0/12       
RETURN     all  --  anywhere             192.168.0.0/16      
RETURN     all  --  anywhere             base-address.mcast.net/4 
RETURN     all  --  anywhere             240.0.0.0/4         
RETURN     all  --  anywhere             OpenWrt.lan         
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
RETURN     tcp  --  anywhere             anywhere             match-set clash_lan src
REDIRECT   tcp  --  anywhere             anywhere             redir ports 7892

Chain clash_udp (1 references)
target     prot opt source               destination         
REDIRECT   udp  --  anywhere             anywhere             redir ports 5300

**Comment by ztechie** [comment]
Last login: Tue Jul 30 12:18:01 on console
MacBook Pro:~ Zcracker$ nslookup www.baidu.com
Server:  10.0.0.1
Address: 10.0.0.1#53

Non-authoritative answer:
Name: www.baidu.com
Address: 198.18.0.88

MacBook Pro:~ Zcracker$ ping www.baidu.com
PING www.baidu.com (198.18.0.88): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6
Request timeout for icmp_seq 7

**Comment by frainzy1477** [comment]
> Last login: Tue Jul 30 12:18:01 on console
> MacBook Pro:~ Zcracker$ nslookup [www.baidu.com](http://www.baidu.com)
> Server: 10.0.0.1
> Address: 10.0.0.1#53
> 
> Non-authoritative answer:
> Name: [www.baidu.com](http://www.baidu.com)
> Address: 198.18.0.88
> 
> MacBook Pro:~ Zcracker$ ping [www.baidu.com](http://www.baidu.com)
> PING [www.baidu.com](http://www.baidu.com) (198.18.0.88): 56 data bytes
> Request timeout for icmp_seq 0
> Request timeout for icmp_seq 1
> Request timeout for icmp_seq 2
> Request timeout for icmp_seq 3
> Request timeout for icmp_seq 4
> Request timeout for icmp_seq 5
> Request timeout for icmp_seq 6
> Request timeout for icmp_seq 7

fake-ip 不支持不走代理

**Comment by frainzy1477** [comment]
有空修问题

**Comment by ztechie** [comment]
> > Last login: Tue Jul 30 12:18:01 on console
> > MacBook Pro:~ Zcracker$ nslookup [www.baidu.com](http://www.baidu.com)
> > Server: 10.0.0.1
> > Address: 10.0.0.1#53
> > Non-authoritative answer:
> > Name: [www.baidu.com](http://www.baidu.com)
> > Address: 198.18.0.88
> > MacBook Pro:~ Zcracker$ ping [www.baidu.com](http://www.baidu.com)
> > PING [www.baidu.com](http://www.baidu.com) (198.18.0.88): 56 data bytes
> > Request timeout for icmp_seq 0
> > Request timeout for icmp_seq 1
> > Request timeout for icmp_seq 2
> > Request timeout for icmp_seq 3
> > Request timeout for icmp_seq 4
> > Request timeout for icmp_seq 5
> > Request timeout for icmp_seq 6
> > Request timeout for icmp_seq 7
> 
> fake-ip 不支持不走代理

这个是设置的不走代理的IP列表，应该是默认直连啊

**Comment by frainzy1477** [comment]
> 这个是设置的不走代理的IP列表，应该是默认直连啊

redir-host 可以，fake-ip不会
