### ISSUE TITLE
DNS not Working

### ISSUE THREAD

**Issue by Krazysdaki** [frainzy1477/luci-app-clash#311]
Ver: 1.7.5.3
I enabled Clash DNS and set port to `1053`, but it seems not working at all.
```  
root@OpenWrt:~# dig qq.com @127.0.0.1:1053
dig: couldn't get address for '127.0.0.1:1053': failure
```
My config file:  
```  

config clash 'config'
	option redir_port '7892'
	option http_port '7890'
	option socks_port '7891'
	option dash_port '9090'
	option level 'info'
	option core '1'
	option allow_lan 'true'
	option bind_addr '*'
	option subcri 'clash'
	option cus_list '0'
	option custom_dns '114.114.114.114'
	option cusrule '0'
	option loadservers '1'
	option loadgroups '1'
	option auto_clear_log '1'
	option auto_update '1'
	option auto_update_time '12'
	option clear_time '12'
	option append_rules '0'
	option ping_enable '1'
	option dnscache '1'
	option culan '0'
	option ipv6 '0'
	option mode '1'
	option use_config '/usr/share/clash/config/upload/config.yaml'
	option config_type '2'
	option enable '1'
	option dcore '1'
	option download_core 'linux-386'
	option mixed_port '7893'
	option enable_ipv6 'false'
	option p_mode 'rule'
	option tun_mode '0'
	option enable_dns '1'
	option enhanced_mode 'redir-host'
	list default_nameserver '119.29.29.29'
	list default_nameserver '101.101.101.101'
	option access_control '1'
	list proxy_lan_ips '10.1.1.2'
	list proxy_lan_ips '10.1.1.3'
	list proxy_lan_ips '10.1.1.4'
	list proxy_lan_ips '10.1.1.5'
	list proxy_lan_ips '10.1.1.7'
	list proxy_lan_ips '10.1.1.13'
	option enable_udp '0'
	option interf '0'
	option listen_port '1053'
	option dnsforwader '1'

config dnsservers
	option enabled '1'
	option ser_type 'nameserver'
	option protocol 'none'
	option ser_address '119.29.29.29'

config dnsservers
	option enabled '1'
	option ser_type 'nameserver'
	option protocol 'https://'
	option ser_address 'https://doh.rixcloud.dev/dns-query'

config dnsservers
	option enabled '1'
	option ser_type 'fallback'
	option protocol 'https://'
	option ser_address 'https://dns.google/dns-query'

config dnsservers
	option enabled '1'
	option ser_type 'fallback'
	option protocol 'https://'
	option ser_address 'https://1.1.1.1/dns-query'
```  

And can you add "Custom DNS" back? Set DNS in new UI is not convenient.
Thanks for help.

**Comment by frainzy1477** [comment]
check dns if active, if not let me know
![image](https://user-images.githubusercontent.com/49537471/86332594-50c14a00-bc7d-11ea-90ce-d328d8f3b1d5.png)
![image](https://user-images.githubusercontent.com/49537471/86332680-6d5d8200-bc7d-11ea-87d3-31916af7bdf4.png)

**Comment by frainzy1477** [comment]
> Ver: 1.7.5.3
> I enabled Clash DNS and set port to `1053`, but it seems not working at all.
> 
> ```
> root@OpenWrt:~# dig qq.com @127.0.0.1:1053
> dig: couldn't get address for '127.0.0.1:1053': failure
> ```
> 
> My config file:
> 
> ```
> 
> config clash 'config'
> 	option redir_port '7892'
> 	option http_port '7890'
> 	option socks_port '7891'
> 	option dash_port '9090'
> 	option level 'info'
> 	option core '1'
> 	option allow_lan 'true'
> 	option bind_addr '*'
> 	option subcri 'clash'
> 	option cus_list '0'
> 	option custom_dns '114.114.114.114'
> 	option cusrule '0'
> 	option loadservers '1'
> 	option loadgroups '1'
> 	option auto_clear_log '1'
> 	option auto_update '1'
> 	option auto_update_time '12'
> 	option clear_time '12'
> 	option append_rules '0'
> 	option ping_enable '1'
> 	option dnscache '1'
> 	option culan '0'
> 	option ipv6 '0'
> 	option mode '1'
> 	option use_config '/usr/share/clash/config/upload/config.yaml'
> 	option config_type '2'
> 	option enable '1'
> 	option dcore '1'
> 	option download_core 'linux-386'
> 	option mixed_port '7893'
> 	option enable_ipv6 'false'
> 	option p_mode 'rule'
> 	option tun_mode '0'
> 	option enable_dns '1'
> 	option enhanced_mode 'redir-host'
> 	list default_nameserver '119.29.29.29'
> 	list default_nameserver '101.101.101.101'
> 	option access_control '1'
> 	list proxy_lan_ips '10.1.1.2'
> 	list proxy_lan_ips '10.1.1.3'
> 	list proxy_lan_ips '10.1.1.4'
> 	list proxy_lan_ips '10.1.1.5'
> 	list proxy_lan_ips '10.1.1.7'
> 	list proxy_lan_ips '10.1.1.13'
> 	option enable_udp '0'
> 	option interf '0'
> 	option listen_port '1053'
> 	option dnsforwader '1'
> 
> config dnsservers
> 	option enabled '1'
> 	option ser_type 'nameserver'
> 	option protocol 'none'
> 	option ser_address '119.29.29.29'
> 
> config dnsservers
> 	option enabled '1'
> 	option ser_type 'nameserver'
> 	option protocol 'https://'
> 	option ser_address 'https://doh.rixcloud.dev/dns-query'
> 
> config dnsservers
> 	option enabled '1'
> 	option ser_type 'fallback'
> 	option protocol 'https://'
> 	option ser_address 'https://dns.google/dns-query'
> 
> config dnsservers
> 	option enabled '1'
> 	option ser_type 'fallback'
> 	option protocol 'https://'
> 	option ser_address 'https://1.1.1.1/dns-query'
> ```
> 
> And can you add "Custom DNS" back? Set DNS in new UI is not convenient.
> Thanks for help.

i see your mistake, do not add https:// or tls:// or udp://  at ser_address , just input 1.1.1.1/dns-query , dns.google/dns-query

my dns settings
![image](https://user-images.githubusercontent.com/49537471/86334422-c75f4700-bc7f-11ea-9163-ab97dc2275da.png)

your error
![image](https://user-images.githubusercontent.com/49537471/86334206-82d3ab80-bc7f-11ea-9ccd-16eac72767d2.png)

**Comment by Krazysdaki** [comment]
Works fine after delete 'https://'.
Thanks for help.
