### ISSUE TITLE
使用最新版本和内核是Tunclash，连不上google和tw能上youtube其他。。。帮忙看下哪个问题

### ISSUE THREAD

**Issue by denel23** [frainzy1477/luci-app-clash#318]
![image](https://user-images.githubusercontent.com/31842977/86563777-93459800-bf97-11ea-9a63-4689a92836c4.png)

![image](https://user-images.githubusercontent.com/31842977/86563693-64c7bd00-bf97-11ea-99fe-d8aabd9bf929.png)
![image](https://user-images.githubusercontent.com/31842977/86563701-6abd9e00-bf97-11ea-9b81-0bb0a093fe89.png)
port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

experimental:
  ignore-resolve-fail: true
  interface-name: en0

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  default-nameserver:
    - 1.2.4.8
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
  nameserver:
    - 1.2.4.8
    - 119.29.29.29
    - 223.5.5.5
  fallback:
    - dns.adguard.com/dns-query
    - dns.rubyfish.cn/dns-query
    - cloudflare-dns.com/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

tun:
  enable: true
  stack: system # or gvisor
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - tcp://8.8.8.8:53
 
proxies:
  - name: 🇺🇸
    type: ss
    server: 
    port: 
    cipher: chacha20-ietf-poly1305
    password: 
    udp: true
  - name: 🇩🇪
    type: ss
    server: 
    port: 
    cipher: aes-256-gcm
    password: 
    udp: true

proxy-groups:
  - name: "auto"
    type: url-test
    proxies:
      - 🇺🇸
      - 🇩🇪
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: "Proxy"
    type: select
    proxies:
      - 🇺🇸
      - 🇩🇪
      - DIRECT
      - auto
      

rules:
- DOMAIN-SUFFIX,google.com,Proxy
- DOMAIN-KEYWORD,google,Proxy
- DOMAIN,google.com,Proxy
- DOMAIN-SUFFIX,ad.com,REJECT
- SRC-IP-CIDR,192.168.1.201/32,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- DST-PORT,80,DIRECT
- SRC-PORT,7777,DIRECT
- MATCH,Proxy

**Comment by denel23** [comment]
![image](https://user-images.githubusercontent.com/31842977/86563942-e7507c80-bf97-11ea-9901-1cc7a465aa36.png)
![image](https://user-images.githubusercontent.com/31842977/86563973-f46d6b80-bf97-11ea-852f-7df832d5c04e.png)

**Comment by frainzy1477** [comment]
必须开dns转发

**Comment by denel23** [comment]
还是有问题，其他软件ss正常使用怀疑是dns问题。能不能提供您的config和dns，nameserver参考一下。

**Comment by denel23** [comment]
这俩是路由器默认设置
![image](https://user-images.githubusercontent.com/31842977/86607213-92365a00-bfdb-11ea-8240-8be852e43e22.png)

<img width="471" alt="image" src="https://user-images.githubusercontent.com/31842977/86607271-a417fd00-bfdb-11ea-9102-d47341365553.png">
下面是clash dns设置是不是有误？
<img width="513" alt="image" src="https://user-images.githubusercontent.com/31842977/86607374-c01b9e80-bfdb-11ea-807b-7128a5c1751a.png">

**Comment by frainzy1477** [comment]
> 还是有问题，其他软件ss正常使用怀疑是dns问题。能不能提供您的config和dns，nameserver参考一下。

https://github.com/frainzy1477/luci-app-clash/issues/311

**Comment by denel23** [comment]
已经解决，但是在游戏规则无法下载fifa20规则文件。请提供所有游戏规则文件
