### ISSUE TITLE
/tmp/clash.log 存储空间不断增长

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#32]
文件内容很少，但是占用空间很大。

`-rw-r--r--    1 root     root       6038020 Jul 30 22:11 clash.log`

**Comment by ztechie** [comment]
最新版本好像没问题，我在观察一下

**Comment by frainzy1477** [comment]
> 文件内容很少，但是占用空间很大。
> 
> `-rw-r--r-- 1 root root 6038020 Jul 30 22:11 clash.log`

最新版本没问题
