### ISSUE TITLE
大雕的这个稳定源码https://github.com/coolsnowwolf/openwrt编译clash失败

### ISSUE THREAD

**Issue by feifan1113** [frainzy1477/luci-app-clash#321]
无论是集成编译还是完整编译，还是说x86  armv8都无法编译报错
![image](https://user-images.githubusercontent.com/57245399/87852792-9e091100-c937-11ea-8618-417636ffc9cb.png)

**Comment by feifan1113** [comment]
单独编译也报错

**Comment by frainzy1477** [comment]
> 单独编译也报错

我编译没有问题
https://github.com/frainzy1477/Actions-Lean-OpenWrt/actions

**Comment by feifan1113** [comment]
> > 单独编译也报错
> 
> 我编译没有问题
> https://github.com/frainzy1477/Actions-Lean-OpenWrt/actions

解决了，把clash的源码改成777权限就行了 好奇怪

**Comment by feifan1113** [comment]
> > > 单独编译也报错
> > 
> > 
> > 我编译没有问题
> > https://github.com/frainzy1477/Actions-Lean-OpenWrt/actions
> 
> 解决了，把clash的源码改成777权限就行了 好奇怪

之前是775权限会报错
