### ISSUE TITLE
无法下载内核

### ISSUE THREAD

**Issue by WROIATE** [frainzy1477/luci-app-clash#322]
下载一定时间便自动收起日志停止下载
![Snipaste_2020-07-20_17-33-31](https://user-images.githubusercontent.com/44677306/87922913-3675d180-caaf-11ea-8954-9c5e685a226f.png)

**Comment by frainzy1477** [comment]
> 下载一定时间便自动收起日志停止下载
> ![Snipaste_2020-07-20_17-33-31](https://user-images.githubusercontent.com/44677306/87922913-3675d180-caaf-11ea-8954-9c5e685a226f.png)

您可以手动下载然后上传
