### ISSUE TITLE
启动不了

### ISSUE THREAD

**Issue by bengdan** [frainzy1477/luci-app-clash#324]
root@CatManji:/tmp/upload# opkg install luci-app-clash_v1.7.5.5_all.ipk 
Installing luci-app-clash (v1.7.5.5) to root...
Configuring luci-app-clash.
sh: out of range

![image](https://user-images.githubusercontent.com/35016845/88247152-4e2ba080-cccf-11ea-9494-51819c04849e.png)

**Comment by frainzy1477** [comment]
> root@CatManji:/tmp/upload# opkg install luci-app-clash_v1.7.5.5_all.ipk
> Installing luci-app-clash (v1.7.5.5) to root...
> Configuring luci-app-clash.
> sh: out of range
> 
> ![image](https://user-images.githubusercontent.com/35016845/88247152-4e2ba080-cccf-11ea-9494-51819c04849e.png)

我卸载，然后重新安装, 没有遇到任何问题. 你重新安装看看

![image](https://user-images.githubusercontent.com/49537471/88259509-03bd1a80-ccf5-11ea-9dcb-9deaeb8eac01.png)

**Comment by jlzsss** [comment]
我也是启动不了。
日志报错如下：
time="2020-07-23T15:55:15+08:00" level=fatal msg="Parse config error: yaml: line 155: did not find expected key"

**Comment by frainzy1477** [comment]
> 我也是启动不了。
> 日志报错如下：
> time="2020-07-23T15:55:15+08:00" level=fatal msg="Parse config error: yaml: line 155: did not find expected key"

你要看看config.yaml  155行, 你发日志我不会知道问题

**Comment by jlzsss** [comment]
我试了一下用ssr可以启动，用v2ray无法启动。

**Comment by bengdan** [comment]
> > root@CatManji:/tmp/upload# opkg install luci-app-clash_v1.7.5.5_all.ipk
> > Installing luci-app-clash (v1.7.5.5) to root...
> > Configuring luci-app-clash.
> > sh: out of range
> > ![image](https://user-images.githubusercontent.com/35016845/88247152-4e2ba080-cccf-11ea-9494-51819c04849e.png)
> 
> 我卸载，然后重新安装, 没有遇到任何问题. 你重新安装看看
> 
> ![image](https://user-images.githubusercontent.com/49537471/88259509-03bd1a80-ccf5-11ea-9dcb-9deaeb8eac01.png)

重启试过，不行

**Comment by bengdan** [comment]
time="2020-07-24T02:02:21Z" level=fatal msg="Parse config error: Proxy 0: ssr view:3 initialize cipher error: cipher not supported"
