### ISSUE TITLE
new clash core 1.0.0-1 ssr problem

### ISSUE THREAD

**Issue by jonesjedi** [frainzy1477/luci-app-clash#328]
我用新版本 1.7.5.5 里面要使用SSR所以我用了最新的 1.0.0-1 的clash内核，但是报这个错误 tls1.2_ticket_auth incorrect magic number，请问一般是什么情况才会报这个错误

**Comment by tces1** [comment]
我在使用1.0.0-1的时候，ssr也出现问题，配置不报错，运行的现象跟节点挂掉一样，但是同样的yaml文件使用clashr内核就没有问题，是不是1.0.0-1 有什么问题？

**Comment by bengdan** [comment]
新版的Clash使用SSR需要更新yaml配置文件，可以去这里转换一下配置：
* https://acl4ssr.netlify.app/
* 注意客户端参数
![image](https://user-images.githubusercontent.com/35016845/89123455-12c87780-d502-11ea-9c18-1111d1080ba5.png)

**Comment by actg** [comment]
同样的问题，用了楼上的转换工具，也一样不能使用

**Comment by ifelsend007** [comment]
各位大侠，请问下，怎么安装clash core/ctun呢？我已经按照提示下载并且upload了那些文件，但还是显示没有install。
![image](https://user-images.githubusercontent.com/69746526/90328614-4e6a4380-dfd0-11ea-9959-aaaad553ebe7.png)

**Comment by tces1** [comment]
> 我在使用1.0.0-1的时候，ssr也出现问题，配置不报错，运行的现象跟节点挂掉一样，但是同样的yaml文件使用clashr内核就没有问题，是不是1.0.0-1 有什么问题？

已经解决 大家检查一下yaml里这两个key "protocolparam"和"obfsparam" 要修改成"protocol-param"和"obfs-param" 要不然不报错也连不上

**Comment by actg** [comment]
yaml里面并没有 "protocolparam"和"obfsparam" ，没法修改，最新版本ipk依旧不能使用

**Comment by frainzy1477** [comment]
> yaml里面并没有 "protocolparam"和"obfsparam" ，没法修改，最新版本ipk依旧不能使用
不是ipk,就是你在用的clash内核, clashr内核就支持protocolparam"和"obfsparam， 最新的clash内核支持protocol-param"和"obfs-param.
