### ISSUE TITLE
[Need Help]开启 `fake-ip-filter`过滤后 就无法查询本地域名记录

### ISSUE THREAD

**Issue by Aincvy** [frainzy1477/luci-app-clash#329]
![image](https://user-images.githubusercontent.com/8110347/88474862-454ffe80-cf5d-11ea-9844-f03b620c7b94.png)

## 其他信息

- `192.168.200.1` unbound 服务
- 在openwrt上执行`nslookup omv.mylab 192.168.200.1`  是能搜索到的。

## 预期的行为
不加 `fake-ip-filter` 也是可以访问本地记录的，但是 ping 不通， 所以想过滤下，让本地ip不使用`fake-ip`。 

## 更多的信息
直接请求 5300 端口，是能查询到的。
![image](https://user-images.githubusercontent.com/8110347/88475000-9ca29e80-cf5e-11ea-9548-8c18231fdd6e.png)

**Comment by frainzy1477** [comment]
你的NAMESERVER问题，不能用192.168.200.1:53

![image](https://user-images.githubusercontent.com/49537471/88475821-e347c700-cf65-11ea-878b-189e4f0966ba.png)

**Comment by Aincvy** [comment]
@frainzy1477 感谢回复， 不过好像不是这个问题。 似乎是 dnsmasq的转发问题  
BTW, openwrt 的地址是`192.168.200.2` ， unbound 在pfSense 上，地址是`192.168.200.1`

目前的dnsmasq 配置是这样的，因为完全是自用的配置，所以去掉了几个限制。

![image](https://user-images.githubusercontent.com/8110347/88476123-7124b180-cf68-11ea-9226-a7d7c030d461.png)
