### ISSUE TITLE
GEOIP数据库自动更新

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#33]
GEOIP数据库可否和服务器订阅一样，设置自动定时更新。谢谢

**Comment by ztechie** [comment]
这个库更新特别慢，不用在意，偶尔更新一下就好

**Comment by wangxin6** [comment]
> 这个库更新特别慢，不用在意，偶尔更新一下就好

请教一下如何设置让路由器自身流量番茄？

**Comment by ztechie** [comment]
这好像是先有鸡和先有🥚的问题，配置文件被墙无法下载，不能翻，就是自身翻.也先的配置文件啊

**Comment by frainzy1477** [comment]
> 这个库更新特别慢，不用在意，偶尔更新一下就好
