### ISSUE TITLE
谷歌网时不时的打不开，其他的网页可以

### ISSUE THREAD

**Issue by bengdan** [frainzy1477/luci-app-clash#330]
* 谷歌网时不时的打不开，其他的网页可以，问题出现频率比较高。

![image](https://user-images.githubusercontent.com/35016845/88888639-4b9ded80-d271-11ea-9250-637693ed871a.png)

**Comment by javierzhang0504** [comment]
一模一样的问题

**Comment by bengdan** [comment]
> 一模一样的问题，经常google超时很久，有时候重新开关插件有效，有时又无效。
> 当google显示超时时候，很多国外网站都无法访问，都显示“您的链接不是私密链接”之类的。
> 这时候虽然显示YouTube正常，但也经常一直转圈无法加载，不过netflix却可以正常观看，不受影响，

补充的好

**Comment by DuY90** [comment]
同样的问题，启动后一个小时不到就会GOOGLE超时！

**Comment by Hackerl** [comment]
可能是DNS没起来, 可以停止插件再启动插件.
我这种情况发生在我重启路由器, 然后发现www.google.com的dns解析不是fake IP.

**Comment by Hackerl** [comment]
在Fake IP模式下，DNS应该都会返回保留地址，每次当我无法访问谷歌时，我发现DNS返回的不是保留地址，那么毫无疑问这个IP是被污染了的。所以问题出现在，DNS响应本该是由Clash返回的保留地址，现在却不生效了。
我根据OpenWrt提供的系统日志进行分析, 发现由于IPv6接口重拨，会导致Dnsmasq重启，并且重启之后"/etc/config/dhcp"配置文件会变化，里面最重要的配置项list server "127.0.0.1#5300"不见了。
这个配置是将所有DNS请求转发到Clash，正是因为它消失了，所以DNS返回的都是被污染的IP，而不是期望的Fake IP。
```=
/etc/hotplug.d/iface/20-firewall:
    logger -t firewall "Reloading firewall due to $ACTION of $INTERFACE ($DEVICE)"
    fw3 -q reload
```
fw3重载会导致clash重载:
```bash=
/etc/init.d/clash reload
```
但是/etc/init.d/clash reload会删除list server "127.0.0.1#5300"，然后重启Dnsmasq，然后再也不会添加该选项。
