### ISSUE TITLE
存在大量关于clash-watchdog.sh与kill_watchdog.sh的Error级别的日志

### ISSUE THREAD

**Issue by sddpljx** [frainzy1477/luci-app-clash#331]
最近刚转Clash，并且使用了OpenWrt自带的日志功能记录了日志，发现每一分钟就有关于clash-watchdog.sh与kill_watchdog.sh的Error级别的日志，粒度每一分钟，如下图所示：

Time | Level | Log
-- | -- | --
2020/8/1 13:49 | Error | USER root pid 18601 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:48 | Error | USER root pid 13346 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:47 | Error | USER root pid 8105 cmd /usr/share/clash/clash-watchdog.sh
2020/8/1 13:47 | Error | USER root pid 8104 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:46 | Error | USER root pid 2829 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:45 | Error | USER root pid 1645 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:44 | Error | USER root pid 1641 cmd /usr/share/clash/clash-watchdog.sh
2020/8/1 13:44 | Error | USER root pid 1640 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:43 | Error | USER root pid 1636 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:42 | Error | USER root pid 1634 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:41 | Error | USER root pid 1630 cmd /usr/share/clash/clash-watchdog.sh
2020/8/1 13:41 | Error | USER root pid 1629 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:40 | Error | USER root pid 1627 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:39 | Error | USER root pid 1625 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:38 | Error | USER root pid 1617 cmd /usr/share/clash/clash-watchdog.sh
2020/8/1 13:38 | Error | USER root pid 1616 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:37 | Error | USER root pid 1614 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:36 | Error | USER root pid 1612 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:35 | Error | USER root pid 1608 cmd /usr/share/clash/clash-watchdog.sh
2020/8/1 13:35 | Error | USER root pid 1607 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:34 | Error | USER root pid 1605 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:33 | Error | USER root pid 1603 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:32 | Error | USER root pid 1599 cmd /usr/share/clash/clash-watchdog.sh
2020/8/1 13:32 | Error | USER root pid 1598 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:31 | Error | USER root pid 1596 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:30 | Error | USER root pid 1594 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:29 | Error | USER root pid 1590 cmd /usr/share/clash/clash-watchdog.sh
2020/8/1 13:29 | Error | USER root pid 1589 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:28 | Error | USER root pid 1587 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:27 | Error | USER root pid 1581 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:26 | Error | USER root pid 1576 cmd /usr/share/clash/clash-watchdog.sh
2020/8/1 13:26 | Error | USER root pid 1575 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:25 | Error | USER root pid 1572 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:24 | Error | USER root pid 1570 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:23 | Error | USER root pid 1566 cmd /usr/share/clash/clash-watchdog.sh
2020/8/1 13:23 | Error | USER root pid 1565 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:22 | Error | USER root pid 1560 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:21 | Error | USER root pid 1558 cmd /usr/share/clash/kill_watchdog.sh
2020/8/1 13:20 | Error | USER root pid 1554 cmd /usr/share/clash/clash-watchdog.sh
2020/8/1 13:20 | Error | USER root pid 1553 cmd /usr/share/clash/kill_watchdog.sh

虽然不影响正常使用，但是还是想来问一下，万一导致路由器重启了也很难搞。。。

**Comment by cnekol** [comment]
![image](https://user-images.githubusercontent.com/3054962/89257527-effca700-d658-11ea-90c1-e126fbd729e9.png)
![image](https://user-images.githubusercontent.com/3054962/89257628-1fabaf00-d659-11ea-97f0-a47da8be33c5.png)
遇到同样的问题。但我自己去后台看了暂时没看出个所以然来，没影响使用就没管了先。

**Comment by frainzy1477** [comment]
这不是问题
