### ISSUE TITLE
还是老问题，google系的服务间歇性无法访问。

### ISSUE THREAD

**Issue by javierzhang0504** [frainzy1477/luci-app-clash#337]
已使用最新版本插件及内核，无论fake-ip还是redir-host
google系列均用着用着就掉无法访问。
此时youtube可以正常显示页面，但无法看视频。
netflix正常可看。
翻了之前被关闭的一样问题，也没找到怎么设置，求助。

**Comment by javierzhang0504** [comment]
> #330
> 设置fake-ip的模式，不能上网的时候，在OpenWrt上使用"dig [www.google.com"看返回的ip。如果返回的是fake](http://www.google.com%22%E7%9C%8B%E8%BF%94%E5%9B%9E%E7%9A%84ip%E3%80%82%E5%A6%82%E6%9E%9C%E8%BF%94%E5%9B%9E%E7%9A%84%E6%98%AFfake) ip，说明是clash内部问题，返回的不是fake ip说明是dns问题。
> 或"cat /etc/config/dhcp"查看是否用有"server 127.0.0.1#5300"这个参数。

感谢，我先看看。

**Comment by lloyd18** [comment]
用的官方源码，同样问题
