### ISSUE TITLE
编译出错 求大佬指导下！！

### ISSUE THREAD

**Issue by Umomboom** [frainzy1477/luci-app-clash#34]
在Ubuntu 19.04下编译出错 附上出错信息 启用root都还是不行 求大佬指导下使用方法 

make[3]: Entering directory '/home/h/lede/package/luci-app-clash'
touch /home/h/lede/build_dir/target-x86_64_musl/luci-app-clash-0.31.0/.prepared_a1f59917f6d0e121cc3b34a6df7857c9_6664517399ebbbc92a37c5bb081b5c53_check
/home/h/lede/package/luci-app-clash/tools/po2lmo/src/po2lmo /home/h/lede/package/luci-app-clash/po/zh-cn/clash.po /home/h/lede/package/luci-app-clash/po/zh-cn/clash.zh-cn.lmo
bash: /home/h/lede/package/luci-app-clash/tools/po2lmo/src/po2lmo: Permission denied
make[3]: *** [Makefile:87: /home/h/lede/build_dir/target-x86_64_musl/luci-app-clash-0.31.0/.prepared_a1f59917f6d0e121cc3b34a6df7857c9_6664517399ebbbc92a37c5bb081b5c53] Error 126
make[3]: Leaving directory '/home/h/lede/package/luci-app-clash'
time: package/luci-app-clash/compile#0.06#0.03#0.10
make[2]: *** [package/Makefile:109: package/luci-app-clash/compile] Error 2
make[2]: Leaving directory '/home/h/lede'
make[1]: *** [package/Makefile:103: /home/h/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/h/lede'
make: *** [/home/h/lede/include/toplevel.mk:218：world] 错误 2

**Comment by ztechie** [comment]
/home/h/lede/package/luci-app-clash/tools/po2lmo/src/po2lmo: Permission denied 给这个文件执行权限，错误提示说的很明白了

**Comment by Umomboom** [comment]
怎么给他权限 chomd 777么

**Comment by frainzy1477** [comment]
> 启用root

别用启用root编译

**Comment by Umomboom** [comment]
那我该怎么解决这个错误呢？ 给整个clash包加上chmod 777权限么

**Comment by ztechie** [comment]
chmod +x /home/h/lede/package/luci-app-clash/tools/po2lmo/src/po2lmo
