### ISSUE TITLE
iptables 有多条 --set-mark 规则时，下一条会错误将上一条打上标记，导致不能联网

### ISSUE THREAD

**Issue by harv** [frainzy1477/luci-app-clash#341]
https://github.com/frainzy1477/luci-app-clash/blob/fd17bc98fb4e35fa5d1542a36170341e6db6ea21/root/etc/init.d/clash#L392-L393

china 中的地址会在 localnetwork 的时候被标记

我改成下面的就正常了
```
iptables -t mangle -I PREROUTING -m set ! --match-set localnetwork dst -m set ! --match-set china dst -j MARK --set-mark "$PROXY_FWMARK"

**Comment by hkq3323** [comment]
按照楼主的方法改了ipk文件后还是不能上网，客户端就是启动不了
