### ISSUE TITLE
compilling just stopped at "configure: error: Invalid kernel source directory /lib/modules/5.4.0-47-generic/source"

### ISSUE THREAD

**Issue by mh4nx7net** [frainzy1477/luci-app-clash#343]
here for log discription
```
checking pkg-config is at least version 0.9.0... yes
configure: error: Invalid kernel source directory /lib/modules/5.4.0-47-generic/source
make[2]: *** [Makefile:76: /home/dev/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/ipset-7.3/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
make[2]: Leaving directory '/home/dev/openwrt/package/network/utils/ipset'
time: package/network/utils/ipset/compile#14.77#2.80#18.68
make[1]: *** [package/Makefile:113: package/network/utils/ipset/compile] Error 2
make[1]: Leaving directory '/home/dev/openwrt'
make: *** [/home/dev/openwrt/include/toplevel.mk:227: package/luci-app-clash/compile] Error 2
```

then, what actually mistake's is ?
i just following these guide 
` make package/luci-app-clash/compile V=99`

**Comment by frainzy1477** [comment]
> here for log discription
> 
> ```
> checking pkg-config is at least version 0.9.0... yes
> configure: error: Invalid kernel source directory /lib/modules/5.4.0-47-generic/source
> make[2]: *** [Makefile:76: /home/dev/openwrt/build_dir/target-mips_24kc_musl/linux-ath79_generic/ipset-7.3/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
> make[2]: Leaving directory '/home/dev/openwrt/package/network/utils/ipset'
> time: package/network/utils/ipset/compile#14.77#2.80#18.68
> make[1]: *** [package/Makefile:113: package/network/utils/ipset/compile] Error 2
> make[1]: Leaving directory '/home/dev/openwrt'
> make: *** [/home/dev/openwrt/include/toplevel.mk:227: package/luci-app-clash/compile] Error 2
> ```
> 
> then, what actually mistake's is ?
> i just following these guide
> ` make package/luci-app-clash/compile V=99`

i recommend using github action to compiler if is the single app
