### ISSUE TITLE
Openwrt编译支持

### ISSUE THREAD

**Issue by ZimuSama** [frainzy1477/luci-app-clash#345]
可否提供feeds的支持以便在编译openwrt固件时能够将clash打包进去？

**Comment by PaTTeeL** [comment]
同问，好像不支持在feeds.conf.default中加src-git clash https://github.com/frainzy1477/luci-app-clash
执行 ./scripts/feeds update -a
显示lean/feeds/clash.tmp/info/.files-packageinfo.mk:1: *** target pattern contains no '%'.  Stop.
希望能支持直接添加

**Comment by frainzy1477** [comment]
试试    src-git clash https://github.com/frainzy1477/luci-app-clash.git

**Comment by ZimuSama** [comment]
似乎目录和脚本还有点问题，应该要再写一些包相关的索引




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "frainzy1477/luci-app-clash"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月10日(星期六) 晚上9:36
收件人:&nbsp;"frainzy1477/luci-app-clash"<luci-app-clash@noreply.github.com&gt;;
抄送:&nbsp;"子沐H₂"<3229329616@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [frainzy1477/luci-app-clash] Openwrt编译支持 (#345)





 
试试    src-git clash https://github.com/frainzy1477/luci-app-clash.git

**Comment by PaTTeeL** [comment]
> 
> 
> 试试 src-git clash https://github.com/frainzy1477/luci-app-clash.git

没变化，一样的错误，lean/feeds/clash.tmp/info/.files-packageinfo.mk:1: *** target pattern contains no '%'.  Stop.
其他成功引用的项目，repo的结构上貌似多了一层，就是现在根目录的文件结构除了.github,lincese和readme.md之外都集中在一个目录例如luci-app-clash，就是https://github.com/frainzy1477/luci-app-clash.git/luci-app-clash/(makefile,luasrc,po/zh-cn……)，不知道是不是这个原因？

**Comment by ZimuSama** [comment]
之前有试过建一个新仓库把这些放到一个单独的目录里，但还是会报错。之前和室友调的时候感觉是makefile里面缺了些东西，但是工程太大了没精力调了
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "frainzy1477/luci-app-clash"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月10日(星期六) 晚上10:34
收件人:&nbsp;"frainzy1477/luci-app-clash"<luci-app-clash@noreply.github.com&gt;;
抄送:&nbsp;"子沐H₂"<3229329616@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [frainzy1477/luci-app-clash] Openwrt编译支持 (#345)





  
试试 src-git clash https://github.com/frainzy1477/luci-app-clash.git
  
没变化，一样的错误，lean/feeds/clash.tmp/info/.files-packageinfo.mk:1: *** target pattern contains no '%'.  Stop.
 其他成功引用的项目，repo的结构上貌似多了一层，就是现在根目录的文件结构除了.github,lincese和readme.md之外都集中在一个目录例如luci-app-clash，就是https://github.com/frainzy1477/luci-app-clash.git/luci-app-clash/(makefile,luasrc,po/zh-cn……)，不知道是不是这个原因？
