### ISSUE TITLE
Why imported config file was changed

### ISSUE THREAD

**Issue by a13519** [frainzy1477/luci-app-clash#349]
When manually import or specify the config.yaml, the luci-app-clash changes the settings without any notification, this includes: secret, the dns port, etc. Can you fix this?

thanks,

**Comment by frainzy1477** [comment]
> When manually import or specify the config.yaml, the luci-app-clash changes the settings without any notification, this includes: secret, the dns port, etc. Can you fix this?
> 
> thanks,
you can disable such settings in custom dns

**Comment by gbaoye** [comment]
> > When manually import or specify the config.yaml, the luci-app-clash changes the settings without any notification, this includes: secret, the dns port, etc. Can you fix this?
> > thanks,
> > you can disable such settings in custom dns

为什么不更新了

**Comment by frainzy1477** [comment]
> > > When manually import or specify the config.yaml, the luci-app-clash changes the settings without any notification, this includes: secret, the dns port, etc. Can you fix this?
> > > thanks,
> > > you can disable such settings in custom dns
> 
> 为什么不更新了

你可以PR
