### ISSUE TITLE
v0.32 点击config页面无法加载出错

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#35]
错误信息如下：
![屏幕快照 2019-08-16 上午11 13 38](https://user-images.githubusercontent.com/24645789/63141554-b8948500-c018-11e9-8b8e-6680276fc305.JPEG)

返回v0.31没有问题

**Comment by wangxin6** [comment]
X86架构没有此问题。aarch64_cortex-a53_armv8，PI 3B有此问题

**Comment by hackenfu** [comment]
我是x64软路由，一样的问题

**Comment by hackenfu** [comment]
配的是最新的clash 0.15.1-dev

**Comment by wangxin6** [comment]
> 配的是最新的clash 0.15.1-dev

我软路由用的lean编译版本没问题，pi用的官方固件出问题。

**Comment by hackenfu** [comment]
> > 配的是最新的clash 0.15.1-dev
> 
> 我软路由用的lean编译版本没问题，pi用的官方固件出问题。

我软路由是官方固件18.0.4

**Comment by frainzy1477** [comment]
> 错误信息如下：
> ![屏幕快照 2019-08-16 上午11 13 38](https://user-images.githubusercontent.com/24645789/63141554-b8948500-c018-11e9-8b8e-6680276fc305.JPEG)
> 
> 返回v0.31没有问题
更新了
