### ISSUE TITLE
请问Clash for Openwrt 的源码在哪里？

### ISSUE THREAD

**Issue by a13519** [frainzy1477/luci-app-clash#350]
请问Clash for Openwrt 的源码在哪里？
是不公开了吗？为什么？这会造成安全隐患。。。。。

**Comment by frainzy1477** [comment]
> 请问Clash for Openwrt 的源码在哪里？
> 是不公开了吗？为什么？这会造成安全隐患。。。。。
什么意思，开源码你看不到了吗？
