### ISSUE TITLE
放在lean-openwrt里编译报错

### ISSUE THREAD

**Issue by Kinodi** [frainzy1477/luci-app-clash#37]
make[3]: Entering directory `/home/openwrt/lede/package/openwrt-packages/luci-app-clash'
touch /home/openwrt/lede/build_dir/target-x86_64_musl/luci-app-clash-0.35.0/.prepared_e81ff253bb4c9b0d4cdc391353430123_6664517399ebbbc92a37c5bb081b5c53_check
/home/openwrt/lede/package/openwrt-packages/luci-app-clash/tools/po2lmo/src/po2lmo /home/openwrt/lede/package/openwrt-packages/luci-app-clash/po/zh-cn/clash.po /home/openwrt/lede/package/openwrt-packages/luci-app-clash/po/zh-cn/clash.zh-cn.lmo
bash: /home/openwrt/lede/package/openwrt-packages/luci-app-clash/tools/po2lmo/src/po2lmo: Permission denied
make[3]: *** [/home/openwrt/lede/build_dir/target-x86_64_musl/luci-app-clash-0.35.0/.prepared_e81ff253bb4c9b0d4cdc391353430123_6664517399ebbbc92a37c5bb081b5c53] Error 126
make[3]: Leaving directory `/home/openwrt/lede/package/openwrt-packages/luci-app-clash'
time: package/openwrt-packages/luci-app-clash/compile#0.02#0.00#0.09
make[2]: *** [package/openwrt-packages/luci-app-clash/compile] Error 2
make[2]: Leaving directory `/home/openwrt/lede'
make[1]: *** [/home/openwrt/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/openwrt/lede'
make: *** [world] Error 2

**Comment by frainzy1477** [comment]
> make[3]: Entering directory `/home/openwrt/lede/package/openwrt-packages/luci-app-clash' touch /home/openwrt/lede/build_dir/target-x86_64_musl/luci-app-clash-0.35.0/.prepared_e81ff253bb4c9b0d4cdc391353430123_6664517399ebbbc92a37c5bb081b5c53_check /home/openwrt/lede/package/openwrt-packages/luci-app-clash/tools/po2lmo/src/po2lmo /home/openwrt/lede/package/openwrt-packages/luci-app-clash/po/zh-cn/clash.po /home/openwrt/lede/package/openwrt-packages/luci-app-clash/po/zh-cn/clash.zh-cn.lmo bash: /home/openwrt/lede/package/openwrt-packages/luci-app-clash/tools/po2lmo/src/po2lmo: Permission denied make[3]: *** [/home/openwrt/lede/build_dir/target-x86_64_musl/luci-app-clash-0.35.0/.prepared_e81ff253bb4c9b0d4cdc391353430123_6664517399ebbbc92a37c5bb081b5c53] Error 126 make[3]: Leaving directory `/home/openwrt/lede/package/openwrt-packages/luci-app-clash'
> time: package/openwrt-packages/luci-app-clash/compile#0.02#0.00#0.09
> make[2]: *** [package/openwrt-packages/luci-app-clash/compile] Error 2
> make[2]: Leaving directory `/home/openwrt/lede' make[1]: *** [/home/openwrt/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2 make[1]: Leaving directory `/home/openwrt/lede'
> make: *** [world] Error 2

https://github.com/frainzy1477/luci-app-clash/commit/0811ca484d4f77dd57afee5b9284fd10b42c3537
