### ISSUE TITLE
通过代理更新配置

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#41]
订阅URL托管在gist上，但是gist.github.com被屏蔽。
订阅在更新的时候，会先停止客户端，造成订阅无法更新。
能否增加选项，通过代理更新。
谢谢

![屏幕快照 2019-09-07 下午8 53 17](https://user-images.githubusercontent.com/24645789/64475160-7d1d4e80-d1b1-11e9-9eed-455504bc8d7b.JPEG)

**Comment by wangxin6** [comment]
或者更新保存为临时文件完成后，再覆盖重启

**Comment by wangxin6** [comment]
好像有点问题，是不是要路由器代理自身流量才能通过代理更新？

**Comment by wangxin6** [comment]
gist托管规则，但是被墙可以解决么？谢谢

**Comment by cielpy** [comment]
> gist托管规则，但是被墙可以解决么？谢谢

Gist 可以配合加速服务，就可以顺利访问了 https://ghproxy.com/

基于开源项目 https://github.com/hunshcn/gh-proxy 信息敏感的话可以自己搭一个
