### ISSUE TITLE
外部控制端口格式设置

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#43]
‘设置’-‘代理端口设置’-‘外部控制端口’格式能否改为 255.255.255.255:0000的形式。谢谢。

**Comment by wangxin6** [comment]
比如：0.0.0.0:9191，或者:127.0.0.1:9191

**Comment by wangxin6** [comment]
或者按照sukk blog提到的方式获取地址

在 OpenWrt 上获取 LAN IP 的方法是 uci get network.lan.ipaddr。当然用户也可以自己决定 Clash 的外部控制监听的 IP。

本文采用 CC BY-NC-SA 4.0 许可协议，著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
作者：Sukka
来源：KoolClash - 在 Koolshare LEDE 上使用 Clash | Sukka's Blog
链接：https://blog.skk.moe/post/how-koolclash-developed/

**Comment by wangxin6** [comment]
自动获取LAN IP的后遗症：zerotier远程进入路由器以后，Clash外部控制无法打开了。对远程来说此时路由器IP地址不是内网地址。

**Comment by frainzy1477** [comment]
> 自动获取LAN IP的后遗症：zerotier远程进入路由器以后，Clash外部控制无法打开了。对远程来说此时路由器IP地址不是内网地址。

我修改了v1.0.2   0.0.0.0:9191

**Comment by wangxin6** [comment]
纯属探讨：固定0.0.0.0（简单），或者读取配置文件（原生），或者页面自定义（灵活）。哪种更适合？
