### ISSUE TITLE
menuconfig界面下无法显示luci-app-clash

### ISSUE THREAD

**Issue by Zack0617** [frainzy1477/luci-app-clash#44]
将源码加入到官方源码编译，make menuconfig时，在service目录，无法找到luci-app-clash选项。反复验证后发现，如果将lean的ssr源码一同加入，如果在menuconfig界面也勾选上luci-app-ssr plus时，可以找到clash，如果取消掉ssr plus，clash也无法显示……这两者有什么依赖关系吗？

**Comment by frainzy1477** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/49537471/64479843-6d245f80-d1ef-11e9-9aef-d0fb8215d232.png)
![Screenshot_6](https://user-images.githubusercontent.com/49537471/64479844-6dbcf600-d1ef-11e9-8bb6-18d84f46c9a5.png)

我用lean的源码编译没有问题

**Comment by Zack0617** [comment]
@frainzy1477 哇，大佬反应这么快，亲自回复，太激动了！！！
你可以试试1806或者官方源的最新源码，只加入你的luci-app-clash，然后你再去luci>Services下看看，应该是找不到这个选项的，至少我直接使用官方源码是这样的。（如果把lean的ssr源码加进去并勾选上，然后也就可以找到clash了）。
lean源码中luci部分应该使用的是lede1701的luci，跟1806和1907有点不样，有些地方不太兼容。

**Comment by Zack0617** [comment]
@frainzy1477 试了下官方的17.01.7,  18.06.4, 1907都有这个问题。不知道是我哪里操作不对还是……？这个源码有具体要求放哪个位置吗？我是放在了openwrt>package下，openwrt>feeds>luci>applications下也试过，都有问题呢…………

**Comment by frainzy1477** [comment]
> @frainzy1477 试了下官方的17.01.7, 18.06.4, 1907都有这个问题。不知道是我哪里操作不对还是……？这个源码有具体要求放哪个位置吗？我是放在了openwrt>package下，openwrt>feeds>luci>applications下也试过，都有问题呢…………

我先试试

**Comment by frainzy1477** [comment]
> @frainzy1477 试了下官方的17.01.7, 18.06.4, 1907都有这个问题。不知道是我哪里操作不对还是……？这个源码有具体要求放哪个位置吗？我是放在了openwrt>package下，openwrt>feeds>luci>applications下也试过，都有问题呢…………

修问题了  https://github.com/frainzy1477/luci-app-clash/commit/433157263097462a8e0687d99874d8817964f363   
DEPENDS:=+luci +luci-base +iptables +dnsmasq-full +coreutils +coreutils-nohup +bash +wget +ipset

**Comment by frainzy1477** [comment]
> @frainzy1477 试了下官方的17.01.7, 18.06.4, 1907都有这个问题。不知道是我哪里操作不对还是……？这个源码有具体要求放哪个位置吗？我是放在了openwrt>package下，openwrt>feeds>luci>applications下也试过，都有问题呢…………

修问题了 

SUBMENU:=2. Clash
DEPENDS:=+luci +luci-base +iptables +dnsmasq-full +coreutils +coreutils-nohup +bash +wget +ipset

![image](https://user-images.githubusercontent.com/49537471/64490606-3a32a800-d291-11e9-8168-44d0ea4a3311.png)

**Comment by Zack0617** [comment]
谢谢，很快就解决了这个问题。
