### ISSUE TITLE
1.0.2版本的surge2clash的订阅有问题

### ISSUE THREAD

**Issue by zcluo** [frainzy1477/luci-app-clash#45]
https://tgbot.lbyczf.com/surge2clash?url=.https://
日子里url=后面多了个.

**Comment by frainzy1477** [comment]
> https://tgbot.lbyczf.com/surge2clash?url=.https://
> 日子里url=后面多了个.
没有问题， 你就要输入订阅地址不要添加https://tgbot.lbyczf.com/surge2clash?url=

**Comment by zcluo** [comment]
我没加那段，这个是从日志拷出来发现的

**Comment by frainzy1477** [comment]
> 我没加那段，这个是从日志拷出来发现的

你把日志出来
