### ISSUE TITLE
WIKI fake-ip 使用规则

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#5]
对于第一点没看懂：

`不要改你的设备的网络设置，将网关设置或者DNS`

**Comment by wangxin6** [comment]
fake-ip-range 不是必须的吧？

`fake-ip-range: 198.18.0.1/16`

**Comment by wangxin6** [comment]
如果config.yaml已经指定

`dns:`
`  enable: true`

是否luci里面可以不用再启用DNS转发？

**Comment by frainzy1477** [comment]
> 如果config.yaml已经指定
> 
> `dns:`
> ` enable: true`
> 
> 是否luci里面可以不用再启用DNS转发？

必须启用DNS转发

**Comment by frainzy1477** [comment]
> fake-ip-range 不是必须的吧？
> 
> `fake-ip-range: 198.18.0.1/16`

you can comment out if you do not understand how the range works

**Comment by frainzy1477** [comment]
> 对于第一点没看懂：
> 
> `不要改你的设备的网络设置，将网关设置或者DNS`

Do not set custom ip or gateway in LAN settings as in KoolClash, use default settings.

**Comment by wangxin6** [comment]
Thanks
