### ISSUE TITLE
safari无法打开外部控制

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#50]
1. clash外部控制访问的页面为` http://192.168.1.3:9090/ui/ ‘，补全为 ’http://192.168.1.3:9090/ui/#/proxies‘ 后可以打开

2. yacd外部控制一直停留为ip地址，端口，密码网页。在系统日志中发现有如下记录：
`Sat Sep 14 15:21:48 2019 daemon.err uhttpd[2389]: Model clash/overview returns SimpleForm but is dispatched via cbi(),`
`Sat Sep 14 15:21:48 2019 daemon.err uhttpd[2389]: please change admin/services/clash to use the form() action instead.`

**Comment by frainzy1477** [comment]
> 1. clash外部控制访问的页面为` http://192.168.1.3:9090/ui/ ‘，补全为 ’[http://192.168.1.3:9090/ui/#/proxies‘](http://192.168.1.3:9090/ui/#/proxies%E2%80%98) 后可以打开
> 2. yacd外部控制一直停留为ip地址，端口，密码网页。在系统日志中发现有如下记录：
>    `Sat Sep 14 15:21:48 2019 daemon.err uhttpd[2389]: Model clash/overview returns SimpleForm but is dispatched via cbi(),`
>    `Sat Sep 14 15:21:48 2019 daemon.err uhttpd[2389]: please change admin/services/clash to use the form() action instead.`

试试 v1.0.9  https://github.com/frainzy1477/luci-app-clash/releases/download/v1.0.9/luci-app-clash_1.0.9_all.ipk

**Comment by wangxin6** [comment]
赞
