### ISSUE TITLE
三个小问题

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#51]
1. clash日志里的时间是GMT时间，不是本地时间
2. 系统日志里仍有大量提示：
`Sun Sep 15 03:24:41 2019 daemon.err uhttpd[2381]: Model clash/actconfig returns SimpleForm but is dispatched via cbi(),` 
` Sun Sep 15 03:24:41 2019 daemon.err uhttpd[2381]: please change admin/services/clash/config to use the form() action instead.` 
3. 每次升级后，配置页面需要重新设置，不知是否可以升级时保留。

**Comment by Cakewalk598** [comment]
官方源码编译的固件clash中的访问控制ip 设置无法保存。

**Comment by Zack0617** [comment]
1.我编译的lean版本，只要一启动软件，这个IP就会变成0000,不管怎么修改都一样。
2.一直困扰我的一个问题，用clash之后，电脑和手机端看Netflix没有问题,也比较顺畅，但是field tv盒子上Netflix老是报错，要不软件无法运行，要不提示我在使用代理。盒子系统为原版美版系统。之前在0.36版本的时候也出现这个问题，但是把DNS代理打开就可以解决，后来的版本一直解决不了

**Comment by frainzy1477** [comment]
> 1. GMT时间

1.日志里的时间没办法改
2＆3 更新了

**Comment by frainzy1477** [comment]
> 官方源码编译的固件clash中的访问控制ip 设置无法保存。

修好了, 重新上传v1.1.0

**Comment by frainzy1477** [comment]
> 1.我编译的lean版本，只要一启动软件，这个IP就会变成0000,不管怎么修改都一样。
> 2.一直困扰我的一个问题，用clash之后，电脑和手机端看Netflix没有问题,也比较顺畅，但是field tv盒子上Netflix老是报错，要不软件无法运行，要不提示我在使用代理。盒子系统为原版美版系统。之前在0.36版本的时候也出现这个问题，但是把DNS代理打开就可以解决，后来的版本一直解决不了

1。不懂你的意思IP就会变成0000
2. 我没试过所以不知道怎么回事

**Comment by wangxin6** [comment]
问题解决，谢谢
