### ISSUE TITLE
系统日志中存在的错误信息

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#53]
不知道是否算错误信息？
`Tue Sep 17 22:33:22 2019 daemon.err uhttpd[2381]: Model clash/upconfig returns SimpleForm but is dispatched via cbi(),`
`Tue Sep 17 22:33:22 2019 daemon.err uhttpd[2381]: please change admin/services/clash/config/upconfig to use the form() action instead.`

**Comment by wangxin6** [comment]
和之前的信息相似，但是内容少许不应：
原来的：` Model clash/actconfig returns SimpleForm`和` admin/services/clash/config`

**Comment by shikkoku** [comment]
Duplicate of #51 下载最新版本试试。

**Comment by wangxin6** [comment]
已经最新版。信息和之前的不一样。

**Comment by frainzy1477** [comment]
> 不知道是否算错误信息？
> `Tue Sep 17 22:33:22 2019 daemon.err uhttpd[2381]: Model clash/upconfig returns SimpleForm but is dispatched via cbi(),`
> `Tue Sep 17 22:33:22 2019 daemon.err uhttpd[2381]: please change admin/services/clash/config/upconfig to use the form() action instead.`

好的，等v1.1.1.1

**Comment by wangxin6** [comment]
为什么怎么多1？

**Comment by frainzy1477** [comment]
> 为什么怎么多1？

我这边没有问题， 但我知道你的op那里有问题

**Comment by frainzy1477** [comment]
> 不知道是否算错误信息？
> `Tue Sep 17 22:33:22 2019 daemon.err uhttpd[2381]: Model clash/upconfig returns SimpleForm but is dispatched via cbi(),`
> `Tue Sep 17 22:33:22 2019 daemon.err uhttpd[2381]: please change admin/services/clash/config/upconfig to use the form() action instead.`

修好了
