### ISSUE TITLE
fack-ip 模式下爱奇艺客户端不能正常使用

### ISSUE THREAD

**Issue by slitilanber** [frainzy1477/luci-app-clash#54]
fack-IP模式，vmesh/ws协议，默认配置
iPad的爱奇艺 和Android 的奇艺果客户端多数视频不能加载，提示网络错误。
redir-host模式,aria2-rpc连接上但不能加载配置，ddns也异常。
如何解决?

**Comment by frainzy1477** [comment]
> fack-IP模式，vmesh/ws协议，默认配置
> iPad的爱奇艺 和Android 的奇艺果客户端多数视频不能加载，提示网络错误。
> redir-host模式,aria2-rpc连接上但不能加载配置，ddns也异常。
> 如何解决?

启用DNS转发试试

![image](https://user-images.githubusercontent.com/49537471/65227736-08ce8f00-da7e-11e9-90a0-60675995392c.png)

**Comment by frainzy1477** [comment]
> > fack-IP模式，vmesh/ws协议，默认配置
> > iPad的爱奇艺 和Android 的奇艺果客户端多数视频不能加载，提示网络错误。
> > redir-host模式,aria2-rpc连接上但不能加载配置，ddns也异常。
> > 如何解决?
> 
> 启用DNS转发试试
> 
> ![image](https://user-images.githubusercontent.com/49537471/65227736-08ce8f00-da7e-11e9-90a0-60675995392c.png)

dns nameservers有问题那你修改吧， 还是假fallback试试
