### ISSUE TITLE
clash下shield TV 开启Netflix报错nw－2－5,有时nw－3－5

### ISSUE THREAD

**Issue by Zack0617** [frainzy1477/luci-app-clash#55]
clash下shield TV 开启Netflix报错nw－2－5,有时n－3－5，但是手机端和电脑端Netflix播放正常。ssr下shiled TV也能正常播放Netflix。路由器固件为lean源码编译的4.19.72。折腾很久了，一直找不到原因。

**Comment by frainzy1477** [comment]
> clash下shield TV 开启Netflix报错nw－2－5,有时n－3－5，但是手机端和电脑端Netflix播放正常。ssr下shiled TV也能正常播放Netflix。路由器固件为lean源码编译的4.19.72。折腾很久了，一直找不到原因。

启用DNS转发试试

**Comment by Zack0617** [comment]
启用了还是不行，在0.36版本的时候启用DNS转发可以解决，后来的版本都不可以

**Comment by Zack0617** [comment]
可能跟我盒子有关，买的国行然后刷的美版系统
