### ISSUE TITLE
dial DIRECT error: All DNS requests failed

### ISSUE THREAD

**Issue by wtser** [frainzy1477/luci-app-clash#57]
DNS 配置
![image](https://user-images.githubusercontent.com/2093743/65326486-2a498b00-dbe4-11e9-910e-f885d46eba1c.png)

一段时间后会突然无法正常访问网页，查看日志发现如下错误
```
time="2019-09-20T12:15:44Z" level=warning msg="dial DIRECT error: All DNS requests failed"
time="2019-09-20T12:15:45Z" level=warning msg="dial DIRECT error: All DNS requests failed"
time="2019-09-20T12:15:46Z" level=warning msg="dial DIRECT error: All DNS requests failed"
```

以及 timeout
```
time="2019-09-20T12:22:19Z" level=warning msg="dial DIRECT error: dial tcp 45.79.107.111:80: i/o timeout"
```

**Comment by frainzy1477** [comment]
> DNS 配置
> ![image](https://user-images.githubusercontent.com/2093743/65326486-2a498b00-dbe4-11e9-910e-f885d46eba1c.png)
> 
> 一段时间后会突然无法正常访问网页，查看日志发现如下错误
> 
> ```
> time="2019-09-20T12:15:44Z" level=warning msg="dial DIRECT error: All DNS requests failed"
> time="2019-09-20T12:15:45Z" level=warning msg="dial DIRECT error: All DNS requests failed"
> time="2019-09-20T12:15:46Z" level=warning msg="dial DIRECT error: All DNS requests failed"
> ```
> 
> 以及 timeout
> 
> ```
> time="2019-09-20T12:22:19Z" level=warning msg="dial DIRECT error: dial tcp 45.79.107.111:80: i/o timeout"
> ```

是dns nameservers的问题， 你自己可以修改了吧， 我没问题

**Comment by frainzy1477** [comment]
更新 clash ipk   v0.15.3

**Comment by frainzy1477** [comment]
![image](https://user-images.githubusercontent.com/49537471/65375553-c22e8f80-dc4b-11e9-917d-b5ba39f7a411.png)

**Comment by wtser** [comment]
@frainzy1477 能否将上图的配置代码贴一下，供我测试参考 谢谢

**Comment by wangxin6** [comment]
少了一行字ipv6: false？

**Comment by shikkoku** [comment]
fake-ip模式不是说dns只要加一条DNS就可以了吗？都不用加fallback组了吧？
