### ISSUE TITLE
预先编译的1.1.1配置文件allow-lan的值为空，路由器下的设备不能访问网络

### ISSUE THREAD

**Issue by BurningC4** [frainzy1477/luci-app-clash#58]
RT

**Comment by frainzy1477** [comment]
allow-lan的不可能为空

luci-app-clash/root/etc/config/clash

![image](https://user-images.githubusercontent.com/49537471/65380919-7ce57e80-dc9a-11e9-8824-0fc1f47127fe.png)


https://github.com/frainzy1477/luci-app-clash/blob/master/luasrc/model/cbi/clash/port.lua

![image](https://user-images.githubusercontent.com/49537471/65380917-5de6ec80-dc9a-11e9-9500-c54affd58299.png)

**Comment by alexyangjie** [comment]
我也遇到一样的问题，从上一个版本覆盖安装升级上来，配置文件里没有allow_lan，导致所有设备无法上网，排查了很久才发现这个问题。手动加上之后就好了。
