### ISSUE TITLE
Bypass Lan IP 导致客户端无法上网

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#6]
启用Bypass Lan IP模式，并添加客户端IP后，发现客户端无法上外网。

**Comment by frainzy1477** [comment]
> 启用Bypass Lan IP模式，并添加客户端IP后，发现客户端无法上外网。

我自己可以上网， 你再试试吧， 能上网但IP不走客户端

**Comment by wangxin6** [comment]
问题依旧存在。和我使用的网段有关么？
