### ISSUE TITLE
依赖在openwrt-19.07上有所不同

### ISSUE THREAD

**Issue by BurningC4** [frainzy1477/luci-app-clash#60]
rt luci方面的依赖去掉吧。。。

**Comment by Zack0617** [comment]
@BurningC4  你编译了1907，能正常运行吗？之前很多版本编译过官方固件都无法正常运行 ……,1806和1907都是这样。

**Comment by frainzy1477** [comment]
> rt luci方面的依赖去掉吧。。。

你自己可以fork掉吧
