### ISSUE TITLE
绕过系统代理

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#61]
参考CFW：https://docs.cfw.lbyczf.com/rao-guo-xi-tong-dai-li

增加“自定义系统代理需要染过的域名或IP”的功能，以解决部分应用检测到系统代理会拒绝响应（例如网易云音乐uwp，ntp server，Windows本地连接检测等）

**Comment by wangxin6** [comment]
利用dnsmasq的ipset功能，把不需要代理的域名解析至ipset，然后iptables里匹配ipset?

**Comment by frainzy1477** [comment]
> 利用dnsmasq的ipset功能，把不需要代理的域名解析至ipset，然后iptables里匹配ipset?

http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html

https://github.com/frainzy1477/dnsmasq/blob/master/dnsmasq.conf.example

# Add other name servers here, with domain specs if they are for
# non-public domains.
#server=/localnet/192.168.0.1

# Example of routing PTR queries to nameservers: this will send all
# address->name queries for 192.168.3/24 to nameserver 10.1.2.3
#server=/3.168.192.in-addr.arpa/10.1.2.3

server=/google.com/1.2.3.4 --server=/www.google.com/2.3.4.5 will send queries for *.google.com to 1.2.3.4, except *www.google.com, which will go to 2.3.4.5

**Comment by wangxin6** [comment]
V1.1.3

**Comment by wangxin6** [comment]
检查dnsmasq的配置，返回空值。不知道/tmp/dnsmasq.clash/custom_list.conf文件是否已经生效。

`root@:~# uci get dhcp.@dnsmasq[0].confdir` 
` uci: Entry not found`

**Comment by wangxin6** [comment]
我的理解是指定dnsmasq的配置文件夹，重启dnsmasq
uci add_list dhcp.@dnsmasq[0].confdir=/var/dnsmasq.d/custom_list.conf
uci commit dhcp

**Comment by frainzy1477** [comment]
> 检查dnsmasq的配置，返回空值。不知道/tmp/dnsmasq.clash/custom_list.conf文件是否已经生效。
> 
> `root@:~# uci get dhcp.@dnsmasq[0].confdir`
> ` uci: Entry not found`

![Screenshot_3](https://user-images.githubusercontent.com/49537471/65628679-88bba280-e004-11e9-93e7-0c7169383fe3.png)


![Screenshot_3](https://user-images.githubusercontent.com/49537471/65628720-9709be80-e004-11e9-82f8-c04104b40c1c.png)


![Screenshot_4](https://user-images.githubusercontent.com/49537471/65628732-9c670900-e004-11e9-903e-10a893d0e71c.png)

**Comment by wangxin6** [comment]
`uci add_list dhcp.@dnsmasq[0].confdir=/tmp/dnsmasq.d/`
`uci commit dhcp`

这两个命令要自行执行，还是启动脚本会自动检查confdir是否指向正确的目录？

**Comment by frainzy1477** [comment]
default config directory of dnsmasq is /var/etc/dnsmasq.conf.*
Within it have all system network config, with config-dir=/tmp/dnsmasq.d
All configuration related to dnsmasq must be placed on linked in /tmp/dsnmasq.d  which is /var/dnsmasq.d  , this is generated automatically by default.

Either way, you can also set your own config-dir but must make sure is added to /var/etc/dnsmasq.conf.*

**Comment by frainzy1477** [comment]
you xan read more about dnsmasq if you are interested,  closing issue now
