### ISSUE TITLE
OpenWrt R9.10.1 lean 原版luci启动问题

### ISSUE THREAD

**Issue by shikkoku** [frainzy1477/luci-app-clash#62]
在界面中点击Start Client无反应，无法应用启动。可能是因为lean大把luci升级过有关。

**Comment by frainzy1477** [comment]
> 在界面中点击Start Client无反应，无法应用启动。可能是因为lean大把luci升级过有关。

我编译R9.10.1 lean没有问题哦，可以启动

![image](https://user-images.githubusercontent.com/49537471/65631655-89efce00-e00a-11e9-964c-a8e2a872f3f8.png)


![Screenshot_1](https://user-images.githubusercontent.com/49537471/65631767-c8858880-e00a-11e9-8c3c-7d508ebf7fcc.png)

**Comment by shikkoku** [comment]
![Capture](https://user-images.githubusercontent.com/4697177/65650452-8295e800-e03d-11e9-9e6a-72b5a79cb6da.JPG)
点击停止客户端显示的未保存配置
![Capture1](https://user-images.githubusercontent.com/4697177/65650459-89bcf600-e03d-11e9-8727-7c803b9aebdc.JPG)
点击启动客户端显示的未保存配置
![Annotation 2019-09-26 010940](https://user-images.githubusercontent.com/4697177/65650472-9b060280-e03d-11e9-96fa-acf185a2fc13.jpg)
我刚编译的lean源码固件
从你图中看到，你的luci版本和我不一致，你的源码好像是旧的。

**Comment by frainzy1477** [comment]
更新了
