### ISSUE TITLE
设置-自定义列表在启用／停用客户端后被关闭

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#64]
设定订阅自动更新，每次更新完成后设置-自定义列表被关闭。或者手动启用／停用客户端后，也可以发现自定义列表被关闭。

**Comment by frainzy1477** [comment]
> 设定订阅自动更新，每次更新完成后设置-自定义列表被关闭。或者手动启用／停用客户端后，也可以发现自定义列表被关闭。

重新上传了

**Comment by wangxin6** [comment]
多谢
