### ISSUE TITLE
duplicate name

### ISSUE THREAD

**Issue by jw8013** [frainzy1477/luci-app-clash#65]
time="2019-09-27T05:32:42Z" level=fatal msg="Parse config error: Proxy 日本7 500M Amazon vip2 X1 V2 is the duplicate name"

- {"name":"日本7 500M Amazon vip2 X1 V2","type":"vmess","server":"**这里是域名**","port":*,"uuid":"*","alterId":2,"cipher":"auto"}
- {"name":"日本7 500M Amazon vip2 X1 V2","type":"vmess","server":" **这里是IP** ","port":*,"uuid":"*","alterId":2,"cipher":"auto"}

机场订阅服务器本来都是域名，但是其中一个同时生成了IP，导致节点重复了，
clash就不能启动，手动删掉重复的一个节点，本地上传就可以用了

**Comment by frainzy1477** [comment]
duplicate name
这个不是luci的事，  clash代理配置中不能有相同的名称.
![image](https://user-images.githubusercontent.com/49537471/65750982-2cf43500-e13c-11e9-8fb0-923e5b93572c.png)
