### ISSUE TITLE
运行一段时间后，部分网站无法访问

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#66]
运行一段时间后，部分网站无法访问。IP也无法检测出来。停用／启用客户端以后，问题消失。clash日志和系统日志无异常。

问题现象：
![屏幕快照 ](https://user-images.githubusercontent.com/24645789/65818262-965e6b80-e242-11e9-8465-0e994be882d2.JPEG)

DNS设置：
![屏幕快照](https://user-images.githubusercontent.com/24645789/65818317-0c62d280-e243-11e9-8789-8baaf7b7b9ff.JPEG)

**Comment by wangxin6** [comment]
也不知道是core的问题，还是luci的问题。。。

**Comment by frainzy1477** [comment]
nameserver 怎么写192.168.1.1?? 问题是你的dns nameserver问题， 我这边没有问题哦

**Comment by frainzy1477** [comment]
how can 192.168.1.1 resolve a domain name? pls use a correct dns nameserver

**Comment by wangxin6** [comment]
fake-ip模式dns只是解析IP做规则判断。192.168.1.1是光猫地址，作为上游dns。

**Comment by wangxin6** [comment]
因为是运行一段时间以后出的问题，和dnsmasq的dns缓存有关系么？

**Comment by RealKiro** [comment]
![image](https://user-images.githubusercontent.com/33367701/65827176-17a91300-e2c2-11e9-8086-0428d848284b.png)
www.google.com 也无法打开
![image](https://user-images.githubusercontent.com/33367701/65827195-3f987680-e2c2-11e9-8e18-f4a5fb2226b7.png)

**Comment by wangxin6** [comment]
访问github有个错误代码：cache-hnd18729-HND

**Comment by wangxin6** [comment]
现在把网络--dhcp/dns--高级设置-DNS 查询缓存的大小设置为0，看一下效果

**Comment by wangxin6** [comment]
对redir-host模式来说，dns缓存应该是有存在的必要。
