### ISSUE TITLE
1.2.0订阅的节点跑到自定义里去了

### ISSUE THREAD

**Issue by Kinodi** [frainzy1477/luci-app-clash#68]
如题

**Comment by frainzy1477** [comment]
> 如题

v2ssr2clash订阅的节点到自定义配置, 想用v2ssr2clash配置在客户端页面配置类型选自定义配置

clash订阅的节点到订阅配置，想用配置在客户端页面配置类型选订阅配置

**Comment by frainzy1477** [comment]
重新下载，修一点问题

**Comment by Kinodi** [comment]
ok     发现如果通过自定义规则URL下载规则后重写策略组proxy   需要把节点一个一个添加进去   而不像你默认的策略组proxy会自动添加

**Comment by frainzy1477** [comment]
> ok 发现如果通过自定义规则URL下载规则后重写策略组proxy 需要把节点一个一个添加进去 而不像你默认的策略组proxy会自动添加

更新了
