### ISSUE TITLE
上传配置文件后，clash自动重启

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#7]
目前上传新的配置文件后，clash不会自动重启。需要在‘客户端’-’启动‘ 取消勾选后重新勾选启动。能否增加上传配置文件后，clash自动重启。

**Comment by frainzy1477** [comment]
> 目前上传新的配置文件后，clash不会自动重启。需要在‘客户端’-’启动‘ 取消勾选后重新勾选启动。能否增加上传配置文件后，clash自动重启。

https://github.com/frainzy1477/luci-app-clash/commit/3f707a4820b3008ec8dc7a062a6ee0d0260fabc3

**Comment by frainzy1477** [comment]
> > 目前上传新的配置文件后，clash不会自动重启。需要在‘客户端’-’启动‘ 取消勾选后重新勾选启动。能否增加上传配置文件后，clash自动重启。
> 
> [3f707a4](https://github.com/frainzy1477/luci-app-clash/commit/3f707a4820b3008ec8dc7a062a6ee0d0260fabc3)

you can look at commit and manually add it, will include in next release
