### ISSUE TITLE
启动不能并全路由断网

### ISSUE THREAD

**Issue by aoi777** [frainzy1477/luci-app-clash#70]
斐讯K3，刷了这个固件https://right.com.cn/forum/thread-1007971-1-1.html。
然后下载了clashr_0.15.5_bcm53xx_arm_cortex-a9_armv7.ipk
luci-app-clash_1.2.1-2_all.ipk，两个ipk安装成功。
主程序，选择clash订阅地址导入不了节点，试过两个订阅，可以在cfw上用，但是路由上完全刷不出来节点。然后换了ssr模式，刷出来节点了。
找不到节点选择？？，试着勾选启用，应用并保存。
然后主程序 客户端一直显示未运行，clash模式显示为fake ip。两个外部控制为未运行。
之后就开始断网无法直连，删除了两个ipk都无法恢复。试了几轮都是如此。
恢复出厂，提交问题。

**Comment by frainzy1477** [comment]
> 斐讯K3，刷了这个固件[https://right.com.cn/forum/thread-1007971-1-1.html。](https://right.com.cn/forum/thread-1007971-1-1.html%E3%80%82)
> 然后下载了clashr_0.15.5_bcm53xx_arm_cortex-a9_armv7.ipk
> luci-app-clash_1.2.1-2_all.ipk，两个ipk安装成功。
> 主程序，选择clash订阅地址导入不了节点，试过两个订阅，可以在cfw上用，但是路由上完全刷不出来节点。然后换了ssr模式，刷出来节点了。
> 找不到节点选择？？，试着勾选启用，应用并保存。
> 然后主程序 客户端一直显示未运行，clash模式显示为fake ip。两个外部控制为未运行。
> 之后就开始断网无法直连，删除了两个ipk都无法恢复。试了几轮都是如此。
> 恢复出厂，提交问题。

1.ssr或v2 你要用v2ssr2clash订阅,在客户端页面配置类型选自定义配置
2.断网无法 .可以ssh   service clash stop 会好了

**Comment by wclmgcd** [comment]
> 斐讯K3，刷了这个固件[https://right.com.cn/forum/thread-1007971-1-1.html。](https://right.com.cn/forum/thread-1007971-1-1.html%E3%80%82)
> 然后下载了clashr_0.15.5_bcm53xx_arm_cortex-a9_armv7.ipk
> luci-app-clash_1.2.1-2_all.ipk，两个ipk安装成功。
> 主程序，选择clash订阅地址导入不了节点，试过两个订阅，可以在cfw上用，但是路由上完全刷不出来节点。然后换了ssr模式，刷出来节点了。
> 找不到节点选择？？，试着勾选启用，应用并保存。
> 然后主程序 客户端一直显示未运行，clash模式显示为fake ip。两个外部控制为未运行。
> 之后就开始断网无法直连，删除了两个ipk都无法恢复。试了几轮都是如此。
> 恢复出厂，提交问题。

你Clash选择的是那个版本的，我选v6v7都不行，我用大雕的自己编译，或者安装以编译好的都是不能启动，你的问题解决了吗？
