### ISSUE TITLE
打开网页弹出安全提示

### ISSUE THREAD

**Issue by Zack0617** [frainzy1477/luci-app-clash#71]
1.官方源编译的1907固件，电脑打开网页或者手机打开app，时不时的弹出安全提示，具体记不得了，大概是证书不匹配，链接不安全，是否继续。
2.运行一段时间后fq不正常❨速度慢或者无法fq❩，需要重启一下系统才可以❨lean固件好像也一样❩。
3.官方源❨1907或者1806❩下，需要点击两次才可以启动clash，lean下只需要一次。

**Comment by wangxin6** [comment]
是使用fake-ip模式并开了dns转发么？
我有类似情况，猜测是dnsmasq缓存的原因造成的。
能否请优化一下watchdog里面的“端口转发重启”和“DNS转发劫持”

**Comment by Zack0617** [comment]
@wangxin6  默认就是fake IP模式，可以更改吗？没有找到选项在哪改？

**Comment by Zack0617** [comment]
在wiki里找到了，晚上试试看

**Comment by wangxin6** [comment]
https://github.com/Dreamacro/clash/issues/345
