### ISSUE TITLE
客户端启用按钮需要保存2次

### ISSUE THREAD

**Issue by ztechie** [frainzy1477/luci-app-clash#72]
客户端启用按钮需要保存2次，第一次日志显示客户端被禁用 ，在保存一次就正常运行了，取消勾选一次就停止了，奇怪的问题再次在新版本复现

**Comment by Zack0617** [comment]
我早发现了，这个问题是在官方1806和1907下才有，lean固件正常

**Comment by ztechie** [comment]
luci-app-clash_1.1.6-1之前的版本正常，之后的版本不正常，需要2次，openwrt 18.06.4自己编译的

**Comment by frainzy1477** [comment]
I have stopped maintaining repo for official openwrt, lean luci master work fine, you can chose to make changes by yourself if want to. Have no time to maintain two repos
![image](https://user-images.githubusercontent.com/49537471/67263303-476ec380-f4da-11e9-8b80-ac2563b925a8.png)

**Comment by frainzy1477** [comment]
更新了，试试看

**Comment by ztechie** [comment]
用opkg remove 卸载后有用opkg install安装的，还是老样子

**Comment by frainzy1477** [comment]
> 用opkg remove 卸载后有用opkg install安装的，还是老样子

好的，官方OP的luci 和lean luci master 一样, 官方OP的我停止更新

![image](https://user-images.githubusercontent.com/49537471/67282587-b06b3100-f504-11e9-9bea-7e73dc56bf68.png)

**Comment by ztechie** [comment]
表示遗憾，不过还是感谢你的付出，难道是官方的bug？lean源码最终不是也得更新官方的么
