### ISSUE TITLE
`pidof clash` 返回 /etc/init.d/clash 自身PID

### ISSUE THREAD

**Issue by peter-tank** [frainzy1477/luci-app-clash#75]
手动复制到 Chaos Calmer branch `r47335`方式安装，/bin/pidof 会返回 init script 自身PID，导致自杀。
以 `ps -w` 代替， watchdog 正常后台：
```diff
diff --git a/root/etc/init.d/clash b/root/etc/init.d/clash
index 7047469..8f740d4 100644
--- a/root/etc/init.d/clash
+++ b/root/etc/init.d/clash
@@ -42,6 +42,7 @@ config_type=$(uci get clash.config.config_type 2>/dev/null)
 	[ -n "$(grep -w "/usr/share/clash/clash.sh" $CRON_FILE)" ] && sed -i '/\/usr\/share\/clash\/clash.sh/d' $CRON_FILE
 	[ -n "$(grep -w "/usr/share/clash/v2ssr.sh" $CRON_FILE)" ] && sed -i '/\/usr\/share\/clash\/v2ssr.sh/d' $CRON_FILE
 	auto=$(uci get clash.config.auto_update 2>/dev/null)
+	auto=${auto:-0}
 	if [ $auto -eq 1 ]; then
 	[ -z "$(grep -w "/usr/share/clash/clash.sh" $CRON_FILE)" ] && echo "0 $(uci get clash.config.auto_update_time 2>/dev/null) * * * /usr/share/clash/clash.sh" >> $CRON_FILE
 	[ -z "$(grep -w "/usr/share/clash/v2ssr.sh" $CRON_FILE)" ] && echo "0 $(uci get clash.config.auto_update_time 2>/dev/null) * * * /usr/share/clash/v2ssr.sh" >> $CRON_FILE
@@ -239,6 +240,19 @@ custom_list() {
 	sh /usr/share/clash/list.sh  >/dev/null 2>&1
 }
 
+#ccid=$$
+pidof() {
+local pidof=`which pidof`
+local pids
+#echo ccid=$ccid >&2
+#pids=`$pidof "${1}" | grep -wv "$ccid"`
+pids=`ps -w | grep "d /etc/${1}" | grep -v "grep" | awk '{print $1}'`
+if [ -z "$pids" ]; then
+  return 1
+else
+  echo $pids
+fi
+}
 
 start(){
 lang=$(uci get luci.main.lang 2>/dev/null)
@@ -308,7 +322,7 @@ if  [  -f $CONFIG_YAML ] && [ "$(ls -l $CONFIG_YAML|awk '{print int($5/1024)}')"
 	
 	if pidof clash >/dev/null; then
 		add_cron
-		nohup /usr/share/clash/clash-watchdog.sh >/dev/null 2>&1
+		nohup /usr/share/clash/clash-watchdog.sh >/dev/null 2>&1 &
 	
 	fi
 else
```

**Comment by frainzy1477** [comment]
> 手动复制到 Chaos Calmer branch `r47335`方式安装，/bin/pidof 会返回 init script 自身PID，导致自杀。
> 以 `ps -w` 代替， watchdog 正常后台：
> 
> ```diff
> diff --git a/root/etc/init.d/clash b/root/etc/init.d/clash
> index 7047469..8f740d4 100644
> --- a/root/etc/init.d/clash
> +++ b/root/etc/init.d/clash
> @@ -42,6 +42,7 @@ config_type=$(uci get clash.config.config_type 2>/dev/null)
>  	[ -n "$(grep -w "/usr/share/clash/clash.sh" $CRON_FILE)" ] && sed -i '/\/usr\/share\/clash\/clash.sh/d' $CRON_FILE
>  	[ -n "$(grep -w "/usr/share/clash/v2ssr.sh" $CRON_FILE)" ] && sed -i '/\/usr\/share\/clash\/v2ssr.sh/d' $CRON_FILE
>  	auto=$(uci get clash.config.auto_update 2>/dev/null)
> +	auto=${auto:-0}
>  	if [ $auto -eq 1 ]; then
>  	[ -z "$(grep -w "/usr/share/clash/clash.sh" $CRON_FILE)" ] && echo "0 $(uci get clash.config.auto_update_time 2>/dev/null) * * * /usr/share/clash/clash.sh" >> $CRON_FILE
>  	[ -z "$(grep -w "/usr/share/clash/v2ssr.sh" $CRON_FILE)" ] && echo "0 $(uci get clash.config.auto_update_time 2>/dev/null) * * * /usr/share/clash/v2ssr.sh" >> $CRON_FILE
> @@ -239,6 +240,19 @@ custom_list() {
>  	sh /usr/share/clash/list.sh  >/dev/null 2>&1
>  }
>  
> +#ccid=$$
> +pidof() {
> +local pidof=`which pidof`
> +local pids
> +#echo ccid=$ccid >&2
> +#pids=`$pidof "${1}" | grep -wv "$ccid"`
> +pids=`ps -w | grep "d /etc/${1}" | grep -v "grep" | awk '{print $1}'`
> +if [ -z "$pids" ]; then
> +  return 1
> +else
> +  echo $pids
> +fi
> +}
>  
>  start(){
>  lang=$(uci get luci.main.lang 2>/dev/null)
> @@ -308,7 +322,7 @@ if  [  -f $CONFIG_YAML ] && [ "$(ls -l $CONFIG_YAML|awk '{print int($5/1024)}')"
>  	
>  	if pidof clash >/dev/null; then
>  		add_cron
> -		nohup /usr/share/clash/clash-watchdog.sh >/dev/null 2>&1
> +		nohup /usr/share/clash/clash-watchdog.sh >/dev/null 2>&1 &
>  	
>  	fi
>  else
> ```

你可以PR
