### ISSUE TITLE
希望支持頁面修改配置文本﹑讀取配置並更新頁面策略組。

### ISSUE THREAD

**Issue by hxhwing0522** [frainzy1477/luci-app-clash#77]
大佬，我有兩個建議。望大佬希望考慮

1. 希望可以在<配置>頁面上修改配置 
    目前上傳配置﹑自定義配置都只能看，不能頁面修改。每次都要自己修改後，再上傳新配置。

2. 希望在<訂閱&服務器>頁面點擊<讀取節點>後，也會讀取和更新策略組。
    目前在<訂閱&服務器>頁面上傳配置後，點擊<讀取節點>只會讀取配置和更新頁面節點。但是頁面的策略組並沒有隨之更新。

**Comment by Mattraks** [comment]
希望可以下载**规则**时候连同**策略组**一并更新!

**Comment by frainzy1477** [comment]
等新的本版。。。
