### ISSUE TITLE
订阅&服务器 最底部填入三方规则，启动 clash 时总是报规则解析错误，怀疑插件处理 yaml 存在问题

### ISSUE THREAD

**Issue by yellowvii** [frainzy1477/luci-app-clash#79]
非常感谢作者编写这么好用的插件，我在使用中遇到一些问题，希望能得到帮助。

## 环境
openwrt 18.06.4 x86_64 官方 tag 自编译，搭配部分自编译 Lean package ，使用 **clash 0.16.3** 和 **luci-app-clash 1.2.7**

## 问题描述
在 **订阅&服务** 底部填入 [神机规则](https://raw.githubusercontent.com/ConnersHua/Profiles/master/Clash/Pro.yaml) 的 Rule 部分，在插件生成的配置中存在格式错误。反复确认原规则格式不存在问题。

依据 log 查看出错的问题行，有两种错误：

1. 空格被错误删除 **"-DOMAIN-SUFFIX,foo.com,Hijacking"** 
2. 空格连同首字母一同被错误删除 **"-P-CIDR,114.247.28.96/32,Hijacking"** 

具体出问题的行数没有发现规律，而且偶尔会存在多个错误点。

手动修改 **_/usr/share/clash/config/_** 目录下的配置修正错误，即可正常使用。

看到是使用 sed 处理规则替换合并，但是我对 sed 不熟悉，不知道是脚本对规则的兼容性不好，还是 busybox 存在 bug。

**Comment by frainzy1477** [comment]
你要添加到策略组  Hijacking

**Comment by yellowvii** [comment]
> 如果在用是自定义节点要添加到策略组 Hijacking， 如果你的是订阅配置，那问题不是luci的问题
> 如果你写这一样那就是写错啦
> 
> ```
> -DOMAIN-SUFFIX,foo.com,Hijacking  
> -P-CIDR,114.247.28.96/32,Hijacking
> ```
> 
> 是这一样
> 
> ```
>  - DOMAIN-SUFFIX,foo.com,Hijacking
>  - IP-CIDR,114.247.28.96/32,Hijacking
> ```

嗯，原规则的格式是完全正确的，粘贴添加我也有核对过没有出现这种错误，但是经过 shell 脚本处理之后就出现了格式错误。
