### ISSUE TITLE
k3无法启动

### ISSUE THREAD

**Issue by wclmgcd** [frainzy1477/luci-app-clash#82]
如上，该选择什么版本的v7v6都不行，大雕和原版编译的，下载编译好的都不行

**Comment by frainzy1477** [comment]
> 如上，该选择什么版本的v7v6都不行，大雕和原版编译的，下载编译好的都不行

那你去试试openclash,我没用k3不知道哪里有问题

**Comment by wclmgcd** [comment]
选择v5可以了，感谢大佬

**Comment by frainzy1477** [comment]
> 选择v5可以了，感谢大佬

好
