### ISSUE TITLE
怎么下载离线内核

### ISSUE THREAD

**Issue by cjlhll** [frainzy1477/luci-app-clash#83]
在路由器里下不动，下载了离线内核~请问扔到哪个文件夹呢？

**Comment by frainzy1477** [comment]
在更新页下载内核

**Comment by cjlhll** [comment]
> 在更新页下载内核

你好~我的意思是离线内核~在编译的时候直接把我需要的内核编译进去~  因为在更新页下载很慢~经常失败

**Comment by frainzy1477** [comment]
clash
/etc/clash/clash
clashr
/usr/bin/clash

**Comment by cjlhll** [comment]
> clash
> /etc/clash/clash
> clashr
> /usr/bin/clash

clash和clashr分别放到这俩不同的文件夹是吧？谢谢

**Comment by frainzy1477** [comment]
嗯

**Comment by cjlhll** [comment]
> 嗯

好的~  谢谢

**Comment by cjlhll** [comment]
你好~不用修改什么配置文件吗？我放进去后更新页还是显示未安装

**Comment by frainzy1477** [comment]
clash
/usr/share/clash/core_version    0.16.4

clashr
/usr/share/clash/corer_version    0.16.4



![Uploading image.png…]()
