### ISSUE TITLE
FAKE-IP or REDIR-HOST?

### ISSUE THREAD

**Issue by paulgit** [frainzy1477/luci-app-clash#86]
I have noticed that the default DNS configuration from 1.2.9 to 1.30 had changed from REDIR-HOST to FAKE-IP, however I don't fully understand the benefit of one over the other.  

Can you please explain or point me to the relevant documentation (I cannot find it anywhere)

Thanks

**Comment by frainzy1477** [comment]
> I have noticed that the default DNS configuration from 1.2.9 to 1.30 had changed from REDIR-HOST to FAKE-IP, however I don't fully understand the benefit of one over the other.
> 
> Can you please explain or point me to the relevant documentation (I cannot find it anywhere)
> 
> Thanks

you can find out from the author of clash. Clash have two running mode( redir-host and fake-ip), you can decide by yourself which is suitable and best work for you.

https://github.com/Dreamacro/clash
