### ISSUE TITLE
密匙不能为空，无法匹配机场端的设置

### ISSUE THREAD

**Issue by jh3274** [frainzy1477/luci-app-clash#87]
订阅配置为
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
secret: ""

openwrt客户端 设置成空无法保存

**Comment by frainzy1477** [comment]
> 订阅配置为
> port: 7890
> socks-port: 7891
> redir-port: 7892
> allow-lan: true
> mode: Rule
> log-level: info
> external-controller: 127.0.0.1:9090
> secret: ""
> 
> openwrt客户端 设置成空无法保存

你安装是  *_2.ipk ??

**Comment by jh3274** [comment]
是的

frainzy1477 <notifications@github.com> 于 2019年11月30日周六 下午3:33写道：
