### ISSUE TITLE
建議: 配置頁面修改成可編輯保存

### ISSUE THREAD

**Issue by hxhwing0522** [frainzy1477/luci-app-clash#89]
Suggestion: Config webpage can be modify and save.

希望clash的配置頁面可以編輯保存。

目前只能觀看，而不能在頁面上修改編輯。
如果可以編輯保存，會更方便。
希望采納意見。

I hope clash's configuration page can be edited and saved.

Currently, it can only be viewed, but cannot be edited on the page.
It would be more convenient if you could edit and save.
Hope to adopt comments.

![image](https://user-images.githubusercontent.com/35884432/70296258-dfbfce00-1824-11ea-9495-7639d0ba7de7.png)

**Comment by frainzy1477** [comment]
the reason is because if not careful to edit the config file will generate a error , there will be incomplete config.yaml file, it happen several times after i tested reason i disabled the editting

**Comment by frainzy1477** [comment]
I suggest you use the custom config to load your config and modify it.
