### ISSUE TITLE
makefile 报错

### ISSUE THREAD

**Issue by ztechie** [frainzy1477/luci-app-clash#9]
define Package/$(PKG_NAME)/postinst
#!/bin/sh
rm -rf /tmp/luci*
/etc/init.d/clash disable 
丢到openwrt源码编译都会提示line 3: /etc/init.d/clash: No such file or directory

**Comment by cnzgray** [comment]
遇到同样的问题，该postinst应该是ipkg直接安装的时候有用，如果是在编译的时候包含加入则会出问题。
