### ISSUE TITLE
是否考虑增加CI 在线集成编译环境

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#90]
是否考虑增加CI 在线集成编译环境？谢谢

**Comment by frainzy1477** [comment]
还没想

**Comment by frainzy1477** [comment]
> 是否考虑增加CI 在线集成编译环境？谢谢

增加CI 在线集成编译

**Comment by wangxin6** [comment]
没看到workflow。。。

https://help.github.com/en/actions

**Comment by frainzy1477** [comment]
> 没看到workflow。。。
> 
> https://help.github.com/en/actions

。travis.yml 就行了
