### ISSUE TITLE
使用clashr模式，运行几个小时候后，log中出现大量warning

### ISSUE THREAD

**Issue by breakersun** [frainzy1477/luci-app-clash#94]
如下，warning信息始终出现，不会停止：

17:18:46 Logs exceeded limit，cleaning logs now..！
time="2019-12-12T09:18:53Z" level=warning msg="dial DIRECT error: dial tcp4 127.0.0.1:443: connect: connection refused"
time="2019-12-12T09:18:53Z" level=warning msg="dial DIRECT error: dial tcp4 127.0.0.1:443: connect: connection refused"

**Comment by frainzy1477** [comment]
> 如下，warning信息始终出现，不会停止：
> 
> 17:18:46 Logs exceeded limit，cleaning logs now..！
> time="2019-12-12T09:18:53Z" level=warning msg="dial DIRECT error: dial tcp4 127.0.0.1:443: connect: connection refused"
> time="2019-12-12T09:18:53Z" level=warning msg="dial DIRECT error: dial tcp4 127.0.0.1:443: connect: connection refused"

是你的规则问题，你先看看修

**Comment by fish065** [comment]
> 如下，warning信息始终出现，不会停止：
> 
> 17:18:46 Logs exceeded limit，cleaning logs now..！
> time="2019-12-12T09:18:53Z" level=warning msg="dial DIRECT error: dial tcp4 127.0.0.1:443: connect: connection refused"
> time="2019-12-12T09:18:53Z" level=warning msg="dial DIRECT error: dial tcp4 127.0.0.1:443: connect: connection refused"

我也遇到了相同问题，请问你是如何解决的
