### ISSUE TITLE
为什么域名全部是IP地址

### ISSUE THREAD

**Issue by yocosweet** [frainzy1477/luci-app-clash#95]
![批注 2019-12-12 215347](https://user-images.githubusercontent.com/40546262/70717854-24b69980-1d2a-11ea-8e7c-5a4e9a31d626.png)

**Comment by frainzy1477** [comment]
什么域名？？ 你要说清楚

**Comment by yocosweet** [comment]
![批注 2019-12-12 234826](https://user-images.githubusercontent.com/40546262/70727016-ecb75280-1d39-11ea-983c-a19577e5f794.png)
标注红色的地方现在都是ip地址，写的域名规则全部失效了

**Comment by frainzy1477** [comment]
你的dns问题
如果你在用是默认设置不可能有这个问题
![image](https://user-images.githubusercontent.com/49537471/70739346-91915a00-1d51-11ea-8786-3b2c4b10869e.png)
