### ISSUE TITLE
检测是否包含ssr节点处，未考虑rule片段

### ISSUE THREAD

**Issue by Apocalypsor** [frainzy1477/luci-app-clash#96]
在启动时检测是否包含ssr节点处，如果规则的域名包含ssr，那么会识别为使用clashr内核规则，建议改成：
```
checktype=$(grep -c "type: ssr" /etc/clash/config.yaml 2>/dev/null)
```

**Comment by frainzy1477** [comment]
> 在启动时检测是否包含ssr节点处，如果规则的域名包含ssr，那么会识别为使用clashr内核规则，建议改成：
> 
> ```
> checktype=$(grep -c "type: ssr" /etc/clash/config.yaml 2>/dev/null)
> ```

rule 怎么有ssr?? 就检测ssr节点

**Comment by Apocalypsor** [comment]
> > 在启动时检测是否包含ssr节点处，如果规则的域名包含ssr，那么会识别为使用clashr内核规则，建议改成：
> > ```
> > checktype=$(grep -c "type: ssr" /etc/clash/config.yaml 2>/dev/null)
> > ```
> 
> rule 怎么有ssr?? 就检测ssr节点

你这里时检测有没有ssr字段啊，如果你的规则有一条DOMAIN-SUFFIX,ssrtool.com,PROXY这种不就被你当成用clashr内核了

**Comment by frainzy1477** [comment]
> > > 在启动时检测是否包含ssr节点处，如果规则的域名包含ssr，那么会识别为使用clashr内核规则，建议改成：
> > > ```
> > > checktype=$(grep -c "type: ssr" /etc/clash/config.yaml 2>/dev/null)
> > > ```
> > 
> > 
> > rule 怎么有ssr?? 就检测ssr节点
> 
> 你这里时检测有没有ssr字段啊，如果你的规则有一条DOMAIN-SUFFIX,ssrtool.com,PROXY这种不就被你当成用clashr内核了

好的，晚点修

**Comment by frainzy1477** [comment]
修好了
