### ISSUE TITLE
潘多拉固件启动Clash失败

### ISSUE THREAD

**Issue by aglent** [frainzy1477/luci-app-clash#97]
路由器acrh17 安装了恩山论坛的潘多拉固件 因为服务里没有clash 所以在这里下载并安装了clash app，用的是luci-app-clash_1.3.5-2_all.ipk。
Clash控制台里安装了clash核心，配置了订阅，读取了节点和策略组，但是开启clash失败，clash日志里没有相关信息，固件系统日志里有提示找不到/etc/clash/config.yaml，我把/usr/share/clash/config/sub/config.yaml复制到/etc/clash/下，也无法启动clash。
不知道问题出在哪里，能否指点下。

**Comment by frainzy1477** [comment]
> 路由器acrh17 安装了恩山论坛的潘多拉固件 因为服务里没有clash 所以在这里下载并安装了clash app，用的是luci-app-clash_1.3.5-2_all.ipk。
> Clash控制台里安装了clash核心，配置了订阅，读取了节点和策略组，但是开启clash失败，clash日志里没有相关信息，固件系统日志里有提示找不到/etc/clash/config.yaml，我把/usr/share/clash/config/sub/config.yaml复制到/etc/clash/下，也无法启动clash。
> 不知道问题出在哪里，能否指点下。

可能你下载的clash核心不对

**Comment by aglent** [comment]
> 
> 
> > 路由器acrh17 安装了恩山论坛的潘多拉固件 因为服务里没有clash 所以在这里下载并安装了clash app，用的是luci-app-clash_1.3.5-2_all.ipk。
> > Clash控制台里安装了clash核心，配置了订阅，读取了节点和策略组，但是开启clash失败，clash日志里没有相关信息，固件系统日志里有提示找不到/etc/clash/config.yaml，我把/usr/share/clash/config/sub/config.yaml复制到/etc/clash/下，也无法启动clash。
> > 不知道问题出在哪里，能否指点下。
> 
> 可能你下载的clash核心不对

目前安装的clash 核心是 0.16.6版本 是最新的  处理器型号: arm_cortex-a7_neon-vfpv4 内核选择armv7 对吧

**Comment by aglent** [comment]
我发现问题出在安装上
潘多拉固件ssh安装clash，最后一句提示为“Terminated”。
对比OpenWT-LEDE的安装是好的，能正常使用。
是不是这个app不适用于潘多拉固件呢？

**Comment by frainzy1477** [comment]
> 固件

可能是你的固件问题
