### ISSUE TITLE
开启clash后，由外网访问内网服务无法建立连接

### ISSUE THREAD

**Issue by vongoethe** [frainzy1477/luci-app-clash#98]
内网的 NAS 上 Host 了一个 NextCloud 服务，路由器端口映射到外网，使用 V2RAY 和 REDSOCKS2 的时候，使用正常。
换用 CLASH，开启 CLASH 后，无法访问，log 一直提示如下
`"dial DIRECT error: dial tcp4 xxx.xxx.xxx.xxx:xx: connect: connection refused"`
我使用了动态 DNS 服务，DNS 解析没问题，IP 能正确解析出来
不过，DNS 也切换用 FAKE-IP 和 REDIR-HOST，均无法解决
请问是什么原因呢？

**Comment by vongoethe** [comment]
补充一下，提供 NextCloud 服务的机器的本地地址，被我加入了 Access Control 的 Bypass LAN IP 列表里了

**Comment by frainzy1477** [comment]
> 内网的 NAS 上 Host 了一个 NextCloud 服务，路由器端口映射到外网，使用 V2RAY 和 REDSOCKS2 的时候，使用正常。
> 换用 CLASH，开启 CLASH 后，无法访问，log 一直提示如下
> `"dial DIRECT error: dial tcp4 xxx.xxx.xxx.xxx:xx: connect: connection refused"`
> 我使用了动态 DNS 服务，DNS 解析没问题，IP 能正确解析出来
> 不过，DNS 也切换用 FAKE-IP 和 REDIR-HOST，均无法解决
> 请问是什么原因呢？

检查配置规则

**Comment by ztechie** [comment]
NB: 设置->访问控制 fake-ip 不支持不走代理, redir-host 可以了. fake-ip 你也可以在config.yaml的rule加 - SRC-IP-CIDR,192.168.1.201/32,DIRECT 不走代理
