### ISSUE TITLE
停止客户端以后，外网无法访问

### ISSUE THREAD

**Issue by wangxin6** [frainzy1477/luci-app-clash#99]
Luci V1.3.5-1 ／fake-ip模式 ／开启 dns 转发
停止客户端以后，外网无法访问

**Comment by yocosweet** [comment]
一样的情况

**Comment by frainzy1477** [comment]
更新了

**Comment by frainzy1477** [comment]
我这个一样用没有问题
![image](https://user-images.githubusercontent.com/49537471/71240197-791dd280-2343-11ea-937b-bf4b02ca5c09.png)

**Comment by frainzy1477** [comment]
如果开启 dns 转发你的路由器用所以dns是clash的，fake-ip停止客户端以后需要等一会让路由器恢复dns

**Comment by wangxin6** [comment]
开启 dns 转发是为了让路由器自身流量翻墙。当用terminal连上路由器进行软件下载时，可以快速下载。

**Comment by frainzy1477** [comment]
> 开启 dns 转发是为了让路由器自身流量翻墙。当用terminal连上路由器进行软件下载时，可以快速下载。

重新上传 2019/12/20 16:51:00 GMT+8

**Comment by wangxin6** [comment]
不知道新的选项“启用局域网DNS”，“删除局域网DNS”，“局域网dns服务器”对使用单臂路由的有多少影响。试一下再看。谢谢。
